getumbrel/umbrel-apps

tailscale/exports.sh
tailscale/umbrel-app.yml

Detects a Tailscale install failure right before it happens, abuses exports.sh to execute a patch script that runs on the host, patches up the install script, reruns the install command with the patched CLI, and then terminates execution of bad install process.

Fix Tailscale

---

jam/docker-compose.yml
jam/umbrel-app.yml

- joinmarket-webui: [v0.0.6](https://github.com/joinmarket-webui/joinmarket-webui/releases/tag/v0.0.6)
- joinmarket-clientserver: [v0.9.6](https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.9.6)
All notable changes of the UI can be seen in the [Jam v0.0.6 changelog](https://github.com/joinmarket-webui/joinmarket-webui/blob/v0.0.6/CHANGELOG.md)
- increase api request timeout from 60sec to 5min [#34](https://github.com/joinmarket-webui/joinmarket-webui-docker/pull/34)
- update to default config for v0.9.6 [#32](https://github.com/joinmarket-webui/joinmarket-webui-docker/pull/32)

Update Jam to v0.0.6

---

tailscale/docker-compose.yml
tailscale/umbrel-app.yml

This resolves #24 and updates the Tailscale docker version to v1.26.0., which appears to be the current stable release.
Per this post on where to get the SHA256 checksum from:
https://community.getumbrel.com/t/taproot-how-can-we-help/306/9
And following this change as an example:
https://github.com/getumbrel/umbrel-apps/commit/484b538375ddcd0228bb2b0cd91d8602ca86f30f
Appreciate being able to help out.  If I missed something I should be aware of when submitting pull requests, please let me know!

Update Tailscale to v1.26.0

---

bitfeed/docker-compose.yml
bitfeed/umbrel-app.yml

Changes since v2.2.1:
- Visualize transactions replaced/dropped from the mempool.
- Block explorer functionality: look up past blocks and transactions.
- Substantially reduced CPU load on start up.
- Smoother, fancier graphics

Update Bitfeed to v2.3.4

---

sparkkiosk/docker-compose.yml
sparkkiosk/umbrel-app.yml

Service needs to be publicly accessible to return LNURLS - thus disabling umbrel default password protection setting PROXY_AUTH_ADD: "false" - still uses the password generated by umbrel.

Added PROXY_AUTH_ADD: "false"

---

ipfs-podcasting/docker-compose.yml
ipfs-podcasting/umbrel-app.yml

Pushed a new v0.6 docker image. Thought I saw an app store update (automatically) during testing, but my Umbrels (arm & amd) haven't displayed a notification to update to 0.6.

Upgrade IPFS Podcasting to v0.6

---

itchysats/docker-compose.yml
itchysats/umbrel-app.yml

Long was the wait - finally a new ItchySats version!
Note: Users on versions `0.4.x` are still supported for the time being, `0.5.0` is not breaking. However, support for previous protocol version will eventually be discontinued, upgrading is encouraged :)
For detailed changes please refer to the [release changelogs](https://github.com/itchysats/itchysats/releases/).

Upgrade ItchySats to `0.5.0`

---

jam/docker-compose.yml
jam/umbrel-app.yml

- joinmarket-webui: [v0.0.9](https://github.com/joinmarket-webui/joinmarket-webui/releases/tag/v0.0.9)
- joinmarket-clientserver: [v0.9.6](https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.9.6)
All notable changes of the UI can be seen in the [Jam v0.0.9 changelog](https://github.com/joinmarket-webui/joinmarket-webui/blob/v0.0.9/CHANGELOG.md)
- [remove leftover wallet lockfiles](https://github.com/getumbrel/umbrel-apps/pull/52#issuecomment-1169784192) before startup
As [mentioned in the latest PR](https://github.com/getumbrel/umbrel-apps/pull/52#pullrequestreview-1022603593) and what came up during a conversation with @nevets963, we are still tracking "removing Basic Auth" …

Update Jam to v0.0.9

---

ln-visualizer/docker-compose.yml
ln-visualizer/umbrel-app.yml

new features:
- initial sync performance improvements
- can filter by node feature bits
- filter dropdown for node network type (onion vs clearnet)
- new statistics window. Will calculate min/max/total/average for both the entire network and for subgraph being viewed.
- new mode to normalize channel color to min/max range of subgraph

Update LnVisualizer to v0.0.25

---

itchysats/docker-compose.yml
itchysats/umbrel-app.yml

Unfortunately this one slipped through because we closed a previous upgrade PR that included it.
The missing variable is not critical, i.e. the application works without it, but reports may be incorrect.

Add environment variable for ItchySats

---

krystal-bull/docker-compose.yml
krystal-bull/umbrel-app.yml

Updates Krystal Bull docker images to include autologin functionality
The backend image:
https://hub.docker.com/layers/249479785/bitcoinscala/bitcoin-s-oracle-server/1.9.2-42-83cff9a4-SNAPSHOT/images/sha256-ca622219d3502f6970ae920b3c26ed05011de867d51fdb864d9df32914a2bbc1?context=repo
the frontend image: 
https://hub.docker.com/layers/249503207/bitcoinscala/oracle-server-ui/1.9.2-f44ad4a4-SNAPSHOT/images/sha256-1338a36213803e98330d844b4ef877d7e56a149394a985f76f29ff25d016fb04?context=repo

Update Krystal Bull images to include autologin

---

oak-node/docker-compose.yml
oak-node/umbrel-app.yml

Bump to next version, which brings a Nostr bot and ability to send to onion LN addresses.
Tested on an Umbrel VM.

Bump Oak Node to v0.3.2

---

samourai-server/umbrel-app.yml

Samourai Server depends on electrs (local indexer).
https://github.com/getumbrel/umbrel-apps/blob/642a4bd52a2cfbb2431a84b1e9ea1b9a8b9d2273/samourai-server/docker-compose.yml#L80-L84

fix: samourai-server app depends on electrs

---

oak-node/docker-compose.yml
oak-node/umbrel-app.yml

Two main changes:
* charts for the Scheduled Payments view
* for the Nostr bot, users can now change the pubkey from the Oak Node UI
Tested in a VM and on a raspi.

Bump Oak Node to v0.3.3

---

specter-desktop/docker-compose.yml
specter-desktop/umbrel-app.yml

This will update specter desktop to the latest available v1.12.0 including many new features

Update specter desktop app to v1.12.0

---

samourai-server/umbrel-app.yml

Due a port conflict (port 3005) between Samourai Server's Web UI and Plex Companion, the port number for Samourai Server will be changed to 3021 as we cannot change the port number for these Plex Companion apps.

Samourai server Web UI port change

---

krystal-bull/docker-compose.yml
krystal-bull/umbrel-app.yml

This updates Krystal Bull for the 1.9.3 release of bitcoin-s. 
This modifies some configurations on our umbrel deployment as we are no longer specify the [USER id in our docker images](https://github.com/bitcoin-s/bitcoin-s/pull/4601)
I still need to test this with a fresh umbrel install.

2022 08 18 krystal bull update

---

suredbits-wallet/docker-compose.yml
suredbits-wallet/umbrel-app.yml

We are about to cut a 1.9.3 for the Suredbits Wallet.
This modifies some configurations on our umbrel deployment as we are no longer specify the [USER id in our docker images](https://github.com/bitcoin-s/bitcoin-s/pull/4601)
I still need to test this with a fresh umbrel install.

2022 08 16 suredbits wallet update

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

Hey y'all! New Litd release is out. It bundles LND v0.15.1-beta along with some Loop & Pool updates
https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.8.0-alpha

lightning-terminal: bump version to v0.8.0-alpha

---

jam/docker-compose.yml
jam/umbrel-app.yml

- Jam: [v0.1.0](https://github.com/joinmarket-webui/jam/releases/tag/v0.1.0)
All notable changes of the UI can be seen in the [Jam v0.1.0 changelog](https://github.com/joinmarket-webui/jam/blob/v0.1.0/CHANGELOG.md)
- fix: run tor daemon with distinct user https://github.com/joinmarket-webui/jam-docker/pull/61
- fix: make sure non-descriptor wallet is created https://github.com/joinmarket-webui/jam-docker/pull/58 
- fix: remove conditional autostart handling https://github.com/joinmarket-webui/jam-docker/pull/56 
- feat: serve logs https://github.com/joinmarket-webui/jam-docker/pull/51

Update Jam to v0.1.0

---

ln-visualizer/docker-compose.yml
ln-visualizer/umbrel-app.yml

A few visible changes:
- new channel color mapping modes. can map channel color by fee-rate, base-fee, cltv-delta, max-htlc, min-htlc
- new color range ui menu
Also better container security. Only include cert and readonly macaroon in container.

Update Lnvisualizer to 0.0.26

---

jam/docker-compose.yml
jam/umbrel-app.yml

- Jam: [v0.1.1](https://github.com/joinmarket-webui/jam/releases/tag/v0.1.1)
All notable changes of the UI can be seen in the [Jam v0.1.1 changelog](https://github.com/joinmarket-webui/jam/blob/v0.1.1/CHANGELOG.md)
- feat: randomize mandatory fee config values [#66](https://github.com/joinmarket-webui/jam-docker/pull/66)

Update Jam to v0.1.1

---

core-lightning-rtl/docker-compose.yml
core-lightning/docker-compose.yml
elements/docker-compose.yml

For certain versions of docker-compose (currently unknown), all docker-compose manifest versions must match otherwise this error can occur during app installation: `Version mismatch: file /data/umbrel/scripts/support/docker-compose.app_proxy.yml specifies version 3.7 but extension file /data/umbrel/app-data/core-lightning/docker-compose.yml uses version 3.8`
Related issue: https://github.com/getumbrel/umbrel-core-lightning/issues/1

All apps should use docker-compose 3.7 manifest version

---

lnmarkets/docker-compose.yml
lnmarkets/umbrel-app.yml

Patchnote [v1.2.4](https://github.com/ln-markets/umbrel/releases/tag/v1.2.4)
Related PRs: https://github.com/getumbrel/umbrel-apps-gallery/pull/14

Update ln-markets app to v1.2.4

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

Hey y'all! 
Here to update Litd to v0.8.2-alpha which contains the latest version of LND (v0.15.3-beta
https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.8.2-alpha)

lightning-terminal: bump version to v0.8.2-alpha

---

lnmarkets/docker-compose.yml
lnmarkets/umbrel-app.yml

Patchnote: [v1.2.5](https://github.com/ln-markets/umbrel/releases/tag/v1.2.5)
Tested on `arm64` !

Update LN Markets to v1.2.5

---

jam/docker-compose.yml
jam/umbrel-app.yml

- Jam: [v0.1.2](https://github.com/joinmarket-webui/jam/releases/tag/v0.1.2)
All notable changes of the UI can be seen in the [Jam v0.1.2 changelog](https://github.com/joinmarket-webui/jam/blob/v0.1.2/CHANGELOG.md)
- fix: ensure jm working dir exists [#68](https://github.com/joinmarket-webui/jam-docker/pull/68)
- feat(init): use dinit instead of supervisor [#69 ](https://github.com/joinmarket-webui/jam-docker/pull/69)

Update Jam to v0.1.2

---

btcpay-server/docker-compose.yml
btcpay-server/umbrel-app.yml

A few versions ago, we introduced optimizations to btcpay to directly connect to the nbx db for faster querying and better dashboard functionality.

Update BTCPay Server to use direct postgres nbx connection

---

lightning/docker-compose.yml
lightning/umbrel-app.yml

Tested on `arm64` and `amd64` with real sats.

Update Lightning to use LND v0.15.4-beta

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

Here with the update of LiT that includes the LND bump to v0.15.4-beta
https://github.com/lightningnetwork/lnd/releases/tag/v0.15.4-beta

Update Lightning Terminal to v0.8.3-alpha

---

pi-hole/hooks/pre-install
pi-hole/umbrel-app.yml

Platforms using systemd-resolved's DNS Stub Listener (which listens on 53/UDP) will cause the installation of Pi-Hole to fail (as it requires port 53/UDP). This PR adds a pre-install hook to detect if such service is being used and is listening, and to then disable this, and then have the OS use systemd-resolved's upstream resolv.conf file for DNS resolution.

Pi hole pre-install hook to disable systemd-resolved's DNS Stub Listener

---

photoprism/docker-compose.yml
photoprism/umbrel-app.yml

After this version, Photoprism started to separate their images based on OS/Arch. Unless we use the `latest` tag for the image I don't really know how we could proceed to keep this application up-to-date. 
See Docker Hub : https://hub.docker.com/r/photoprism/photoprism/tags

App Update: Photoprism to 221105

---

lightning/data/lnd/lnd.conf
lightning/exports.sh
lightning/umbrel-app.yml

The next major release of Lightning Terminal will require the `--rpcmiddleware.enabled` flag to be set in order to use some new features we've been working on. `litd` will not startup without this flag being set. I am preemptively opening this PR before that release in order to have the LND dependency in order.
More details on what this flag does can be found at https://github.com/lightningnetwork/lnd/pull/5101.

Enable RPC middleware in LND

---

jam/docker-compose.yml
jam/umbrel-app.yml

- Jam: [v0.1.3](https://github.com/joinmarket-webui/jam/releases/tag/v0.1.3)
All notable changes of the UI can be seen in the [Jam v0.1.3 changelog](https://github.com/joinmarket-webui/jam/blob/v0.1.3/CHANGELOG.md)
- feat: wait for `bitcoind` to accept RPC calls [#76](https://github.com/joinmarket-webui/jam-docker/pull/76)

Update Jam to v0.1.3

---

nolooking/docker-compose.yml
nolooking/umbrel-app.yml

From what I can tell, this auth is adding some protection to the payjoin endpoints.
Results in wallets giving messages like:
```
2022-11-10 00:59:48,027 ERROR Error parsing received PSBT
com.sparrowwallet.drongo.psbt.PSBTParseException: Provided string is not a PSBT
```
I think we should remove this auth for now, to fix the app, and inform users to keep their onion private? (Worst they can do is open channels)

Add proxy auth whitelist for nolooking

---

home-assistant/docker-compose.yml
home-assistant/umbrel-app.yml

**Docker Hub :** https://hub.docker.com/layers/homeassistant/home-assistant/2022.11.2/images/sha256-c2c94019e2e9ba4616cccfd5f9abe223f725f984358dc4fd6f6472caa6cb75be?context=explore
**Changelog :** https://www.home-assistant.io/changelogs/core-2022.11
Tested on Linux VM ✅

App Update: HomeAssistant to 2022.11.2

---

lndg/docker-compose.yml
lndg/umbrel-app.yml

Updates LNDg to v1.4.0
https://github.com/cryptosharks131/lndg/releases/tag/v1.4.0
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/51717530?tag=v1.4.0
Note: LNDg can now be accessed without a password by passing `-nologin` in the docker-compose.yml.

App Update: LNDg v1.4.0

---

nolooking/docker-compose.yml
nolooking/umbrel-app.yml

Built for docker here: https://github.com/DanGould/nolooking/actions/runs/3509289629, but renamed so the hash doesn't match. From here on out we're building on tag @chaincase-app/nolooking

Update nolooking to v0.2.0-alpha

---

nextcloud/docker-compose.yml
nextcloud/hooks/pre-start
nextcloud/umbrel-app.yml

This PR adds a hook to cycle through the intermediate versions of Nextcloud from v22 and v25 and installs them in order for us to reliability upgrade users to the latest version (v25).
Tested:
- Upgrade process from v22.1 to v25
- Upgrade process from v22.2 to v25
- Fresh install of v25
... on my `arm64` and `amd64` Umbrels

Nextcloud: Migrate from v22 to v25

---

nitter/docker-compose.yml

Nitter's docker-compose.yml file was missing a version docker-compose interprits as version 1. This then leads to a version mismatch error when combining multiple compose files.

Add version to docker-compose.yml

---

jam/docker-compose.yml
jam/umbrel-app.yml

- Jam: [v0.1.4](https://github.com/joinmarket-webui/jam/releases/tag/v0.1.4)
All notable changes of the UI can be seen in the [Jam v0.1.4 changelog](https://github.com/joinmarket-webui/jam/blob/v0.1.4/CHANGELOG.md)

Update Jam to v0.1.4

---

torq/docker-compose.yml
torq/umbrel-app.yml

Apologies that we only released a week ago but we got a few nice bug fixes in and a new network toggle for changing between mainnet and the various test nets which keeps the data segregated for those who use Torq with a testnet node as well as a main net node.
Tested on a real RaspberryPi

Bump Torq to v0.15.4

---

electrs/docker-compose.yml
electrs/umbrel-app.yml

Tested:
- Umbrel App (frontend)
- Mempool
- BTC RPC Explorer
- Sparrow Wallet (MacOS)
Release notes: https://github.com/romanz/electrs/blob/master/RELEASE-NOTES.md#0910-nov-3-2022

Update Electrs to v0.9.10

---

kollider/docker-compose.yml
kollider/umbrel-app.yml

This fixes a bug on the arm version where pyzmq cannot connect to a hostname. Due to the recent change from hardcoded IPs to hostnames, this broke the Kollider app for some users.

Update Kollider to v1.0.7

---

simple-torrent/docker-compose.yml
simple-torrent/hooks/pre-start
simple-torrent/umbrel-app.yml

This PR adds a migration using a `pre-start` hook to migrate existing installations to use Umbrel's shared downloads directory.
Tested the following cases:
- Creating Umbrel's shared downloads directory if it does not exist
- Migrating an existing install with downloads (tested with 10GB dummy data)
- Migrating an existing install with no downloads
- App restart after migration to ensure it does not run again
Closes #349

Migrate contents of Simple torrent downloads directory to Umbrel's shared downloads directory

---

torq/docker-compose.yml
torq/umbrel-app.yml

Bump Torq to v0.16.3: 
New features:
- Tags! You can now tag channels and nodes!
- Tags can be seen on the channels, forwards and channel inspection pages.
- Navigate using the flow diagram!
- Quicker inspection of channels from both the forwards and channels page using pop out modal.
- Update and close channels from the forwards page
- New Channel table columns for remote node stats.
- New default views for the forwards and channels tables
- Navigate time using the arrow keys on the forwards table, summary page and channel inspect page
Bug fixes:
- Fix bug preventing routing policy updates
- Corrected bug causing the channel balance in the channels table page to be incorrect
- Importing pending open/closing channels properly
- Fetching missing channel ids from vector
- Updating "Import …

Torq v0.16.3

---

lightning/exports.sh
lightning/umbrel-app.yml

Currently LND assumes the RPC port depending on the network that is in use. The previous Bitcoin update uses port `8332` for RPC for all networks. This PR makes use the `$APP_BITCOIN_RPC_PORT` env. var. that is exported by the Bitcoin app.

Allow LND to connect to Bitcoin Core on other networks

---

torq/docker-compose.yml
torq/umbrel-app.yml

Bump Torq to v0.16.6
* Add admin.macaroon support
* You can now filter on tags
* Missing opening and closing channel time is fetched from Torq Vector
* Closed channels no longer logs errors on new forwards
* Fixed timestamp issue prevented fetching from being returned for channel and summary pages.

Update Torq to v0.16.6

---

urbit/docker-compose.yml
urbit/umbrel-app.yml

- Updated Urbit to official v1.16 binary: https://github.com/urbit/vere/releases

Update Urbit to v1.16

---

urbit/docker-compose.yml
urbit/umbrel-app.yml

- Urbit project moved binary to new GH url (urbit/vere); fixing download URL

Fix Urbit retrieval URL

---

urbit/docker-compose.yml
urbit/umbrel-app.yml

In addition to changing the repo, the new releases have a new naming scheme that breaks the previous binary download script ( https://github.com/mopfel-winrux/urbit-umbrel/commits/main/install-urbit.sh ). Don't mean to be annoying! Many things broke with the new release scheme.

Fix urbit binary extraction

---

urbit/docker-compose.yml
urbit/umbrel-app.yml

- Updated Urbit to official v1.17 binary: https://github.com/urbit/vere/releases

Update Urbit to v1.17

---

home-assistant/docker-compose.yml
home-assistant/umbrel-app.yml

Dockerhub: https://hub.docker.com/layers/homeassistant/home-assistant/2023.2.0/images/sha256-dff6ad8d27f40a3c167243f39d9ac4e1177c67b0fd3276be0624673a920664fe?context=explore
Changelog: https://www.home-assistant.io/changelogs/core-2023.2 (includes initial release of new voice assistant)

Update home-assistant to 2023.2.0

---

jam/docker-compose.yml
jam/umbrel-app.yml

- Jam: [v0.1.5](https://github.com/joinmarket-webui/jam/releases/tag/v0.1.5)
- joinmarket-clientserver: [v0.9.9](https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.9.9)
All notable changes of the UI can be seen in the [Jam v0.1.5 changelog](https://github.com/joinmarket-webui/jam/blob/v0.1.5/CHANGELOG.md)

Update Jam to v0.1.5

---

torq/docker-compose.yml
torq/umbrel-app.yml

Update Torq to v0.18.18 
New features: 
- Channel views can now be renamed via the title
- Added filterable columns to Channel view
- Tag sorting
Bug fixes:
- Fixed bug causing race conditions when saving a node
- Activate Streams by default
Tested on real Rasberry PI

Update Torq to v0.18.18

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

Updates Lighting Terminal (litd) to the latest release.
https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.8.6-alpha

Update lightning-terminal to v0.8.6-alpha

---

pi-hole/docker-compose.yml
pi-hole/umbrel-app.yml

Hi,
I had noticed that the changelogs and versioning in `umbrel-app.yml` didn't follow the `docker` github repository of PiHole. I was wondering if there would be a reason?
PiHole Docker Repo: https://github.com/pi-hole/docker-pi-hole/
This PR Updates to the latest version and switched the versioning to follow PiHole's Docker Github versioning.
Tested on AMD VM

Update PiHole to 2023.02.2

---

gitea/docker-compose.yml
gitea/umbrel-app.yml

I'm not sure if we need the MariaDB hash as well, I used the 10.11.2 tag from here: [MariaDB Docker Hub](https://hub.docker.com/layers/library/mariadb/10.11.2/images/sha256-dc249cd0b7e41739fc4c5dbfcfda160afc7d6d1e40ce14ffbe2b62c285dd06ef?context=explore)

Update Gitea to 1.18.5

---

oak-node/docker-compose.yml
oak-node/umbrel-app.yml

Most changes affect the Nostr bot.
I've tested it on an Umbrel VM.

Bump Oak Node to v0.3.5

---

samourai-server/docker-compose.yml
samourai-server/exports.sh
samourai-server/torrc.template
samourai-server/umbrel-app.yml

Fixes Whirpool GUI issue noted in Issue https://github.com/getumbrel/umbrel-apps/issues/397
Whirlpool GUI connection/authentication does not appear to do any DNS resolution. The following error is shown in the GUI:
and the following error is logged in the whirpool container:
`whirlpool_1   | com.samourai.wallet.api.backend.beans.HttpException: java.lang.IllegalArgumentException: Invalid URI host: null (authority: samourai-server_nginx_1:80)`
Reverting back to using hardcoded container IPs instead of name containers w/ Docker DNS fixes this issue.

Update Samourai Server (revert using Docker DNS)

---

rotki/docker-compose.yml
rotki/umbrel-app.yml

Hi there,
Minor update for rotki, the full changelog is available here: https://github.com/rotki/rotki/releases/tag/v1.27.1
I don't have access to my testing environment to check if it breaks a previous install. It shouldn't as there are no disclaimers on the release page.

Update rotki 1.27.1

---

woofbot-lnd/docker-compose.yml
woofbot-lnd/umbrel-app.yml

Just like: https://github.com/getumbrel/umbrel-apps/pull/441 but with LND integration.
Tested on my Raspberry Pi 4.
Logo:
I asked Lightning Labs for permissions to use the LND logo inside WoofBot logo, and they agreed with the condition that I specify that the app is not affiliated with LND (see app description).
Gallery screenshots can be taken from the original WoofBot app (although it's about time I update both of them, because the dashboard UI has changed).

App Submission: WoofBot LND

---

lndg/docker-compose.yml
lndg/umbrel-app.yml

Updates LNDg to v1.6.0
https://github.com/cryptosharks131/lndg/releases/tag/v1.6.0
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/81448828?tag=v1.6.0

Update LNDg to v1.6.0

---

lndg/docker-compose.yml
lndg/umbrel-app.yml

Updates LNDg to v1.6.1
https://github.com/cryptosharks131/lndg/releases/tag/v1.6.1
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/82690937?tag=v1.6.1
Fixes a breaking change introduced in a recent `pandas` update which causes new installs and updates to fail.

Update LNDg to v1.6.1

---

mempool/docker-compose.yml
mempool/umbrel-app.yml

This update brings the mempool app to parity with the production version. If LND is installed, the Lightning Explorer will be enabled.
The new app has been tested on an Ubuntu VM and Raspberry Pi running Umbrel 0.5.3.
Note: Additional testing by the Umbrel team is advised due to the community app store changes. This update has been tested using a modified Umbrel install and a temporary community app store repository, as discussed by another user in #358. See also https://github.com/getumbrel/umbrel/issues/1564#issuecomment-1373150661

Update the mempool app to v2.5.0

---

torq/docker-compose.yml
torq/umbrel-app.yml

Fixes high CPU usage and adds peers page
Tested on a real RaspberryPi
I realise there is already a PR  for this (#499) but we went for simpler release notes and a warning that db migrations might take a while on first start-up as they clean up a lot of old logs.

Update Torq v0.20.3

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

Hi there! Here to bump Litd to v0.9.2-alpha. 
See the release notes here: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.9.2-alpha
Thanks!

lightning-terminal: update to v0.9.2-alpha

---

lndg/docker-compose.yml
lndg/umbrel-app.yml

Updates LNDg to v1.6.4
https://github.com/cryptosharks131/lndg/releases/tag/v1.6.4
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/89375368?tag=v1.6.4
-Extends pandas fix in order to resolve issue with Auto-Fees no longer triggering (v1.6.2)
-Fixes manual rebalancer when not using a last hop pubkey (v1.6.3)
-Fixes an issue that causes the rebalancer to get stuck for some users (v1.6.3)
-Fixes a rebalancer issue causing channels to stop targeting when certain status codes were returned (v1.6.4)
-Manually submitted rebalance requests are now processed without needing to clear the current queue first (v1.6.4)

Update LNDg to v1.6.4

---

lnbits/docker-compose.yml
lnbits/umbrel-app.yml

This PR addresses two concerns:
1. Critical bug: https://twitter.com/lnbits/status/1654416778804580352?s=20
2. Newer versions of LNbits have extensions [removed by default](https://github.com/lnbits/lnbits/releases/tag/0.10) for better scalability and decreased attack vectors. Users now need to be at least Admin-level to manage extensions.
(1) Is fixed by bumping LNbits to version 0.10.5
(2) Needs to be fixed by ~~setting new and existing users as Admins~~ giving users access to an admin or super user url. Currently, if a user were to update to the newest LNbits version, any extensions they had previously isntalled would disappear and there would be no way to manage extensions without manually updating `LNBITS_ADMIN_USERS` in the `docker-compose.yml` to include a relevant user id, which …

Update LNbits to 0.10.5

---

tailscale/docker-compose.yml
tailscale/umbrel-app.yml

dockerhub had 1.40 and 1.40.0 
I used 1.40.0 becasue didn't see a 1.40 in [latest releases](https://github.com/tailscale/tailscale/releases)

Update Tailscale to v1.40.1

---

robosats/docker-compose.yml
robosats/umbrel-app.yml

Update RoboSats to latest v0.5.0-alpha. 
This update is a must as the RoboSats coordinators have deprecated the auth method used in v0.4.0-alpha.
Untested, but exactly replicated the steps to create the v0.4.0-alpha PR https://github.com/getumbrel/umbrel-apps/pull/447

Update RoboSats to v0.5.0-alpha

---

ghostfolio/docker-compose.yml
ghostfolio/umbrel-app.yml

Yahoo Finance changed something and this older version of ghostfolio is no longer working correctly. You are unable to add new assets on the portfolio screen.
My discussions with the Ghostfolio developer can confirm this here: https://ghostfolio.slack.com/archives/C02DMFGS0B1/p1684051691077229
Here is an update to the newest version of Ghostfolio recommended by the Ghostfolio developer

Update Ghostfolio to 1.269.0

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to v0.10.0-alpha, which now also packages the new Taproot Assets Daemon.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.10.0-alpha
Happy to address any potential feedback! Thanks!

lightning-terminal: update to v0.10.0-alpha

---

chatpad-ai/docker-compose.yml
chatpad-ai/umbrel-app.yml

https://chatpad.ai/
https://github.com/deiucanta/chatpad
Chatpad AI is an alternative user interface for OpenAI's chat models. Simply add your OpenAI API key and you're ready to go!
No tracking, no cookies, no bullshit. All your data is stored locally within your browser. You can export and import conversations to safeguard against data loss.

App Submission - Chatpad AI

---

homebridge/docker-compose.yml
homebridge/exports.sh
homebridge/umbrel-app.yml

https://homebridge.io/
https://github.com/homebridge/homebridge
Bringing HomeKit support where there is none. Homebridge allows you to integrate with smart home devices that do not natively support HomeKit. There are over 2000 Homebridge plugins supporting thousands of different smart accessories.

App Submission - Homebridge

---

mealie/docker-compose.yml
mealie/umbrel-app.yml

https://mealie.io/
https://github.com/hay-kot/mealie
Mealie is a self hosted recipe manager and meal planner. Easily add recipes by providing the url and Mealie will automatically import the relevant data or add a family recipe with the UI editor. Mealie also provides an API for interactions from 3rd party applications.

App Submission - Mealie

---

oak-node/docker-compose.yml
oak-node/umbrel-app.yml

Tested on amd64 (VM) and arm64 (raspi).

Bump Oak Node to v0.3.6

---

trilium-notes/docker-compose.yml
trilium-notes/umbrel-app.yml

Updates trilium notes from version 55.1 to version 59.4 (currently latest stable)

feat(trilium-notes): bump version to 59.4

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to v0.10.1-alpha.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.10.1-alpha
Happy to address any potential feedback! Thanks!

lightning-terminal: update to v0.10.1-alpha

---

home-assistant/docker-compose.yml
home-assistant/umbrel-app.yml

Bumping Homeassistant from 2023.2 to 2023.6. 
Full Changelog of 2023.6 is available here: https://www.home-assistant.io/changelogs/core-2023.6

Update Homeassistant to 2023.6

---

torq/docker-compose.yml
torq/umbrel-app.yml

* Open telemetry instrumentation
* Jaeger tracing
* Prometheus export
* Peers' page now supports multi-node setups
* Custom mempool.space URL
* Inspect a closed/closing channel
* Pagination added to all channel table pages and forwarding pages
* Fix Amboss ping service
* Increase initial channel data import throughput
* LND maximum message size increase to 150M
* CLN fixes (thanks to borsche-hfsp.com)
* And more...

Update Torq to v0.23.1

---

bazarr/docker-compose.yml
bazarr/umbrel-app.yml

Fixes an issue where bazaar tries to read the media file and returns an error:
FileNotFoundError: [Errno 2] No such file or directory: \'/downloads/movies/[movie_file_name]
thus never downloading nor finding any subtitles for Radaar movies or Sonar shows

Fix no access to download directories in bazaar

---

immich/docker-compose.yml
immich/umbrel-app.yml

Getting Immich update PR going
added tag for 
immich-server
Looks like one for microservices is the same
immich-machine-learning
immich-web
&
immich-proxy
didn't change the new typesense
redis
or 
postgres

Update Immich to 1.65.0

---

node-red-standalone/docker-compose.yml
node-red-standalone/umbrel-app.yml

Upgrade Node-Red-Standalone to 3.0.4.
Tested on Custom Umbrel install on Linux

Upgrade Node-Red-standalone to latest version (3.0.4)

---

home-assistant/docker-compose.yml
home-assistant/umbrel-app.yml

This PR enables Home Assistant to have access to USB devices connected to the host machine, while not requiring the USB to be connected prior to starting the Docker container.

Home Assistant - Enable USB device access

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to v0.10.2-alpha.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.10.2-alpha
Happy to address any potential feedback! Thanks!

lightning-terminal: update to v0.10.2-alpha

---

node-red-standalone/docker-compose.yml
node-red-standalone/umbrel-app.yml

NodeJS 14 is deprecated. This version uses NodeJS 18 instead.
Tested on Raspberry Pi.

Update Node-Red-Standalone to 3.0.2-18

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to `v0.10.4-alpha`.
There was no `v0.10.3-alpha` release, due to a build issue we had to skip that version and go directly to `v0.10.4-alpha`.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.10.4-alpha
Happy to address any potential feedback! Thanks!

lightning-terminal: update to v0.10.4-alpha

---

torq/docker-compose.yml
torq/umbrel-app.yml

Torq v1.0
New:
- Connections status: Provides insight into the internals of Torq. (People often ask if there is a way to see if it's still importing data; well, now you can!)
- LND: Select an outbound channel for payment
- Keep historic information about tagging/untagging
- Manually request a channel from an LSP that is following the LSP channel request specification (i.e. Deezy)
- HTLC information in Open Channels
- Quick filter with fuzzy search on listing screens
- Mempool API integration for fee recommendations
New HTLC Firewall workflows:
- You can create one or more workflows to firewall/drop HTLCs. (i.e. block any HTLC coming from peer1 going to peer2 below a certain amount. Or block any HTLC if the amount of pending HTLC for a peer is above a certain amount)
- New HTLC Firewall …

Update Torq to v1.0.10

---

btcpay-server/docker-compose.yml
btcpay-server/umbrel-app.yml

PR for 1.11.0,
updated postgres, BTCPay, and nbxplorer tags
updating release notes description
Don't see any other big breaking changes for new update
If there's anything else I can do, do better, or can confirm standardization of release notes let me know!

Update BTCPay Server to 1.11.1

---

torq/docker-compose.yml
torq/umbrel-app.yml

This update fixes a bug when creating tags. In the last release, new tags would overwrite an existing one.

Update Torq to v1.0.11

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

Hi there! Here with the latest release: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.10.5-alpha

lightning-terminal: update to v0.10.5-alpha

---

immich/docker-compose.yml
immich/umbrel-app.yml

I've updated the image to v1.72.2 for
`immich-server` (the same immich-server tag is used under `server` and `microservices`)
`immich-machine-learning`
`immich-web`
`immich-proxy`
I did not change `typesense:0.24.1`, `redis:6.2-alpine` or `postgres:14-alpine`

Update Immich to v1.72.2

---

tailscale/docker-compose.yml
tailscale/umbrel-app.yml
vaultwarden/docker-compose.yml
vaultwarden/umbrel-app.yml

Due to a regression introduced in the interaction between Tailscale and Linux ufw, the Linux release for `v1.48.0` has been withdrawn and is pending a fix.
To ensure stability and avoid potential issues, opting to stick with **v1.46.1** until the issue is resolved in a future release.

Update Tailscale to v1.46.1

---

vaultwarden/docker-compose.yml
vaultwarden/umbrel-app.yml

Update Vaultwarden from v1.25.0 to v1.29.1.
Full release notes can be found at: https://github.com/dani-garcia/vaultwarden/releases

Update Vaultwarden to v1.29.1

---

whoogle-search/docker-compose.yml
whoogle-search/umbrel-app.yml

Fixes recent EU cookie consent bug: https://github.com/benbusby/whoogle-search/pull/1054
Closes https://github.com/getumbrel/umbrel-apps/issues/738

Update Whoogle Search to v0.8.3

---

tailscale/docker-compose.yml
tailscale/umbrel-app.yml

This update fixes the `nftables` interaction between `tailscale` and `ufw` which resulted in blocking subnet routed traffic. Also, it now determine correct CPU architecture on Synology platforms during `tailscale update`

Update Tailscale to v1.48.1

---

ride-the-lightning/docker-compose.yml
ride-the-lightning/umbrel-app.yml

I have updated the `RTL` image from version `v0.13.2-beta-hotfix-1` to `v0.14.0-beta`. As for `boltz-lnd`, there have been no new releases.

Update Ride The Lightning to v0.14.0-beta

---

immich/docker-compose.yml
immich/umbrel-app.yml

I've updated image to v1.75.2 for
- `immich-server` (the same `immich-server` tag is used under `server` and `microservices`)
- `immich-machine-learning`
- `immich-web`
- `immich-proxy`

Update Immich to v1.75.2

---

jellyfin/docker-compose.yml
jellyfin/umbrel-app.yml

Update Jellyfin image from `v10.8.9` to `v10.8.10`, which fixes a critical bug along with other bug fixes and improvements.
⚠️ CRITICAL SECURITY ADVISORY: [GHSA-9p5f-5x8v-x65m](https://github.com/jellyfin/jellyfin/security/advisories/GHSA-9p5f-5x8v-x65m) and [GHSA-89hp-h43h-r5pq](https://github.com/jellyfin/jellyfin-web/security/advisories/GHSA-89hp-h43h-r5pq) can be combined to allow remote code execution for any authenticated Jellyfin user including non-admin users. While the particular execution mechanism of the former dates to the 10.8.0 release, the latter was present for all Jellyfin releases before this point. It is thus absolutely critical for all Jellyfin administrators, regardless of version, to upgrade to this version if they allow any untrusted users and/or expose their …

Update Jellyfin to v10.8.10

---

ride-the-lightning/docker-compose.yml
ride-the-lightning/umbrel-app.yml

The latest version of the Lightning Node app does not include an lnd.conf file by default. Instead, it has a file named umbrel-lnd.conf located at:
`/lnd/umbrel-lnd.conf`
Updating RTL to reflect this

Update docker-compose.yml to reflect umbrel-lnd.conf update

---

n8n/docker-compose.yml
n8n/umbrel-app.yml

Update N8N version to 1.4.0.
This is the latest stable version.
There are many new features from version 1 and this update is important.
[N8N 1.4.0 change log](https://github.com/n8n-io/n8n/releases/tag/n8n%401.4.0)

feat: bump n8n to 1.4.0

---

core-lightning/docker-compose.yml
core-lightning/umbrel-app.yml

This PR updates c-lightning-REST to [v0.10.5](https://github.com/Ride-The-Lightning/c-lightning-REST/releases/tag/v0.10.5) and lightningd to [v23.08](https://github.com/ElementsProject/lightning/releases/tag/v23.08). 
No change has been made to the frontend cln-application. Relevant context from @ShahanaFarooqui here: https://github.com/getumbrel/umbrel-apps/pull/748#issuecomment-1696747582
This still needs to be tested.

Update Core Lightning to v23.08

---

core-lightning-rtl/docker-compose.yml
core-lightning-rtl/umbrel-app.yml

I have updated the `Core Lightning RTL` image from version `v0.13.2-beta` to `v0.14.0-beta`.
This release covers breaking changes from CLN 23.05, a few minor UX enhancements and bug fixes
⚠️ Core Lightning users should note that this update depends on cl-rest v0.10.3 and Core Lightning v23.05. If you are running any version older than 23.05, you should not upgrade to this UI. The changes are not backwards compatible with older versions of Core Lightning
Full releases can be found here: https://github.com/Ride-The-Lightning/RTL/releases

Update Core Lightning RTL to v0.14.0 beta

---

portainer/default-password
portainer/docker-compose.yml
portainer/entrypoint.sh
portainer/umbrel-app.yml

Portainer on Umbrel has been configured for power users aiming to run custom applications on umbrelOS. Portainer is not interfacing directly with the primary host's Docker instance active on Umbrel. Instead, it communicates with a Docker-in-Docker (DinD) service.
Follow these best practices to avoid issues:
1. Data persistence: Make sure to only used named Docker volumes for your stacks and containers. Data in bind-mounted volumes will be lost when the Portainer app is restarted or updated.
2. Port management: Watch out for potential port conflicts between your custom containers and umbrelOS' service containers, apps you have installed from the Umbrel App Store or Community App Stores, and any apps you go to install in the future.
3. Container restart policy: Set your containers to …

Add Portainer

---

librespeed/hooks/post-update
librespeed/umbrel-app.yml

Updates Librespeed's web ui port from 3009 to 3011 to avoid a port conflict with [Samourai Server's DOJO port](https://github.com/getumbrel/umbrel-apps/blob/0f7a8dd951e6dc165205b66c476bdee3a3ef9389/samourai-server/docker-compose.yml#L141).
Added a post-update hook to source updated port number correctly on update.

Update Librespeed Web UI port

---

jam/docker-compose.yml
jam/umbrel-app.yml

- Jam: [v0.1.6](https://github.com/joinmarket-webui/jam/releases/tag/v0.1.6)
- joinmarket-clientserver: [v0.9.10](https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.9.10)
All notable changes of the UI can be seen in the [Jam v0.1.6 changelog](https://github.com/joinmarket-webui/jam/blob/v0.1.6/CHANGELOG.md)

Update Jam to v0.1.6

---

immich/docker-compose.yml
immich/umbrel-app.yml

Updated image to v1.79.1 for
`immich-server` (the same `immich-server` tag is used under `server` and `microservices`)
`immich-machine-learning`
`immich-web`
`immich-proxy`

Update Immich to v1.79.1

---

immich/docker-compose.yml
immich/umbrel-app.yml

I have updated image to v1.81.0 for
`immich-server` (the same `immich-server` tag is used under `server` and `microservices`)
`immich-machine-learning`
`immich-web`
`immich-proxy`

Update Immich to v1.81.0

---

home-assistant/docker-compose.yml
home-assistant/umbrel-app.yml

Changes: https://www.home-assistant.io/blog/2023/09/06/release-20239/
Tested on:
- `x86_64` -> Digital Ocean droplet by updating from old to new version.
- `arm64` -> Fresh install
New onboarding screen looks clean 😮‍💨

update home-assistant to 2023.9.3

---

photoprism/docker-compose.yml
photoprism/umbrel-app.yml

The [September release](https://github.com/photoprism/photoprism/releases/tag/230923-e59851350) includes a [redesigned Places view](https://user-images.githubusercontent.com/301686/269433540-cd48e79f-b2a8-4fb5-bc54-52467b15b743.jpg), with the search box moved to the top and a preview for selected clusters at the bottom. Also added support for https://github.com/photoprism/photoprism/issues/439/https://github.com/photoprism/photoprism/issues/1739, so you can view them like Apple Live Photos after [re-indexing your library](https://docs.photoprism.app/user-guide/library/originals/). Beyond those highlights, you'll get many usability improvements, new search filters, and fixes for recently discovered issues.

Update PhotoPrism to 230923

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to `v0.11.0-alpha`.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.11.0-alpha
There's one change that I think might be important for Umbrel that I've noted in the release notes:
"One important change to note for users running LiT through docker, is that due to the new status server feature, the startup process of LiT won’t error and end if a sub-server or sub-system fails to start. So any platforms that rely on docker to automatically restart the LiT container if the startup process ends due to the sub-servers or sub-system not having started yet, will now not restart the container as the start process won't exit."
I don't know if this affects your startup process of the container, so just thought I'd make you aware …

lightning-terminal: update to `v0.11.0-alpha`

---

helipad/docker-compose.yml
helipad/umbrel-app.yml

Updates the Helipad app to the latest Docker version and includes release notes with changes since the last version.

Update Helipad to v0.1.10.5

---

jackett/docker-compose.yml
jackett/umbrel-app.yml

This PR takes care of the issue https://github.com/getumbrel/umbrel-apps/issues/487
But additional testing is needed. I think we may need to whitelist something in order to get it completely. Anyways I have no idea need some reviews
...
https://raw.githubusercontent.com/IMPranshu/svg-logo/main/jackett.svg
...
...

App Submission: Jackett

---

autobrr/docker-compose.yml
autobrr/umbrel-app.yml

[autobrr](https://autobrr.com/introduction) is the modern download automation tool for torrents and usenet
https://raw.githubusercontent.com/autobrr/autobrr/master/web/src/logo.svg

App Submission: autobrr

---

immich/docker-compose.yml
immich/umbrel-app.yml

Tested on:
Tested both fresh install & version update and verified the functionality by uploading images, deleting images etc.
Very cool update, Adds Trash feature & Websocket support so we don't have to refresh to see updates.

update Immich to v1.82.0

---

portainer/docker-compose.yml
portainer/umbrel-app.yml

Tested on:
Tested both fresh install & version update and verified the functionality by running containers and pulling images.

update Portainer to v2.19.1

---

core-lightning/docker-compose.yml
core-lightning/umbrel-app.yml

Fixes issue when running Bitcoin in testnet, Core Lightning will also now automatically open in testnet successfully, thank you!
Worked and opened app at 97% Bitcoin testnet synced and opening at 100% showing: 
Not sure if denoting that it is indeed in testnet?
something app proxy can handle?

Fix to use RPC port

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to `v0.12.0-alpha` which adds support for Taproot Assets on the Bitcoin mainnet!
See the release notes here: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.12.0-alpha
There's one extra important release note for Umbrel users that I'll include until we have added some additional backup procedure to mitigate the current backup procedure for Umbrel Taproot Assets users:
**DO NOT UNDER ANY CIRCUMSTANCE** uninstall (or re-install) the "Lightning Terminal" app without first making a manual backup of all local tapd data, if you are using Taproot Assets as part of the "Lightning Terminal" app with Umbrel. Uninstalling Umbrel apps deletes application data. This Taproot Assets application data encumbers Taproot Assets AND bitcoin funds. Receiving and …

lightning-terminal: update to `v0.12.0-alpha`

---

circuitbreaker/docker-compose.yml
circuitbreaker/umbrel-app.yml

This PR upgrades circuitbreaker to v0.5.0, which contains an upgrade to start storing more granular HTLC forwarding data. 
The final section of the release notes has a call to action to help out with ongoing research for protocol work - happy to remove it if it's not appropriate!

Circuitbreaker: Upgrade to v0.5.0

---

torq/docker-compose.yml
torq/umbrel-app.yml

New Torq version with a lot of bug fixes.
List of changes:
-  You can now duplicate views
-  Add payment request to payments page
-  Closed channels sometimes reappeared as active when delayed gossip was processed
-  Pagination indicated to many pages when filtering
-  You can now choose refresh interval for each list view
-  Fix turnover layout and calculation
-  Channel filter "Active" is now true when both sides of the channel are active (used to be local side only)
-  Improvements on channel inspect page:
-  Show channel open and close dates on charts
-  Added basic channel info
-  Indicators if data is loading
Note: This release contains database migrations and cannot be rolled back to a previous version.

Update Torq to v1.4.1

---

homebox/docker-compose.yml
homebox/umbrel-app.yml

Moved over to version-tagged image as per comment on last update
` TODO: update with version-tagged image when available (https://github.com/hay-kot/homebox/pull/372)`
Tested on:

Update homebox to v0.10.1

---

whoogle-search/docker-compose.yml
whoogle-search/umbrel-app.yml

Minor update. https://github.com/benbusby/whoogle-search/releases/tag/v0.8.4
Tested on:

Update whoogle-search to 0.8.4

---

uptime-kuma/docker-compose.yml
uptime-kuma/umbrel-app.yml

Release notes: https://github.com/louislam/uptime-kuma/releases
Only weird issue I noticed is that it takes a weirdly long time to install on the Pi. Wasn't able to resolve it, if you dont mind, maybe check if this happens on your Pi too.

Update uptime-kuma to 1.23.3

---

tailscale/docker-compose.yml
tailscale/umbrel-app.yml

Release notes here https://github.com/tailscale/tailscale/releases
Update works pretty seamlessly which is nice. I updated on my promox umbrel instance and it didn't even drop out.
Did a completely fresh install on Pi instance, and added to tailnet- no issues!
Changed the formatting for release notes so newlines worked.

Update tailscale to v1.52.0

---

vaultwarden/docker-compose.yml
vaultwarden/umbrel-app.yml

Was hoping to test that data persisted across updates, but TOR is really slow today. Update works fine tho.
https://github.com/dani-garcia/vaultwarden/releases/tag/1.30.0

Update vaultwarden to 1.30.0

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to `v0.12.1-alpha`.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.12.1-alpha
I've also updated the description of LiT as discussed in:
https://github.com/getumbrel/umbrel-apps/pull/811#issuecomment-1780111553
In short I've the warning for LiT users using tapd through Umbrel, that we also include in the release notes.
If the format of this warning is incorrect, based on how it should be formatted in the description field, feel very much free to change it!
Happy to address any additional feedback!

lightning-terminal: update to v0.12.1-alpha

---

gitea/docker-compose.yml
gitea/umbrel-app.yml

https://github.com/go-gitea/gitea/releases/tag/v1.21.0
```
BREAKING
- Restrict certificate type for builtin SSH server (https://github.com/go-gitea/gitea/pull/26789)
- Refactor to use urfave/cli/v2 (https://github.com/go-gitea/gitea/pull/25959)
- Move public asset files to the proper directory (https://github.com/go-gitea/gitea/pull/25907)
- Remove commit status running and warning to align GitHub (https://github.com/go-gitea/gitea/pull/25839) (partially reverted: Restore warning commit status (https://github.com/go-gitea/gitea/pull/27504) (https://github.com/go-gitea/gitea/pull/27529))
- Remove "CHARSET" config option for MySQL, always use "utf8mb4" (https://github.com/go-gitea/gitea/pull/25413)
- Set SSH_AUTHORIZED_KEYS_BACKUP to false (https://github.com/go-gitea/gitea/pull/25412)
``` …

Update gitea to 1.21.0

---

immich/docker-compose.yml
immich/umbrel-app.yml

For compatibility with mobile clients, Immich must be updated. See https://github.com/getumbrel/umbrel-apps/issues/865
1.88.0 of immich includes a breaking change, including breaking login functionality for mobile clients.
See documentation on update path here: https://github.com/immich-app/immich/discussions/5086
This PR performs the update as documented.

Update Immich to 1.88.2

---

esphome/docker-compose.yml
esphome/umbrel-app.yml

Release notes: https://github.com/esphome/esphome/releases

Update esphome to 2023.11.6

---

n8n/docker-compose.yml
n8n/umbrel-app.yml

Update N8N version to 1.4.0.
This is the latest stable version.
There are many new features from version 1 and this update is important.
[N8N 1.18.1 change log](https://github.com/n8n-io/n8n/releases/tag/n8n%401.18.1)

feat: bump n8n to 1.18.1

---

home-assistant/docker-compose.yml
home-assistant/umbrel-app.yml

Release notes: https://github.com/home-assistant/core/releases/tag/2023.11.3

Update home-assistant to 2023.11.3

---

homebridge/docker-compose.yml
homebridge/umbrel-app.yml

Release notes: https://github.com/homebridge/homebridge/releases/tag/v1.7.0
Moved from oznu/homebridge to homebridge/homebridge image repo

Update homebridge to 2023-01-08

---

jackett/docker-compose.yml
jackett/umbrel-app.yml

Release notes: https://github.com/Jackett/Jackett/releases

Update jackett to 0.21.1289

---

lidarr/docker-compose.yml
lidarr/umbrel-app.yml

Release notes: https://github.com/Lidarr/Lidarr/releases
Data persisted.

Update lidarr to 1.4.5

---

heimdall/docker-compose.yml
heimdall/umbrel-app.yml

New PR as I accidently had two updates rolled into the last Heimdall PR.
Release notes: https://github.com/linuxserver/Heimdall/releases

Update heimdall to 2.5.8

---

photoprism/docker-compose.yml
photoprism/umbrel-app.yml

Release notes: https://github.com/photoprism/photoprism/releases/
Data persisted across updates. Test with a folder of images.

Update photoprism to 231128

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to `v0.12.2-alpha`.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.12.2-alpha
Thanks a lot for adding the umbrel-specific instructions for taproot assets backup in #859, and for updating the warning message in the umbrel-app.yml file @nmfretz! It looks great, thanks!
Happy to address any feedback regarding this new PR if needed :)!

lightning-terminal: update to `v0.12.2-alpha`

---

sabnzbd/docker-compose.yml
sabnzbd/umbrel-app.yml

This PR binds the main umbrel downloads folder to `/downloads` within the sabnzbd container. This increases the friction on initial app set-up, but decreases the friction when pairing SABnzbd with other apps like radarr and sonarr. No data is lost with this change in configuration.

Update SABnzbd to 4.1.0-hotfix1

---

audiobookshelf/docker-compose.yml
audiobookshelf/umbrel-app.yml

Release notes: https://github.com/advplyr/audiobookshelf/releases
I'm having an issue where audiobookshelf doesnt work at all on my debian instance, neither the old or new one. @nmfretz can you test my update too pls?

Update to audiobookshelf 2.6.0

---

bazarr/docker-compose.yml
bazarr/umbrel-app.yml

Release notes: https://github.com/morpheus65535/bazarr/releases
Only test I did for data persistence was adding an indexer- I noticed that it didn't stick across the update, but I may not have set it up properly. Another than that all worked well.

Update bazarr to 1.4.0

---

jellyfin/docker-compose.yml
jellyfin/umbrel-app.yml

Release notes: https://github.com/jellyfin/jellyfin/releases

Update Jellyfin to 10.8.13

---

circuitbreaker/docker-compose.yml
circuitbreaker/umbrel-app.yml

Bumping circuitbreaker release to include a bugfix. Left release notes from 0.5.0 so that the new feature is still described, happy to update if not!

circuitbreaker: bump release to v0.5.1

---

back-that-mac-up/docker-compose.yml
back-that-mac-up/umbrel-app.yml

Introducing Back That Mac Up — an official app by Umbrel.
Effortlessly back up your Mac to your Umbrel using Time Machine. Simply follow the instructions in the app to set up your Umbrel as a Time Machine backup destination and you're good to go!
Make sure to follow the instructions in the app to appropriately allocate the backup size. Time Machine backs up your Mac by keeping hourly backups for the past 24 hours, daily backups for the past month and weekly backups for all previous months.
Over time, it will likely use all the allotted space on your Umbrel, automatically deleting the oldest backups to free up space as needed.
For seamless backups even when your Mac isn't connected to the same network as your Umbrel, simply install Tailscale on your Umbrel and your Mac, and use …

App Submission: Back That Mac Up

---

specter-desktop/docker-compose.yml
specter-desktop/umbrel-app.yml

Release notes: https://github.com/cryptoadvance/specter-desktop/releases?page=1

Update specter-desktop to 2.0.2

---

node-red/docker-compose.yml
node-red/umbrel-app.yml

Updating the bitcoin specific version of node-red. This hadn't been updated in a while, so I thought it may need a special image/config, but looking at this PR https://github.com/getumbrel/umbrel-apps/issues/36 the only reason i can see they were seperated is due to managing dependencies, so this reflects my other node-red update.
Release notes: https://github.com/node-red/node-red/releases/tag/3.1.0
Node 20 version

Update node-red to 3.1.1

---

lndg/docker-compose.yml
lndg/umbrel-app.yml

Updates LNDg to v1.8.0
https://github.com/cryptosharks131/lndg/releases/tag/v1.8.0
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/162090911?tag=v1.8.0

Update LNDg to v1.8.0

---

octoprint/docker-compose.yml
octoprint/umbrel-app.yml

Release notes: https://github.com/OctoPrint/OctoPrint/releases/tag/1.9.3
This is a requested update. Part of the request is that they've been having trouble connecting via USB- `privileged: true` is specified, and `- /dev:/dev` is correct, maybe this needs to be booted in host mode also?

Update octoprint to 1.9.3

---

thunderhub/docker-compose.yml
thunderhub/umbrel-app.yml

This updates ThunderHub from v0.13.29 to v0.13.30. Contains an important fix for Boltz Swaps.

Update Thunderhub to v0.13.30

---

electrs/docker-compose.yml
electrs/umbrel-app.yml

Release notes: https://github.com/romanz/electrs/blob/master/RELEASE-NOTES.md#0102-dec-31-2023

Update electrs to v0.10.2

---

public-pool/data/proxy/nginx.conf
public-pool/docker-compose.yml
public-pool/umbrel-app.yml

https://web.public-pool.io/assets/layout/images/logo.svg
1. 
2. 
3.

App Submission: Public Pool 

---

public-pool/docker-compose.yml
public-pool/umbrel-app.yml

This hotfix update disables extra caching, so less powerful devices don't run out of memory.
See changes here: https://github.com/sethforprivacy/public-pool/pull/1
Fresh installs work great, however when I update it appears the DB changes cause an issue- see below.

Hotfix for public-pool

---

public-pool/docker-compose.yml
public-pool/umbrel-app.yml

Hot-fix patch fixes public-pool persisting on old blocks.

Hotfix for Public-Pool (ZMQ)

---

invoice-ninja/config/nginx.conf
invoice-ninja/docker-compose.yml
invoice-ninja/exports.sh
invoice-ninja/hooks/pre-start
invoice-ninja/umbrel-app.yml

Release notes: https://github.com/invoiceninja/invoiceninja/releases
**I'm having two slight issues**
- Invoice ninja requires app_key now: I've hardcoded it for the moment, and not sure on the best way to do with it so it persists for users in future updates. See my idea for exports.sh (doesn't work)
- After installing you will get nginx errors for a min or so, not a big issue, but a lil confusing.

Update invoice ninja to 5.7.62

---

robosats/docker-compose.yml
robosats/umbrel-app.yml

Minor release update for Robosats
If anyone tests this on a Pi please inspect the web-app and let me know how long it takes for APIs to fetch for you. Mine seem to either take a long-time or fail, which was also occurring with 0.5.3, so I might just let the Robosats team know if it occurs for anyone else too.

Update robosats to 0.54

---

node-red-standalone/docker-compose.yml
node-red-standalone/umbrel-app.yml

This PR bumps node-RED to v3.1.3 and also switches the node-RED container to host network mode by popular request, in order to facilitate automatic device discovery.

Update Node-RED to v3.1.3

---

torq/docker-compose.yml
torq/umbrel-app.yml

Release notes:
- CLN v23.11+ is required (pagination)
- Integration with Kraken
- New workflow triggers: Invoice, Forward, Payment, Transaction (on-chain)
- New workflow filters: Mempool, Exchange (Kraken) balance
- New workflow action: Payment Attempt (experimental: tries to find a route to pay an exchange invoice)
- New variables in workflow actions: API client, notification
- Replace intercom with chatwoot
- Small changes to rebalancer + new metrics and logs
- Timelock Delta in seconds on list screens
- Update of packages
Notes:
- This release contains a large set of database updates. So the migration might take some time depending on the hardware and stored data. Please create a backup before updating, there is no automatic rollback process other then a database restore from before …

Update Torq to v1.5.1

---

vaultwarden/docker-compose.yml
vaultwarden/umbrel-app.yml

Release notes: https://github.com/dani-garcia/vaultwarden/releases

Update to vaultwarden 1.30.3

---

esphome/docker-compose.yml
esphome/umbrel-app.yml

- Updates ESPHome to latest stable release: https://github.com/esphome/esphome/releases/tag/2023.12.9
- Switches ESPHome container to host networking mode by popular request.
In general, the plan for apps that require host networking to function properly is to allow `network_mode: host` for now. Later on we will remove host access and instead proxy local mDNS traffic through to apps to allow safer device detection.

Update ESPHome to v2023.12.9 and switch to host networking

---

helipad/docker-compose.yml
helipad/umbrel-app.yml

Updates the Helipad app from `v0.1.10.5` to `v0.1.11`.

Update Helipad to v0.1.11

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to `v0.12.3-alpha`.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.12.3-alpha
Happy to address any feedback regarding this new PR if needed :)!

lightning-terminal: update to `v0.12.3-alpha`

---

freshrss/docker-compose.yml
freshrss/umbrel-app.yml

Bumps FreshRSS to version 1.23.1 and also whitelists the /api route in the proxy so that other RSS feed apps like NetNewsWire can connect.
Tested on arm64 and x86(amd64). Tested adding FreshRSS to NetNewsWire.

Update FreshRSS to v1.23.1

---

lnmarkets/docker-compose.yml
lnmarkets/umbrel-app.yml

New version of LNM with a small fix, the image sha is pointing to the arm64 version.

Update ln markers version

---

firefly-iii-importer/docker-compose.yml
firefly-iii-importer/hooks/pre-start
firefly-iii-importer/umbrel-app.yml

Repo: https://github.com/firefly-iii/data-importer
Website: https://docs.firefly-iii.org/explanation/data-importer/about/introduction/
I have added this as a separate app instead of including the data importer as a service within the Firefly III compose file. This way there is an obvious way for users to get to the importer app (by installing it and having the app visible on their dashboard). If the importer was a service within the Firefly III compose file, then it would be invisibly running on port 30010 and we would need to provide instructions in the app description on how to access it (e.g., navigate to http://umbrel.local/30010) which isn't great UX.
Tested in production on arm64 and x86.

App Submission: Firefly III Data Importer

---

pi-hole/docker-compose.yml
pi-hole/umbrel-app.yml

Release notes: https://pi-hole.net/blog/2024/01/06/pi-hole-ftl-v5-24-and-core-v5-17-3-released/

Update pihole to 2024.02.0

---

btcpay-server/docker-compose.yml
btcpay-server/umbrel-app.yml

https://github.com/btcpayserver/btcpayserver/releases
@nmfretz do you mind checking btcpay on a linux instance for me please. should be fine, but im having issues with my linux instance at the moment so i couldn't check.

Update btcpay to 1.12.5

---

ordinals/docker-compose.yml
ordinals/hooks/pre-start
ordinals/umbrel-app.yml

Updates Ord from v0.5.1 to v0.15.0.
This update requires a full re-indexing of the ord database due to newer version of ord altering the database schema.
Re-indexing on update from v0.5.1 will happen automatically for users on app update.
Tested on arm64 and x86.
Tested re-index logic.

Update Ordinals to v0.15.0

---

back-that-mac-up/docker-compose.yml
back-that-mac-up/umbrel-app.yml

This is a patch release to clarify the instructions in the app and improve the accuracy of the current usage indicator.
Tested on arm64 and x86.

Update Back That Mac Up to v1.0.1

---

jam/docker-compose.yml
jam/umbrel-app.yml

- Jam: [v0.2.0](https://github.com/joinmarket-webui/jam/releases/tag/v0.2.0)
- joinmarket-clientserver: [v0.9.11](https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.9.11)
All notable changes of the UI can be seen in the [Jam v0.2.0 changelog](https://github.com/joinmarket-webui/jam/blob/v0.2.0/CHANGELOG.md)
Would you please be so kind as to take a look at https://github.com/getumbrel/umbrel/issues/1736?
It is very annoying to some users and it would be great to know, if you consider adapting it :pray:

Update Jam to v0.2.0

---

home-assistant/docker-compose.yml
home-assistant/umbrel-app.yml

Release notes: https://www.home-assistant.io/blog/2024/03/06/release-20243/

Update home-assistant to 2024.3.0

---

pi-hole/hooks/pre-install

The old code was checking two systemd units - one called "service" and the other the actual one it was supposed to be checking.  If you want to restrict the check to units of type "service" you need to append ".service" to the unit name, _not_ add it as a separate argument.

pi-hole: fixed the systemd service check in the pre-install hook

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to `v0.12.4-alpha`.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.12.4-alpha

lightning-terminal: update to `v0.12.4-alpha`

---

robosats/docker-compose.yml
robosats/umbrel-app.yml

Update RoboSats to latest v0.6.0-alpha
Untested. Exactly replicated the steps to update to v0.5.0-alpha https://github.com/getumbrel/umbrel-apps/pull/528

Update RoboSats to v0.6.0-alpha

---

ride-the-lightning/docker-compose.yml

This pr replaces `boltz-lnd` with its successor [boltz-client](https://github.com/BoltzExchange/boltz-client).
Its completely backwards compatible and the migration is well tested.

upgrade to boltz-client in rtl

---

ordinals/docker-compose.yml
ordinals/hooks/pre-start
ordinals/umbrel-app.yml

- update ord from 0.15.0 to 0.17.1
- built 0.17.1 image using the [official Dockerfile in the ord repo](https://github.com/ordinals/ord/blob/cb4de8dedf8485d265e6cd0edab7c2c894685190/Dockerfile). Had previously been using a custom Dockerfile because the ord repo did not include one in the past. The official Dockerfile does not include an entrypoint with the ord command, so I have added it to the command in the compose file.
- moved appropriate cli flags to environment variables. Users will now see accurate config values when running `ord settings` and can now run ord commands without passing data-dir/config/rpc options. For example `ord wallet create`.
- added --index-runes
- modified the pre-start hook to nuke index.db for users updating so that reindexing for runes occurs automatically.

Update Ordinals to  v0.17.1

---

frigate/data/config/config.yml

This is a fix for Frigate that was impacting new installs. The config.yml was commited blank in the last update PR accidentally when attempting to handle a breaking change: https://github.com/getumbrel/umbrel-apps/pull/1014
New installs that were impacted can uninstall and re-install the app.

Update Frigate with config.yml

---

ordinals/docker-compose.yml
ordinals/hooks/pre-start
ordinals/umbrel-app.yml

- update ord from 0.17.1 to 0.18.1
- modified the pre-start hook to nuke index.db for all bitcoin networks, so that reindexing for runes occurs automatically

Update Ordinals to 0.18.1

---

ordinals/docker-compose.yml
ordinals/hooks/pre-start
ordinals/umbrel-app.yml

This PR updates ord to 0.18.2, which requires the following migration:
https://github.com/ordinals/ord/releases/tag/0.18.2
> Wallet databases are now stored in the /wallets subdirectory of the data dir. To use old wallet databases with 0.18.2, move <WALLET_NAME>.redb files into the /wallets subdirectory of the data dir. Currently, the only information stored in wallet databases are pending etchings.
I have updated the pre-start script to migrate all wallet database files for all bitcoin networks (mainnet, testnet, signet, regtest). I have assumed that all .redb files in the ord data dir that **are not** index.db are instead wallet database files.
I have also removed the `ORD_FIRST_INSCRIPTION_HEIGHT` env var. Ord now handles this automatically for each Bitcoin network, so the app will …

Update Ordinals to v0.18.2

---

jackett/docker-compose.yml
jackett/umbrel-app.yml

Jacket, in its Torznab feed sets the torrent url as http://<jackett>/dl/..., which is protected by umbrel's app proxy. This PR removes protection for dl/*
(Based on app-proxy's source code, the whitelist can be separated with /[, ]*/)

[FIX] a critical issue with Jackett

---

btcpay-server/docker-compose.yml
btcpay-server/umbrel-app.yml

Fix: #1049
Updated containers:
- nicolasdoriev/nbxplorer:2.5.0 -> 2.5.2
- btcpayserver/btcpayserver:1.12.5 -> 1.13.1
- btcpaayserver:13.10 -> 13.13
I have partially tested the app on my Debian Umbrel, but because I don't have a bitcoin node (the synchronization takes Ages!) I can't fully verify that the app is working. It gets to starting the app, but because APP_LIGHTNING_NODE_DATA_DIR is null, it fails. The app should be working for people who have the lightning node. Test it on your machine. Just in case.

[UPDATE] Btcpay server

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to `v0.12.5-alpha`.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.12.5-alpha

lightning-terminal: update to `v0.12.5-alpha`

---

bitcoin/docker-compose.yml
bitcoin/exports.sh
bitcoin/umbrel-app.yml

Bitcoin Core: Upgrades Bitcoin Core to version 27.0. Full release notes for Bitcoin Core 27.0 can be found at https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-27.0.md.
New Advanced Settings Options: Adds 3 new options to the Advanced Settings menu:
- datacarrier: Choose whether or not to relay transactions with OP_RETURN outputs.
- datacarriersize: Set the maximum size of the data in OP_RETURN outputs (in bytes) that your node will relay.
- permitbaremultisig: Choose wether or not to relay non-P2SH multisig transactions.
JoinMarket Compatibility: The deprecated RPC 'deprecatedrpc=create_bdb' is enabled to allow integration with JoinMarket and the Jam app by default. This fixes an issue where Jam app users who upgraded to Bitcoin Core v26.0 would have to …

Update Bitcoin Node to v27.0

---

lightning/docker-compose.yml
lightning/umbrel-app.yml

https://github.com/lightningnetwork/lnd/releases/tag/v0.17.5-beta
> This is a minor hot fix release that resolves an issue that arises (sendrawtransaction calls rejected) when lnd is run with bitcoind 27. This hot fix release bumps a dependency to ensure that lnd is compatible with the latest version of bitcoind.
Tested on arm64 and x86

Update Lightning Node to v0.17.5-beta

---

helipad/docker-compose.yml
helipad/umbrel-app.yml

Updates Helipad from `v0.1.11` to `v0.2.0`

Update Helipad to v0.2.0

---

overseerr/docker-compose.yml
overseerr/umbrel-app.yml

Updates Overseer from `1.32.5` to `1.33.2`.
Tested on rpi5 with Umbrel OS 1.1

Update Overseer from 1.32.5 to 1.33.2

---

seafile/docker-compose.yml
seafile/umbrel-app.yml

This fixes 2 issues:
- bad gateway error after starting the app: The seafile container has to use the container-name seafile-mysql to access the database
-  When connecting through one of the desktop seafile apps, there was an internal server error: This was caused by the additional proxy auth, that the apps could not handle so I deactivated it. Seafile already provides an authentification, so this seems redundant anyway.
I have also updated seafile to the latest patch version and tested it on umbrel home 1.1.

Fix bad gateway error in Seafile-app

---

bitcoin-knots/docker-compose.yml
bitcoin-knots/umbrel-app.yml

Update Bitcoin Knots to [v26.1.knots20240513](https://github.com/bitcoinknots/bitcoin/releases/tag/v26.1.knots20240513)
tested on Umbrel v0.5.4 (aarch64 and amd64)

Update Bitcoin Knots to v26.1.knots20240513

---

plex/docker-compose.yml
plex/umbrel-app.yml

This PR switches the Plex container to use host networking instead of bridge networking. This fixes two issues:
1) It solves the port clash issue with Home Assistant. Previously, if a user tried to install Plex after installing Home Assistant (but not the other way around) the explicit mapping of port 1900 in the Plex compose file would cause Docker to error because port 1900 would be in use by Home Assistant for SSDP discovery and uPNP. Both apps now use the hosts network stack and don't explicitly bind ports, so Docker will not error and they can successfully share the udp port.
2) DLNA server access in Plex will actually work. DLNA server access doesn't work in bridge network mode by default, because udp multicast packets are not automatically forwarded from the host network stack to …

Update Plex to work when Home Assistant is already installed

---

tailscale/docker-compose.yml
tailscale/umbrel-app.yml

This updated fixes a security issue: TS-2024-005
Fixed: getumbrel/umbrel#1831
I'll try to figure out a way to automate updates.

[URGENT] Updated tailscale to v1.66.0

---

bitcoin-knots/docker-compose.yml
bitcoin-knots/umbrel-app.yml

I have used the wrong word to describe the new relay options, see [here](https://github.com/Retropex/umbrel-bitcoin/commit/989b81fcdf98395b409139e583e969415cd9300c) and [here](https://github.com/Retropex/umbrel-bitcoin/commit/9237fa22d1a65364bfee57b1bb35ea2fa992a758).

better explanation of advanced relay options

---

calibre-web/umbrel-app.yml
ln-visualizer/umbrel-app.yml
prowlarr/umbrel-app.yml

Hello Umbrel Team,
I have found some issues in some apps:
- Calibre Web: According to the [schema](https://github.com/getumbrel/umbrel/blob/master/packages/umbreld/source/modules/apps/schema.ts), the website entry is mandatory. Other apps without a website used the GitHub repo as the website. So I have aligned that
- LN Visualizer: The type of the support entry seems to be a link. All the other apps are using it as a link, therefore I have added a `mailto:` to the email to be a valid link and be clickable
- Prowlarr: A missing newline
Thank you so much for your awesome work on UmbrelOS, I am really loving it.
I am exited for future features like https, domain names and backups 😍
Kind regards from Germany
Sharknoon

General fixes

---

jam/docker-compose.yml
jam/umbrel-app.yml

This patch update of Jam fixes an issue where Jam could not be run on a Raspberry Pi 5:
https://github.com/joinmarket-webui/jam-docker/issues/123
https://github.com/joinmarket-webui/jam-docker/pull/124#issuecomment-2124505130

Update Jam to v0.2.0-patch-20240521

---

thunderhub/docker-compose.yml
thunderhub/umbrel-app.yml

Includes an important upgrade for Boltz Swaps, see [release notes](https://github.com/apotdevin/thunderhub/releases/tag/v0.13.31)

Update Thunderhub to v0.13.31

---

helipad/docker-compose.yml
helipad/umbrel-app.yml
saifa/docker-compose.yml
saifa/umbrel-app.yml

App Submission 
...
app name (Saifa)
...
256x256 SVG icon
https://svgur.com/i/1452.svg
description: 
Saifa is designed to enhance the interoperability and efficiency of applications interacting with the Lightning Network Daemon (LND).
Our project simplifies the integration process, allowing applications to seamlessly connect to LND through an intuitive webhook system. 
With Saifa, users can effortlessly create new invoices using a straightforward REST API, cancel invoices, and receive real-time updates on invoice status.
This system is crafted to streamline operations and facilitate a smoother transaction experience on the Lightning Network,
making it an essential tool for developers looking to optimize their applications for better performance and user satisfaction.
...
Gallery images
I …

App Submission: Saifa (lnd Invoice manager)

---

agora/umbrel-app.yml
bitfeed/umbrel-app.yml
bleskomat-server/umbrel-app.yml
blockstream-blind-oracle/umbrel-app.yml
bluewallet/umbrel-app.yml
element/umbrel-app.yml
ipfs-podcasting/umbrel-app.yml
libreddit/umbrel-app.yml
libreoffice/umbrel-app.yml
libretranslate/umbrel-app.yml
lightning-shell/umbrel-app.yml
mealie/umbrel-app.yml
minio/umbrel-app.yml
passky-client/umbrel-app.yml
peerswap/umbrel-app.yml
readarr/umbrel-app.yml
remmina/umbrel-app.yml
satsale/umbrel-app.yml
snapdrop/umbrel-app.yml
sparkkiosk/umbrel-app.yml
squeaknode/umbrel-app.yml
synapse/umbrel-app.yml
tdex/umbrel-app.yml
urbit-bitcoin-connector/umbrel-app.yml
usocial/umbrel-app.yml

Hello,
I have found some small issues:
- Some apps are missing the key for the release notes in the `umbrel-app.yml`. 
- Adguard Home has the wrong [logo](https://github.com/getumbrel/umbrel-apps-gallery/blob/master/adguard-home/icon.svg). According to their [repo](https://github.com/AdguardTeam/AdGuardHome), the app should have this logo:
(This is a 256x256 optimized svg, ready to be used as app icon)
Kind regards
Sharknoon

Add missing `releaseNotes` keys and logo fix

---

core-lightning/docker-compose.yml
core-lightning/umbrel-app.yml

lightningd v24.02.2:
- pay route algorithm doesn't bias against our own "expensive" channels any more
- pay route algorithm fixed and refined to balance fees and capacity far better
- prevents repeating the preapproveinvoice check
- gossip feature bit deprecation for LDK compatibility fix
- renepay bugfix with situation htlcmax=htlcmin
- recover plugin can now detect dataloss and guide you through the recovery process, making emergency recoveries less stressful
- logic of the anchor channels has been overhauled and channel fundings and closing should now be more flexible and reliable
- dual-funding has been merged into the Lightning Specification! This is a major milestone for more efficient channel management
- gossip_store file can now be shared with others, since it no longer contains …

Updates cln-application to v0.0.5 and core lightning to v24.02.2

---

ghostfolio/docker-compose.yml
ghostfolio/umbrel-app.yml

Release notes: https://github.com/ghostfolio/ghostfolio/releases
Could not test it, but I don't see any breaking changes. 
Follows a repeated request for an update on the forum, as the current version is in some cases unusable. See here: 
https://community.umbrel.com/t/ghostfolio-needs-to-be-updated-due-to-yahoo-api-issue/16667

Update ghostfolio to 2.83.0

---

alby-nostr-wallet-connect/umbrel-app.yml
frigate/umbrel-app.yml
nutstash-wallet/umbrel-app.yml
tallycoin-connect/umbrel-app.yml
tdex/umbrel-app.yml

Hello,
to be consistent with other apps, I have removed the periods at the end of the taglines.
Exceptions were made for taglines like this: `Read. Listen. Pay back.` by `usocial`.
Kind regards
Sharknoon

Remove periods from taglines

---

penpot/docker-compose.yml
penpot/export.sh
penpot/umbrel-app.yml

Penpot has released v2 which has quite a lot of changes. https://github.com/penpot/penpot/releases/tag/2.0.0
I've updated the images in `docker-compose.yml` and I've updated the release notes + version in `umbrel-app.yml`. 
I tested the new container but I've been getting 502 errors which I can't resolve. The 502 error persists when reverting versions so I'm thinking I did something wrong when trying to test. The 502 occurs when a request to `http://umbrel.local:9001/api/rpc/command/get-profile` is made.

Update Penpot 2.0.1

---

qbittorrent/hooks/post-start
qbittorrent/umbrel-app.yml

This fixes an issue where qBittorrent sometimes required a restart after installation/update to v4.6.5 in order for default credentials to work.

Modify qBittorrent post-start hook for default credentials

---

mealie/docker-compose.yml
mealie/umbrel-app.yml

This updates Mealie from 1.0.0beta-5 to 1.8.0. This required a rewrite of the compose file because Mealie has changed from a two-container to a single container deployment.
Database migration is only needed for Mealie installations that are v0.5.6 and earlier. This does not impact any umbrelOS users because the initial release on the Umbrel app store was 1.0.0beta-5 (https://github.com/getumbrel/umbrel-apps/pull/608); no database migration is needed.
Tested on arm64 and x86.

Update Mealie to v1.8.0

---

just-download/docker-compose.yml
just-download/umbrel-app.yml

This time it's my own app!
`Just. Download.`
or
`Just Download`
If I manually insert the icon into Umbrel's homepage, it is just a little bit too bit
https://raw.githubusercontent.com/highghlow/just-download/main/public/icon.svg
_We will help finalize these images before the app goes live in the …

Add just download

---

databag/docker-compose.yml
databag/umbrel-app.yml

- added support for cloudflare turn service for audio and video calls as an alternative to self-hosting coturn
- added support for browser push notifications. existing session require log (out/in) to enable

updated to latest databag container

---

immich/docker-compose.yml
immich/umbrel-app.yml

Closes https://github.com/getumbrel/umbrel-apps/issues/1158
This update required structural changes to the compose file: https://github.com/immich-app/immich/releases/tag/v1.106.4
- removes the microservices container
- adds data checksums for data corruption detection in the In PostgreSQL container. 
Tested on arm64 and x86. Migration is successful. Server version 1.106.4 works with latest mobile version 1.106.3.

Update Immich to v1.106.4

---

bitcoin-knots/docker-compose.yml
bitcoin-knots/umbrel-app.yml

Update Bitcoin Knots to [v27.1](https://github.com/bitcoinknots/bitcoin/releases/tag/v27.1.knots20240621)

Update Bitcoin Knots to v27.1

---

mealie/docker-compose.yml
ntfy/docker-compose.yml
stirling-pdf/docker-compose.yml

Hello,
Docker Compose V1 does not allow booleans inside the `environment`, `labels` or the `extra_hosts` key.
This PR fixes that issue to get those apps running on umbrelOS 0.5 .
Kind reagards
Sharknoon

Fixed booleans for umbrelOS 0.5

---

paperless/docker-compose.yml

Hello,
the app `paperless` has a Postgres database, which lacks the digest in the image.
This PR fixes this issue.
Kind regards
Sharknoon

Add missing digest for postgres image

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to `v0.13.1-alpha`.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/blob/master/docs/release-notes/release-notes-0.13.1.md

lightning-terminal: update to `v0.13.1-alpha`

---

prowlarr/docker-compose.yml

For some indexers, it is required to proxy Prowlarr's traffic through FlareSolverr, as shown on the screenshot below.
My solution was to add FlareSolverr to Prowlarr's docker-compose, and configure the proxy in Prowlarr as shown below.
From my understanding, it would also be possible to use "getumbrel/media-app-configurator" to configure Prowlarr, however, I have no clue how to do that. Any help would be appreciated.

Add FlareSolverr to Prowlarr

---

lidarr/docker-compose.yml
lidarr/exports.sh
lidarr/umbrel-app.yml
prowlarr/docker-compose.yml
prowlarr/exports.sh
prowlarr/umbrel-app.yml
qbittorrent/hooks/post-start
qbittorrent/umbrel-app.yml
radarr/docker-compose.yml
radarr/exports.sh
radarr/umbrel-app.yml
readarr/docker-compose.yml
readarr/exports.sh
readarr/umbrel-app.yml
sabnzbd/docker-compose.yml
sabnzbd/hooks/post-install
sabnzbd/umbrel-app.yml
sonarr/docker-compose.yml
sonarr/exports.sh
sonarr/umbrel-app.yml

This PR updates Radarr, Sonarr, Lidarr, Readarr, Prowlarr, qBittorrent, and SABnzbd.
In addition to bumping the versions of these apps, this PR also makes it so that the Servarr and download client ecosystem auto-configures upon installation (this was already the case for Servarr apps and Transmission). Auto-configuration of Overseerr, Jellyseerr, and Autobrrr will be added in the future.
- The media-app-configurator will now connect these apps to qBittorrent and SABnzbd if they are installed. These download clients are optional and configuration will only be attempted if they are installed on a user's umbrel.
- This will not change a user's existing configuration if they have already connected the download client.
- User's can make changes to the configurations after install (e.g., name …

Update all Servarr apps and download clients to auto-configure

---

tailscale/docker-compose.yml
tailscale/umbrel-app.yml

Bump Tailscale to 1.68.1
Tested on: Raspberry Pi 4, umbrelOS 1.1.2 ✔️

Update Tailscale 1.68.1

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to `v0.13.2-alpha`.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/blob/master/docs/release-notes/release-notes-0.13.2.md

lightning-terminal: update to `v0.13.2-alpha`

---

peerswap/docker-compose.yml
peerswap/umbrel-app.yml

Adds option to advertise BTC and L-BTC balance to direct PeerSwap Web UI peers.

Update PeerSwap to v1.6.6

---

maybe/docker-compose.yml
maybe/umbrel-app.yml

Couldn't decide whether to add "Other technical improvements" as a feature, to cover non-feature type changes (?)

Update maybe to v0.1.0-alpha.11

---

paperless/docker-compose.yml
paperless/umbrel-app.yml

Without this line, no mobile app can recognize paperless and a usage with mobile apps is not possible

Ignore Proxy auth for usage with apps

---

.github/workflows/lint-apps.yml

This change fixes permission issues with PRs from external repositories (forks).
By adding the permission `pull-requests: write` and `issues: write` we allow comments to be posted to the PR by this bot.
A PR is internally an special issue, that is why we also need the `issue` permission, see [here](https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment).

Fixes permission issues

---

cloudflared/docker-compose.yml
cloudflared/umbrel-app.yml

Changes:
- The tunneling daemon (cloudflared) has been updated to 2024.6.1
- In the web app, updated dependency versions as per vulnerability audit results. This is not a user-facing change
Related: 
- #1169 
- https://github.com/Radiokot/umbrel-cloudflared/issues/8

Update Cloudflare Tunnel to 2024.6.1 (web 1.0.2)

---

mempool/docker-compose.yml
mempool/umbrel-app.yml

Add mempool widget

---

peerswap/docker-compose.yml
peerswap/umbrel-app.yml

Bug fixes and improvements. See full changelog here: https://github.com/Impa10r/peerswap-web/blob/main/CHANGELOG.md

Update PeerSwap to v1.6.7

---

vaultwarden/docker-compose.yml
vaultwarden/umbrel-app.yml

This is an automated app update of Vaultwarden that must be tested before merging.

Update Vaultwarden to 1.31.0

---

btcpay-server/docker-compose.yml
btcpay-server/umbrel-app.yml

Updated btcpay-server to 1.13.5. All other dependencies (postgress and nbxplorer) were verified up-to-date!

btcpay-server update to 1.13.5

---

duplicati/docker-compose.yml
duplicati/umbrel-app.yml

App Submission: Duplicati

---

btcpay-server/docker-compose.yml
btcpay-server/umbrel-app.yml

Fixes getumbrel/umbrel-apps#1292 and btcpayserver/btcpayserver#6128.

BTCPay Server: Remove deprecated NBXplorer options

---

bitcoin-knots/docker-compose.yml
bitcoin-knots/umbrel-app.yml

Update Bitcoin Knots to [v27.1.knots20240801](https://github.com/bitcoinknots/bitcoin/releases/tag/v27.1.knots20240801).

Update Bitcoin Knots to v27.1.knots20240801

---

onlyoffice-nextcloud/docker-compose.yml
onlyoffice-nextcloud/exports.sh
onlyoffice-nextcloud/umbrel-app.yml

App Submission: ONLYOFFICE Document Server for Nextcloud

---

navidrome/hooks/pre-start
navidrome/umbrel-app.yml

Adds a pre-start script to set proper permissions for music folder.
Tested on both fresh install and update.

Update Navidrome to v0.52.5-hotfix

---

btc-rpc-explorer/docker-compose.yml
btc-rpc-explorer/umbrel-app.yml

This PR adds RPC Terminal and RPC Browser functionality to BTC RPC Explorer. This is done by enabling password protection with a non-empty `BTCEXP_BASIC_AUTH_PASSWORD` environment variable.
Closes https://github.com/getumbrel/umbrel-apps/issues/569
The app only requires a password and no username, per https://github.com/janoside/btc-rpc-explorer/blob/adb80713ffea2a39fb600a3e61348dbd207bba52/.env-sample#L116-L118
...but the browser popup auth asks for both a username and password, so to avoid unnecessary confusion and instructions in the app-description to leave the username blank, I have just included a default username.

Update BTC RPC Explorer with RPC Terminal Functionality

---

uptime-kuma/docker-compose.yml
uptime-kuma/umbrel-app.yml

This PR whitelists the Uptime Kuma `/api` route from the auth proxy so that push monitors work (require pinging `http://<hostname>:8385/api/push/...`)

Update Uptime Kuma - whitelist api route in app proxy

---

synapse/docker-compose.yml
synapse/umbrel-app.yml

The compose configuration and initial installation setup for Synapse will need to change in order to update past version 1.55.0 (details to follow - will edit this comment).
https://github.com/matrix-org/synapse/blob/develop/docs/upgrade.md#upgrading-to-v1560
In the interim, I have updated Synapse to 1.55.0 to maintain compatibility with the latest Element app.

Update synapse v1.55.0

---

ordinals/docker-compose.yml
ordinals/hooks/pre-start
ordinals/umbrel-app.yml

This is a major version update, which requires a full re-index of ord (handled by our pre-start script).
Currently testing.

Update ordinals to v0.19.1

---

affine/docker-compose.yml
affine/umbrel-app.yml

Upgrade Affine to version 0.16.3.
The main difference is that the local version control panel has been added. The standard username and password are no longer needed, an administrator account is created in the setup wizard.

Upgrade Affine to version 0.16.3

---

lnbits/docker-compose.yml
lnbits/umbrel-app.yml

Update LNbits to the latest version

Update LNbits to 0.12.10 #1358

---

torq/docker-compose.yml
torq/umbrel-app.yml

Torq v.2.0.4:
A lot of improvements have been made in this release. It's hard to cover it all, but here are some highlights.
List of changes:
- Add advanced outputs table (UTXO management), with the ability to lock/unlock individual outputs.
- LND v0.18 support (+ inbound fees)
- CLN v24.05 support
- Tighter CLN integration via Torq plugin
- Fix opening a channel with CLN (missing close-to address)
- Fix CLN+LND on-chain transaction import (this will reimport on-chain transactions)
- Torq will import transactions + transaction inputs and outputs
- Ability to integrate Electrum (for unconfirmed on-chain notification support)
- System/workflow variables/templates in workflows
- example 1: proportionate fee template: 2000 - ({{Channels.peerGauge}} * 2000)
- example 2: dynamic max HTLC …

Update Torq to v2.0.4

---

just-download/docker-compose.yml
just-download/umbrel-app.yml

I have moved just-download to codeberg: https://codeberg.org/highghlow/just-download
That's the only change

Moved just-download to codeberg

---

bitcoin/docker-compose.yml
bitcoin/umbrel-app.yml

Awaiting `getumbrel/bitcoind:v27.1` image build. New bitcoind image must be added to the compose file and the app tested.
This PR updates the Bitcoin Node app to use the latest Bitcoin Core version 27.1. The previous [lncm/bitcoind](https://github.com/lncm/docker-bitcoind) image has been replaced with [getumbrel/bitcoind](https://github.com/getumbrel/docker-bitcoind).

Update Bitcoin Node to v27.1

---

robosats/docker-compose.yml
robosats/umbrel-app.yml

Update RoboSats to latest v0.7.0-alpha
Untested. Exactly replicated the steps to update to v0.6.0-alpha https://github.com/getumbrel/umbrel-apps/pull/1022

Update RoboSats to v0.7.0-alpha

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to `v0.13.4-alpha`.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/blob/master/docs/release-notes/release-notes-0.13.4.md

lightning-terminal: update to v0.13.4-alpha

---

home-assistant-fusion-ui/docker-compose.yml
home-assistant-fusion-ui/exports.sh
home-assistant-fusion-ui/umbrel-app.yml

Add Home Assistant Fusion UI

---

gitlab/docker-compose.yml
gitlab/umbrel-app.yml

GitLab _Community Edition_
https://images.ctfassets.net/xz1dnu24egyd/3JZABhkTjUT76LCIclV7sH/17a92be9bce78c2adcc43e23aabb7ca1/gitlab-logo-500.svg
_We will help finalize these images before the app goes live in the Umbrel App Store._
Linked Issue : #1219

App Submission: GitLab

---

zabbix/umbrel-app.yml

Zabbix Agent has its own service, so we need to target the Agent's service instead of the Server
As you can see, Zabbix reports an error (in red) when targeting the invalid service name, but it resolves successfully when targeting the updated one.

Bugfix: Update invalid Zabbix Agent service name

---

nostrudel/docker-compose.yml
nostrudel/umbrel-app.yml

upstream release https://github.com/hzrd149/nostrudel/blob/master/CHANGELOG.md#0410

Update noStrudel to v0.41.0

---

firefox/docker-compose.yml
firefox/umbrel-app.yml

The initial 130.0.1 image digest had some broken functionality. See https://community.umbrel.com/t/latest-update-broke-firefox/19332
This PR uses the latest digest for the 130.0.1 tag which solves the issue.

Update firefox to 130.0.1-hotfix

---

albyhub/docker-compose.yml
albyhub/umbrel-app.yml

AlbyHub is Alby's new self-custodial wallet. It is build around the NWC protocol to allow users connect their Umbrel lightning nodes to the growing number applications supporting NWC for payments. Most known are the various nostr apps to enable zapping.
Alby Hub is also the continuation of the Nostr Wallet Connect application with is already in the store.  
+ https://nwc.dev/
+ https://albyhub.com/
Alby Hub
https://svgur.com/s/19oF

App Submission: AlbyHub v1.10.1

---

jam/docker-compose.yml
jam/umbrel-app.yml

- Jam: [v0.3.0](https://github.com/joinmarket-webui/jam/releases/tag/v0.3.0)
- joinmarket-clientserver: [v0.9.11](https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.9.11)
All notable changes of the UI can be seen in the [Jam v0.3.0 changelog](https://github.com/joinmarket-webui/jam/blob/v0.3.0/CHANGELOG.md)

Update Jam to v0.3.0

---

pingvin-share/docker-compose.yml
pingvin-share/umbrel-app.yml

Pingvin Share
Sorry, no experience to create a SVG from an PNG
...

App Submission: Pingvin Share

---

nginx-proxy-manager/docker-compose.yml
nginx-proxy-manager/umbrel-app.yml

Nginx Proxy Manager
> ⚠️ Please take care while exposing apps to the internet.
> ⚠️ Note: This app listen on ports 40080 and 40443. In order to make the apps proxied by NPM accessible from internet, users need to port forward 80 to 40080 and 443 to 40443 on their router.⚠️
[DETAILED GUIDE](https://github.com/sahilph/sahil-umbrel-apps/wiki/How-to-use-Nginx-Proxy-Manager-on-your-Umbrel)
```
https://nginxproxymanager.com/logo.svg
```
Image 1:
Image 2:
Image 3:
Image 4:
Note: These screenshots are taken from NPM website.
I do not have Umbrel Home or Raspberry Pi, hence couldn't test it on them. However I have tested it on my Linux Machine (Umbrel OS 1.2.2) and it works fine.
---
For those who want to try it now, Nginx Proxy Manager is also available on [ my personal app …

App Submission: NPM (Nginx Proxy Manager)

---

mempool/docker-compose.yml
mempool/umbrel-app.yml

This release enables the Rust Get Block Template implementation by default for faster block indexing, there are no other code changes.
We're also taking the opportunity to limit the max heap size of the backend node process to 2gb.

Update mempool to v3.0.1 and set max heap size to 2gb

---

enclosed/docker-compose.yml
enclosed/umbrel-app.yml

Enclosed
https://svgshare.com/s/1BQT
1.jpg:
2.jpg:
3.jpg:
I have tested my app on:
[] umbrelOS on a Raspberry Pi
[] umbrelOS on an Umbrel Home
[] umbrelOS on Linux VM

App Submission: Enclosed

---

bitcoin/docker-compose.yml
bitcoin/exports.sh
bitcoin/umbrel-app.yml

- updates bitcoind to v28.0: https://github.com/getumbrel/docker-bitcoind
- updates getumbrel/umbrel-bitcoin to v0.8.0: https://github.com/getumbrel/umbrel-bitcoin/commits/master/
- `deprecatedrpc=warnings` has been added as a flag at startup for compatibility with LND https://github.com/getumbrel/umbrel-apps/pull/1709/commits/213323c35a6b985083892abdd07f34a55506f5a2
https://x.com/roasbeef/status/1842956355516223824

Update Bitcoin Node to v28.0

---

lightning/docker-compose.yml
lightning/umbrel-app.yml

Bumps LND from 18.0-beta to 18.3-beta
18.3-beta release notes: https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.18.3.md
18.2-beta release notes: https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.18.2.md
18.1-beta release notes: https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.18.1.md

Update LND to 18.3-beta

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to `v0.13.6-alpha`.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/blob/master/docs/release-notes/release-notes-0.13.6.md

lightning-terminal: update to v0.13.6-alpha

---

fulcrum/docker-compose.yml
fulcrum/exports.sh
fulcrum/hooks/pre-start
fulcrum/torrc.template
fulcrum/umbrel-app.yml

Fulcrum
Closes #613, also possibly resolves #134 
For those who want to try it now, Fulcrum is also available on [my personal app store](https://github.com/sahilph/sahil-umbrel-apps)
[https://svgshare.com/i/1Acv.svg](https://svgshare.com/i/1Acv.svg)
1.jpg:
2.jpg:
3.jpg:
4.jpg:

App Submission: Fulcrum

---

public-pool/docker-compose.yml
public-pool/umbrel-app.yml

This PR updates Public Pool with a fix for Bitcoin Core v28 compatibility:
https://github.com/benjamin-wilson/public-pool/pull/66
Thanks to @remcoros for the fix, @benjamin-wilson for the timely merge, and @sethforprivacy for building and maintaining the docker image.

Update Public Pool - Bitcoin Core v28 compatibility

---

tdex/exports.sh
tdex/umbrel-app.yml

This update removes legacy exports.sh logic that was preventing new installs from completing successfully.

TDEX Provider hotfix

---

itchysats/umbrel-app.yml

The ItchySats project is unmaintained and is now non-functional: https://github.com/get10101/itchysats
```
$ sudo docker logs -f itchysats_web_1
Error: failed to lookup address information: Name or service not known
```
This PR:
- adds `disabled: true` to the app manifest which results in ItchySats not being shown in the app store on umbrelOS >= 1.0
- adds a removal notice to the app description so that umbrelOS 0.5 users are aware that it is no longer functional

Remove ItchySats from app store

---

btcpay-server/docker-compose.yml
btcpay-server/umbrel-app.yml

I simply updated the images and could not test this further. Maybe someone can help verify that the upgrade works in production.

Update BTCPay Server to v2.0.1

---

mqttx-web/docker-compose.yml
mqttx-web/umbrel-app.yml

MQTTX Web
https://github.com/emqx/MQTTX/blob/main/web/public/icons/app.png
https://github.com/emqx/MQTTX/blob/main/assets/mqttx-web-preview.png
https://github.com/emqx/MQTTX/blob/main/assets/mqttx-connection.png
https://github.com/emqx/MQTTX/blob/main/assets/mqttx-muti-topics.png

App submission mqttx web

---

mattermost/docker-compose.yml
mattermost/umbrel-app.yml

Update mattermost to v10.2.0

---

electrs/docker-compose.yml
electrs/umbrel-app.yml

This PR updates:
- electrs to 0.10.7 https://github.com/getumbrel/docker-electrs
- the UI to 1.0.4 https://github.com/getumbrel/umbrel-electrs

Update electrs to v0.10.7

---

grafana/docker-compose.yml
grafana/umbrel-app.yml

Update Grafana to version 11.3.1

---

affine/docker-compose.yml
affine/umbrel-app.yml

Tried to update to v0.18.1, but there does not seem to be a proper container for it.
Tested on Raspberry Pi 5.

Update Affine to v0.18.0

---

datum/docker-compose.yml
datum/umbrel-app.yml

[release link](https://github.com/OCEAN-xyz/datum_gateway/releases/tag/v0.2.1beta)

update datum to v0.2.1-beta

---

torq/docker-compose.yml
torq/umbrel-app.yml

Hi, new update for Torq. Here are the details :)
v2.1 release notes:
- bitcoind wallet as a node type (Torq now has on-chain wallet support for CLN, LND and bitcoind)
- bitcoind existing on-chain address listing
- management of UTXO locking 
- improved transaction output visualizations (and backend)
- improve transaction output linking to channels (funding/closing transactions)
- LND: sweep transaction output linking to channels
- Torq gRPC (BETA feature):
- New call SubscribeBlockHeight
- New call PayOnChain
- New call DecodeInvoice
- New call GetInvoiceStatus
- We have been streamlining our names in the proto file (so breaking changes)
- Various small fixes
Note 1: There are database migrations in this release so if you want to be able to roll back, you need to create a backup before …

Update Torq to v2.1.0

---

bitcoin-knots/docker-compose.yml
bitcoin-knots/umbrel-app.yml

Forgot to push the Debian based image with `curl` for the datum release. 🤦‍♂️

new debian based image

---

grafana/docker-compose.yml
grafana/umbrel-app.yml

Update grafana to version 11.4.0

---

ride-the-lightning/docker-compose.yml
ride-the-lightning/umbrel-app.yml

https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.15.4
https://hub.docker.com/layers/shahanafarooqui/rtl/v0.15.4/images/sha256-286b7bbcd5f91e55eff757ad671c1147bfc7c2eb334c1d3308871245e51784d9?context=explore

Update rtl to the latest version

---

metube/docker-compose.yml
metube/umbrel-app.yml

Add variable to delete files from disk when deleting from web ui
https://github.com/alexta69/metube?tab=readme-ov-file#configuration-via-environment-variables

[METUBE] delete files from disk

---

mattermost/docker-compose.yml
mattermost/umbrel-app.yml

Tested update and install on Raspberry Pi 5 and Umbrel Home.

Update Mattermost to v10.3.1

---

linkwarden/docker-compose.yml
linkwarden/umbrel-app.yml

Linkwarden
Fixes #1643
Could not find an official svg, converted the official png that can be found here as best as I could:
https://docs.linkwarden.app/img/logo.png
https://svgur.com seems to be offline, uploaded it here for now:
https://filetransfer.io/data-package/RY5qNfVd#link
https://github.com/linkwarden/linkwarden/blob/main/assets/dashboard.png
https://docs.linkwarden.app/assets/images/showcase_image-2c911c624807d666e2d4feae7879d798.png
https://docs.linkwarden.app/assets/images/single_collection-ae357cb585f175e779783437fbdf0e0f.png

App Submission: Linkwarden

---

nitter/umbrel-app.yml

The Nitter project is unmaintained and is now non-functional due to changes in X's API: 
https://github.com/zedeus/nitter/issues/919
This PR:
- adds `disabled: true` to the app manifest which results in Nitter not being shown in the app store on umbrelOS >= 1.0
- adds a removal notice to the app description so that umbrelOS 0.5 users are aware that it is no longer functional
This does not remove existing installs of Nitter.

Remove Nitter

---

pocketbase/data/migrations/initial_superuser.js
pocketbase/docker-compose.yml
pocketbase/umbrel-app.yml

This PR updates pocketbase to version 0.23.12 and creates the initial superuser with a migration script.
Due to changes made to pocketbase starting with version 0.23, the intial superuser creation has to happen via the cli, the URL that is shown on the terminal or a migration script. See: https://github.com/pocketbase/pocketbase/discussions/5814
Tested both an upgrade and a fresh install on the Raspberry Pi 5 and Umbrel Home.
Existing users / admins will not be touched.
Closes #1969

Update pocketbase to version 0.23.12 and create initial superuser

---

gitlab/docker-compose.yml
gitlab/hooks/pre-start
gitlab/umbrel-app.yml

Update GitLab to most recent release
Key improvements released in GitLab 17.7 :
- New Planner user role
- New user contribution and membership mapping available in direct transfer
- Rotate personal, project, and group access tokens in the UI
- Set your preferred text editor as default
- Unicode 15.1 emoji support
- Kubernetes 1.31 support
- Bug fixes, performance improvements, and UI improvements
Tested on RPi 5 8GB and working :)

Update GitLab to 17.7.0

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to v0.14.0-alpha. Apologies for the delay of the update over the holidays. 
See the release notes here: https://github.com/lightninglabs/lightning-terminal/blob/master/docs/release-notes/release-notes-0.14.0.md

lightning-terminal: update to v0.14.0-alpha

---

samourai-server/docker-compose.yml
samourai-server/umbrel-app.yml

This is a hotfix for the dojo-node container. It fixes an issue with the now unmaintained https://github.com/vansergen/rpc-bitcoin library which does not conform to the strict sanity check that Bitcoin Core v28.0 now carries out to determine which JSON-RPC behaviour to follow (version "1.0" vs version "2.0").
Fix: https://github.com/nmfretz/umbrel-samourai-dojo/commit/e8e439ae1f4931b7f28e6f1aeb208df704f67255
As of April 2024 Whirlpool functionality no longer works due to the shutdown of Samourai's Whirlpool coordinator. Dojo functionality is unaffected. 
This app should be updated to the latest Dojo version and Whirlpool should be removed. The current structure of this app means that this is not a quick fix. Current dojo repo:
https://github.com/Dojo-Open-Source-Project/samourai-dojo
I …

Samourai Server hotfix

---

homebox/docker-compose.yml
homebox/umbrel-app.yml

The split between architectures was finally fixed in sysadminsmedia/homebox#365 🎉 
Tested update and fresh install on Raspberry Pi 5 and Umbrel Home.

Update homebox to version 0.17.1

---

btcpay-server/docker-compose.yml
btcpay-server/umbrel-app.yml

Updates both btcpayserver and nbxplorer containers. Requires testing before merge.

Update btcpay-server to v2.0.5

---

syncthing/docker-compose.yml
syncthing/umbrel-app.yml

Update syncthing to version 1.29.1

---

lobe-chat/docker-compose.yml
lobe-chat/umbrel-app.yml

Lobe Chat
Fixes #1898
https://github.com/lobehub/lobe-icons/blob/master/packages/static-svg/icons/lobehub-color.svg

App Submission: Lobe Chat

---

obsidian/docker-compose.yml
obsidian/umbrel-app.yml

Obsidian
Fixes #1327
https://en.m.wikipedia.org/wiki/File:2023_Obsidian_logo.svg

App Submission: Obsidian

---

maybe/docker-compose.yml
maybe/umbrel-app.yml

Update Maybe to newest release - https://github.com/maybe-finance/maybe/releases/tag/v0.3.0

Upgrade maybe finance to 0.3.0

---

linkwarden/docker-compose.yml
linkwarden/umbrel-app.yml

Tested update on Umbrel Home and fresh install on Raspberry Pi 5.
I noticed some bugs like Linkwarden not being able to create snapshots of websites. This is due to the fact that official support for non-root is still missing. 
There is already a PR open for non-root support: linkwarden/linkwarden#779 
Also changed the database url as I have seem some errors in the logs. Changing it to the full name seems to fix it.
Would run it as root for the time being if that is ok @nmfretz

Update Linkwarden to version 2.9.3 and run as root

---

immich/docker-compose.yml
immich/umbrel-app.yml

Tested update and fresh install on Umbrel Home. Fresh install on Raspberry Pi 5. (Took a long time to start on the Pi)
I disabled the app proxy authentication as immich comes with authentication built in. 
This way users are able to setup a reverse proxy in front of immich for external access. Please let me know if it is ok like this @nmfretz.

Update immich to version 1.125.6 and disable umbrel app proxy

---

vaultwarden/docker-compose.yml
vaultwarden/umbrel-app.yml

This is pull request to update vaultwarden to version 1.33.0. 
This PR must be reviewed and tested before merging.

Update vaultwarden to version 1.33.0

---

ollama/docker-compose.yml
ollama/exports.sh
ollama/umbrel-app.yml

Ollama
https://github.com/simple-icons/simple-icons/blob/develop/icons/ollama.svg
Ollama only shows that it is running on the Web UI, we would need some setup images instead.

App Submission: Ollama

---

open-webui/docker-compose.yml
open-webui/umbrel-app.yml

Open WebUI
@nmfretz It could make sense to split ollama into a separate app. But it has no UI other than showing that it is running when you access the port.
Both parts do not work properly without the root user.
https://filetransfer.io/data-package/N7NbYURd#link

App Submission: Open WebUI

---

jackett/docker-compose.yml
jackett/umbrel-app.yml

🤖 This is an automated summary of installation tests for jackett:

Update jackett to v0.22.1363

---

wikijs/docker-compose.yml
wikijs/umbrel-app.yml

🤖 This is an automated summary of installation tests for wikijs:

Update wikijs to v2.5.306

---

radarr/docker-compose.yml
radarr/umbrel-app.yml

🤖 This is an automated summary of installation tests for radarr:

Update radarr to v5.18.4.9674

---

baikal/docker-compose.yml
baikal/umbrel-app.yml

🤖 This is an automated summary of installation tests for baikal:

Update baikal to 0.10.1

---

gitlab/docker-compose.yml
gitlab/hooks/pre-start
gitlab/umbrel-app.yml

Update GitLab to most recent release
Key improvements released in GitLab 17.8 :
- Enhance security with protected container repositories
- List the deployments related to a release
- Machine learning model experiments tracking in GA
- Track multiple to-do items in an issue or merge request
- Primary domain redirect for GitLab Pages
- Pipeline limits available in GitLab Community Edition
- Bug and security fixes, performance improvements, and UI improvements
Tested on RPi 5 8GB and working ✅

Update GitLab to v17.8.1

---

gitea/docker-compose.yml
gitea/umbrel-app.yml

🤖 This is an automated summary of installation tests for gitea:
Tested update on Umbrel Home.

Update gitea to v1.23.3

---

enclosed/docker-compose.yml
enclosed/umbrel-app.yml

🤖 This is an automated summary of installation tests for enclosed:
Tested fresh install on Umbrel Home.

Update enclosed v1.14.0

---

open-webui/docker-compose.yml
open-webui/umbrel-app.yml

🤖 This is an automated summary of installation tests for open-webui:
Tested update on Umbrel Home.

Update open webui v0.5.10

---

n8n/docker-compose.yml
n8n/umbrel-app.yml

🤖 This is an automated summary of installation tests for n8n:
Tested fresh install on Umbrel Home.

Update n8n n8n@1.77.3

---

wordpress/docker-compose.yml
wordpress/umbrel-app.yml

WordPress
https://en.m.wikipedia.org/wiki/File:WordPress_blue_logo.svg
Port mapping needed as the app_proxy seems to remove headers set by nginx or other proxies.

App Submission: WordPress

---

tailscale/docker-compose.yml
tailscale/umbrel-app.yml

This update reverts Tailscale to the previous stable version to resolve a [sign-in issue introduced in 1.80.0](https://github.com/tailscale/tailscale/issues/14872). If you were affected, simply update to restore access.
Tested fresh install, app update, and downgrade from 1.80.0 (including sign-out/sign-in)

Downgrade Tailscale to v1.78.3

---

peerswap/docker-compose.yml
peerswap/umbrel-app.yml

- Fix Auto Fee not working for channels with no outbound forwards
- Better indication when all channels with a peer are inactive
- Catch Bitcoin Core and Elements Core RPC errors
- Fix telegram bot panic on wrong token or chat id
- Allow Bitcoin fee rates with 0.01 precision
- Reserve 1200 sats of LBTC balance to save on Elements fees
- Show confidential peg-in join time limit on peg-in form
- Allow updating txid of externally funded peg-in when not found

Update PeerSwap to v1.7.7

---

public-pool/docker-compose.yml
public-pool/umbrel-app.yml

This update brings a brand new Public Pool widget, allowing you to see your pool stats at a glance right from your umbrelOS home screen!
To add this widget, right-click on your home screen and select "Edit widgets", or click on Widgets in the Dock.

Add Public Pool widget

---

ordinals/docker-compose.yml
ordinals/hooks/pre-start
ordinals/umbrel-app.yml
scanservjs/docker-compose.yml
scanservjs/umbrel-app.yml

Request: #1085 
This app will require the scanner to be connected by usb to the Umbrel. Less that ideal, but that's what usb ports on the Umbrel home are for... right?
Also, btw, can you give me the power to close issues in the `umbrel` repo? There're a lot of resolved issues where the authors are not responding.
scanservjs
This project doesn't have an icon. There're no google image results for `scanservjs`. You'll have to make an icon of your own.
_(Upload 3 to 5 …

App submission: scanservjs

---

romm/docker-compose.yml
romm/umbrel-app.yml

[romm](https://github.com/zurdi15/romm) (Rom Manager) is a web based retro roms manager integrated with IGDB. Also it has an embebed emulator
256x256 SVG icon
https://raw.githubusercontent.com/zurdi15/romm/a700aa98429b0ec96ec8d9d32ffa01c989d3569f/romm.svg
Gallery images
I have tested my app on:
[Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
[Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
[Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

App Submission: RomM

---

bitcoin/docker-compose.yml
bitcoin/exports.sh
bitcoin/umbrel-app.yml

Pending compatibility testing with major apps in the ecosystem.
TODO: check if `-deprecatedrpc=warnings` can be removed for new LND update https://github.com/lightningnetwork/lnd/blob/0-18-4-branch/docs/release-notes/release-notes-0.18.4.md#functional-enhancements

Update Bitcoin Node to v28.1

---

lightning/docker-compose.yml
lightning/umbrel-app.yml

Pending compatibility testing with major apps in the ecosystem.
TODO: check if `-deprecatedrpc=warnings` can be now be removed from the Bitcoin Node app
https://github.com/lightningnetwork/lnd/blob/0-18-4-branch/docs/release-notes/release-notes-0.18.4.md#functional-enhancements
This update is holding up https://github.com/getumbrel/umbrel-apps/pull/2184

Update Lightning Node to 0.18.5-beta

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to v0.14.1-alpha. 
See the release notes here: https://github.com/lightninglabs/lightning-terminal/blob/master/docs/release-notes/release-notes-0.14.1.md

lightning-terminal: update to `v0.14.1-alpha`

---

cloudflared/docker-compose.yml
cloudflared/umbrel-app.yml

The tunneling daemon (cloudflared) has been updated to 2025.2.0. This update includes security patches, performance improvements, and bug fixes. There are no visible changes in this update.

Update Cloudflared to 2025.2.0

---

adguard-home/docker-compose.yml
adguard-home/umbrel-app.yml

🤖 This is an automated summary of installation tests for adguard-home:

Update adguard-home to v0.107.57

---

gitea/docker-compose.yml
gitea/umbrel-app.yml

🤖 This is an automated summary of installation tests for gitea:

Update gitea to v1.23.4

---

open-webui/docker-compose.yml
open-webui/umbrel-app.yml

Tested by updating files at and causing update to trigger:
- `/home/umbrel/umbrel/app-stores/getumbrel-umbrel-apps-github-53f74447/open-webui/docker-compose.yml`
- `/home/umbrel/umbrel/app-stores/getumbrel-umbrel-apps-github-53f74447/open-webui/umbrel-app.yml`
Update was successful without issues and existing data persists.

Update open webui v0.5.16

---

core-lightning-rtl/docker-compose.yml
core-lightning-rtl/umbrel-app.yml

Update RTL (Core Lightning) - Add Boltz client

---

n8n/docker-compose.yml
n8n/umbrel-app.yml

🤖 This is an automated summary of installation tests for n8n:
Tested on Umbrel Home and Dev instance.

Update n8n to version 1.80.3

---

pi-hole/docker-compose.yml
pi-hole/umbrel-app.yml

Tested fresh install on dev instance and update on Umbrel Home. 
Some more testing would be needed still.

Update pi-hole to version 2025.02.6

---

duplicati/docker-compose.yml
duplicati/umbrel-app.yml

🤖 This is an automated summary of installation tests for duplicati:
Tested fresh install on dev instance and update on Umbrel Home.

Update duplicati to version v2.1.0.4_stable_2025-01-31

---

wikijs/docker-compose.yml
wikijs/hooks/pre-start
wikijs/umbrel-app.yml

This update adds the repo folder to wikijs to fix permissions errors when using the git sync feature.
Fixes #2176.
Maybe you can test and take a look at the new hook @nmfretz.

Wikijs repo fix

---

monero/docker-compose.yml
monero/umbrel-app.yml

This image includes the ban list of suspected spy node IP addresses, provided by the Monero Research Lab.
References:
- https://github.com/monero-project/meta/issues/1124
- https://github.com/sethforprivacy/simple-monerod-docker/commit/cea9d8c83738f8164f8d8e09648c916c571c1571

Update to the latest simple-monerod image

---

zabbix/docker-compose.yml
zabbix/umbrel-app.yml

Upgrade Zabbix to version 7.2.4
At the time of creating this PR, Zabbix Server's Alpine image was not pushed yet:  
https://hub.docker.com/r/zabbix/zabbix-server-pgsql/tags?name=7.2.4-alpine
We can apply this last update as soon as the image is available, then we can merge

[Awaiting new image] - Update Zabbix to v7.2.4

---

budibase/docker-compose.yml
budibase/umbrel-app.yml

🤖 This is an automated summary of installation tests for budibase:

Update budibase to 3.4.24

---

pi-hole/docker-compose.yml

Previously the web GUI was reachable over IPv4 and IPv6.
But recently someone updated this app to v6 and forgot to include the IPv6 port. So this corrects that issue.

fix: Pihole over IPv6

---

pi-hole/umbrel-app.yml

Updates app manifest for https://github.com/getumbrel/umbrel-apps/pull/2288
Context: https://github.com/getumbrel/umbrel-apps/pull/2288#issuecomment-2709475716

Update pi-hole to v2025.02.6-ipv6

---

open-webui/docker-compose.yml
open-webui/umbrel-app.yml

Tested by updating app-store files on Umbrel OS 1.4, and causing update to trigger:
- `open-webui/docker-compose.yml`
- `open-webui/umbrel-app.yml`
Update was successful without issues and existing data persists.

Update Open-webUI to v0.5.20

---

blinko/docker-compose.yml
blinko/umbrel-app.yml

Tested fresh install on Umbrel Dev instance and update on Umbrel Home. Everything working as expected.
This fixes #2297
Note, when opening this PR version 0.43.5 was already out, but there was no docker container available yet.

Update blinko to version 0.43.4

---

ordinals/docker-compose.yml
ordinals/hooks/pre-start
ordinals/umbrel-app.yml

🚨 As usual, major version updates require ord to re-index from scratch. This process will happen automatically when you update the app. 
⏳ If ord is currently indexing, it may take a few minutes to safely shut down before updating. Please be patient during this process.
- Tested on arm64 and x86. 
- Tested fresh install and app update from previous major version
- Tested ord cli commands to ensure compatibility with Core v28.0+

Update ord to v0.22.2

---

albyhub/docker-compose.yml
albyhub/umbrel-app.yml

Updates to Alby Hub v1.15.0
Which contains an important bug fix for a relay connection issue. 
In some cases a relay connection fails for some app connections which is then not recovered which causes the app to fail.

Alby Hub v1.15.0

---

btcpay-server/docker-compose.yml
btcpay-server/umbrel-app.yml

Tested on Umbrel Home, maybe you can also take a look @nmfretz @sharknoon.

Update btcpay-server to version 2.0.8

---

libretranslate/umbrel-app.yml

This PR removes the LibreTranslate from the app store for now over trademark issues.

Remove libretranslate from 1.x app store

---

libretranslate/umbrel-app.yml

Related to https://github.com/getumbrel/umbrel-apps/pull/2528
Also disables on the app store for pre-1.0 umbrelOS installs

Disable LibreTranslate on pre-1.0 app stores

---

mempool/docker-compose.yml
mempool/umbrel-app.yml

Updating the mempool app to v3.2.0
Full changelog available at https://github.com/mempool/mempool/releases/tag/v3.2.0
Note to Umbrel folks: this release includes changes to the Docker images, which are now using newer base OS images and Node/Rust versions.

Update the mempool app to v3.2.0

---

monero/docker-compose.yml
monero/umbrel-app.yml

This is the v0.18.4.0 release of the Monero software. It is a recommended release that fixes multiple daemon-related network vulnerabilities.

Update Monero daemon to v0.18.4.0

---

kollider/umbrel-app.yml

This removes kollider from the Umbrel App Store as the app is no longer maintained.
More information can be found here: https://x.com/kollider_trade/status/1720428682072772708
Closes #2435

Remove kollider from app store

---

mempool/docker-compose.yml
mempool/umbrel-app.yml

Updating the mempool app to v3.2.1 - this is a hotfix for a potential crash if the list of mining pools could not be updated.
Official release notes available at https://github.com/mempool/mempool/releases

Update the mempool app to v3.2.1

---

bitwatch/docker-compose.yml
bitwatch/umbrel-app.yml

This release adds support for extended public key address watching, cleans up UI and fixes several minor bugs.
- Add support for xpub/ypub/zpub addresses as a sub-collection
- extended keys can be configured with an initial number of addresses to watch, a gap limit of empty addresses to keep updating on the list, and a skip count to jump over already spent addresses.
- adds better public mempool.space API rate limiting and a new apiDelay config for being nicer to the API
- new defaults in config for public mempool.space API usage to better align with rate limits
- UI impprovements to unify styles, cleanup modules and make buttons cleaner
New gallery images (if you want to update them):

update bitwatch to 1.5

---

influxdb/docker-compose.yml
influxdb/umbrel-app.yml

This update just bumps influxdb to a newer sha tag and aligns the version with the one already used for the container.

Bump influxdb to version 1.11.8

---

kokoro/umbrel-app.yml

This update just aligns the version to what is actually being installed.

Bump kokoro version to 0.2.3

---

jellyseerr/docker-compose.yml
jellyseerr/umbrel-app.yml

Jellyseerr was not really updated to version 2.5.2 before.

Update sha256 to get Jellyseerr to version 2.5.2

---

wordpress/docker-compose.yml
wordpress/umbrel-app.yml

Tested on Umbrel Home and dev instance.
Added note that the actual update needs to be done via the admin interface.

Update wordpress to version 6.8.1

---

bitcoin/exports.sh
libre-relay/exports.sh

Exports `APP_BITCOIN_NETWORK` as `testnet` when running on testnet3.
@Impa10r can you please check to see if this simple change in the Bitcoin Node app works for your purposes?
If it solves your issue, are you okay if we include this fix with the [Core 29.0 release](https://github.com/bitcoin/bitcoin/releases/tag/v29.0)? I need to set aside some time next week to build the bitcoind image because with 29.0 the build system has migrated from Autotools to CMake.
related: https://github.com/getumbrel/umbrel-apps/pull/2353

Ensure Bitcoin testnet3 compatibility for dependent apps

---

lnbits-holesail-proxy/docker-compose.yml
lnbits-holesail-proxy/umbrel-app.yml

I want to mention that I'm not part of either https://lnbits.com or https://holesail.io . I just found Holesail as a very useful way to connect to my LNbits remotely even if it runs behind NAT  - without the overhead of TOR.
Notice the first commit that makes changes to the LNbits app submission in order to expose its port to the holesail proxy.
Since LNbits work on port 3007, I think it would be nice if the proxy worked on port 3107 (and likewise, if we implement similar proxies for other apps, we could have the proxy management port number to be the app port number + 100).
LNbits should also have a fixed ip address, exposed to the proxy.
LNbits Holesail Proxy
I only have a png for the holesail.io logo. I think a good icon would combine the logos of LNbits and Holesail like this:
- [v] …

App Submission: LNbits Holesail Proxy

---

bitwatch/docker-compose.yml
bitwatch/umbrel-app.yml

This release adds support for taproot extended keys and descriptors.
- Adds support for taproot extended keys (vpub)
- Adds support for descriptors (e.g. multiSig: wsh(multi(2,xpub...,...))
- Allows saving default monitor settings
- Refresh buttons on addresses and descriptor/extended key sets
- fix bug in reloading on sub-pages
New gallery images (if you want to update them):

update bitwatch to 1.6

---

btcpay-server/docker-compose.yml
btcpay-server/umbrel-app.yml

This PR bumps the version of nbxplorer to resolve an issue processing block 896727
More information: 
https://github.com/dgarage/NBXplorer/issues/518

Update nbxplorer image to version 2.5.26

---

bitwatch/docker-compose.yml
bitwatch/umbrel-app.yml

This release completely rebuilds the websocket and API request queue logic and includes bug, performance, and UX fixes.
- new method for mempool.space websocket subscription management
- now managed per address to prevent hundreds of websocket subscriptions
- improved websocket logic for adding/editing/deleting addresses
- showing websocket subscription status in address row
- clearer UI for zero balances (opacity reduction)
- tighter UI (reduced margin/padding)
- fix auto-acceptance bug (failing to alert telegram when alert is set in some cases)
- descriptor and extended key rows now show balance summary of address lists
- more robust e2e tests

update bitwatch to 1.7.0

---

torq/docker-compose.yml
torq/umbrel-app.yml

Release notes for 2.2.2
- Torq API node handle grouping
- A possibility to make hierarchy of nodes that are used in Torq API.
- For example: primarly use Node A, but if it is unreachable, use Node B. Or: use Node A 70% of the time and Node B 30% of the time.
- Node data import downtime threshold
- Configurable threshold for when to run events and imports for node data depending on how long was Torq down for.
- For example: there is a workflow that is set to trigger on "Payment". Then a payment happened on the node while Torq was down. If Torq was down less than the threshold that was set, the workflow **is** triggered when Torq starts, and if Torq was down longer than the threshold, the workflow **is not** triggered.
- Possibility to add/remove tags via Tags -> Manage -menu
- Show tagging …

Update Torq to v2.2.2

---

readarr/docker-compose.yml
readarr/umbrel-app.yml

Update readarr to version 0.4.16.2793

---

fulcrum/docker-compose.yml
fulcrum/umbrel-app.yml

Fulcrum is very susceptible to database corruption. Even a mere shutdown/restart of Umbrel can cause database corruption. 
This PR attempts to mitigate the issue by changing docker's default stop signal to `SIGINT` as per the [recommendation ](https://github.com/cculianu/Fulcrum/issues/115#issuecomment-1140124624) from Fulcrum's developer.
`stop_grace_period` has also been increased to make sure Fulcrum finished writing the block and complete the cleanup on slower machines/ HDDs

Fulcrum database corruption mitigation

---

thunderhub/docker-compose.yml
thunderhub/umbrel-app.yml

Fixes issues when fetching multiple Boltz swap statuses.

Update Thunderhub to v.0.13.32

---

trilium-notes/docker-compose.yml
trilium-notes/umbrel-app.yml

Tested update on Umbrel dev instance and fresh install on Umbrel Home.

Update trilium-notes to v0.95.0

---

cloudflared/docker-compose.yml
cloudflared/umbrel-app.yml

This PR updates the cloudflared daemon of the Cloudflare Tunnel app to [2025.6.1](https://github.com/cloudflare/cloudflared/blob/9ca8b41cf79fa08ec58c0209eef940851df9157b/RELEASE_NOTES).
There are no user-facing changes in this update.

Update Cloudflare Tunnel daemon to 2025.6.1

---

btc-rpc-explorer/docker-compose.yml
btc-rpc-explorer/umbrel-app.yml

~~DO NOT MERGE YET~~
Tested and working on x86 and arm64. It looks like there is a small issue where the project forgot to update the version number in their UI:
Let's wait a couple days to see if they release a fix, just so we don't release 2 updates close together with only a cosmetic version change.

Update btc-rpc-explorer to v3.5.0

---

lightning-terminal/docker-compose.yml
lightning-terminal/umbrel-app.yml

In this PR we bump Litd to v0.15.0-alpha.
See the release notes here: https://github.com/lightninglabs/lightning-terminal/blob/master/docs/release-notes/release-notes-0.15.0.md

lightning-terminal: update to v0.15.0-alpha

---

solidtime/hooks/post-start
solidtime/hooks/pre-start
solidtime/umbrel-app.yml

This update generates a `client_id` that can be used to login to the solidtime Desktop App.
Fixes #3090

Enable Desktop Client use for Solidtime

---

peerswap/docker-compose.yml
peerswap/umbrel-app.yml

Major bump to protocol version 5 that introduces swap premiums. 
Full changelog: https://github.com/Impa10r/peerswap-web/blob/main/CHANGELOG.md

Update PeerSwap to v5.0.0

---

lightning/docker-compose.yml
lightning/umbrel-app.yml

LND release notes: https://github.com/lightningnetwork/lnd/releases/tag/v0.19.2-beta
Updates the underlying Lightning Network Daemon (LND) that powers this app to v0.19.2-beta.
Garbage collection is run on the sphinx.replay.db on update.
Tested on my main LND instance:
```
2025-07-24 02:37:04.943 [INF] CHDB: Checking for optional update: name=gc_decayed_log
2025-07-24 02:37:04.943 [INF] CHDB: Performing database optional migration: gc_decayed_log
2025-07-24 02:37:04.943 [INF] CHDB: Migrating decayed log...
2025-07-24 02:37:04.944 [INF] CHDB: Decayed log migrated successfully
2025-07-24 02:37:04.947 [INF] CHDB: Successfully applied optional migration: gc_decayed_log
```
Tested and is working with other Lightning ecosystem apps.

Update Lightning Node to v0.19.2-beta

---

firefox/umbrel-app.yml

Will be re-enabled once HTTP support is back or Umbrel HTTPS support is available.

Disable firefox

---

sabnzbd/docker-compose.yml
sabnzbd/umbrel-app.yml

I'm editing sabnzbd docker-compose.yml by adding environment variables to make use of docker-mods to install ffmpeg package. See https://github.com/linuxserver/docker-mods and https://github.com/linuxserver/docker-mods/tree/universal-package-install
This will also close issue #3325

ffmpeg support for Sabnzbd

---

README.md

Since GitHub now allows SVG files to be attached to a PR, there is no longer a need for external services. In particular, https://svgur.com has been hacked. It should not be recommended.
Any other places like PR templates that recommend svgur.com should also be updated.

Remove svgur.com from PR description example

---

jam/docker-compose.yml
jam/umbrel-app.yml

- Jam: [v0.4.1](https://github.com/joinmarket-webui/jam/releases/tag/v0.4.1)
- joinmarket-clientserver: [v0.9.11](https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.9.11)
All notable changes of the UI can be seen in the [Jam v0.4.1 changelog](https://github.com/joinmarket-webui/jam/blob/v0.4.1/CHANGELOG.md)

Update Jam to v0.4.1

---

monero/docker-compose.yml
monero/umbrel-app.yml

Monero 0.18.4.2 (Fluorine Fermi) has been released, so we upgrade the daemon in the corresponding Umbrel app accordingly.

Update Monero daemon to v0.18.4.2

---

wger/docker-compose.yml
wger/umbrel-app.yml

This updates the media url of wger so images can be displayed properly.
Usually this command needs to be executed so the default images are downloaded, we could consider to add this to a pre-start script in the future: `docker exec -it wger_web_1 python3 manage.py download-exercise-images`

Update wger media url

---

fulcrum/docker-compose.yml
fulcrum/hooks/post-update
fulcrum/hooks/pre-start
fulcrum/umbrel-app.yml

https://github.com/cculianu/Fulcrum/releases/tag/v2.0.0
From Fulcrum's official release notes:
>#### Upgrade Instructions
>Fulcrum 2.0 has a different database format than the 1.x series. As such, you have two options for upgrading:
>
>Create a blank new datadir and just re-synch from block 0 (slow, but 100% reliable)
Upgrade your existing 1.x datadir (faster, but irreversible and destructice)
To upgade your existing database, be sure to pass the one-time --db-upgrade flag to Fulcrum. It will refuse to start up if it detects that your datadir is in the old format and you did not pass this flag. This ensures that admins know what they are getting into.
>
>Note: The upgrade process takes seconds to minutes on BCH and BTC testnet(s), maybe ~15 minutes on BCH mainnet, and around an hour or …

Update fulcrum to v2.0
