lightning/docker-compose.yml, lightning/umbrel-app.yml
Tested on my prod Umbrel with real funds.
=> Fix LND version. Use 0.14.2-beta

home-assistant/docker-compose.yml, home-assistant/umbrel-app.yml
https://www.home-assistant.io/blog/2022/06/01/release-20226/
https://hub.docker.com/layers/home-assistant/homeassistant/home-assistant/2022.6.4/images/sha256-e96a01479012e637fbe0729adf3448f673b53252508130cac320e0d2dc2f89e6?context=explore
https://github.com/home-assistant/core/releases/tag/2022.6.4
=> Update Home Assistant to 2022.6.4

uptime-kuma/docker-compose.yml, uptime-kuma/umbrel-app.yml
**Current ongoing version:** 1.11.1
**Release Notes :** 
https://github.com/louislam/uptime-kuma/releases/tag/1.16.1
**Docker Hub:**
https://hub.docker.com/layers/uptime-kuma/louislam/uptime-kuma/1.16.1/images/sha256-6d34d6f91553e30f7cd235e4eb7fa927fee381b0e8318fc49b794113791bb21f?context=explore
=> Update uptimekuma to 1.16.1

lightning/docker-compose.yml, lightning/umbrel-app.yml
I know it is not the final release, but I had a lot of force-closures on my channels due to a bug in 0.14, so I cannot afford to wait for it any longer.
=> Upgrade LND to 0.15.0 beta

code-server/docker-compose.yml, code-server/umbrel-app.yml
`codercom/code-server       4.4.0      sha256:f0b4cdac7b7742ec83167666b5bc8abb90c4f2660247d482f55fee916d079cb6   7 weeks ago     725MB`
=> code-server 3.11.1 -> 4.4.0

simple-torrent/docker-compose.yml, simple-torrent/umbrel-app.yml
Updated the docker image to 1.3.9
=> Updated simpletorrent to 1.3.9

lightning-terminal/docker-compose.yml, lightning-terminal/umbrel-app.yml
https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.7.0-alpha
=> lightning-terminal: bump version to v0.7.0-alpha

urbit/docker-compose.yml, urbit/umbrel-app.yml
Updatd the urbit binry to v1.9 and added some extra instruction on how to use the app
=> Update Urbit app to 0.4.1

photoprism/docker-compose.yml, photoprism/umbrel-app.yml
=> Whitelist PhotoPrism WebDAV endpoints

jam/docker-compose.yml, jam/umbrel-app.yml
Replaces https://github.com/getumbrel/umbrel-apps/pull/52 (cherry-picked into master to avoid conflicts)
=> Update Jam to v0.0.8

lndg/docker-compose.yml, lndg/umbrel-app.yml
Updates LNDg to v1.2.0
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/28046226?tag=v1.2.0
https://github.com/cryptosharks131/lndg/releases/tag/1.2.0
=> LNDg v1.2.1

tailscale/exports.sh, tailscale/umbrel-app.yml
The apps script changed in 0.5.1 so the previous checksum check failed.
=> Patch Tailscale for Umbrel 0.5.1

README.md
Document the new `releaseNotes` key in `umbrel-app.yml`.
=> Document releaseNotes

pi-hole/docker-compose.yml, pi-hole/umbrel-app.yml
**Github release:** https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.07.1
**Dockerhub:** https://hub.docker.com/layers/pihole/pihole/pihole/2022.07.1/images/sha256-02481b81def44028744e20259164238937cb6ce6933c33ab9b88f797ac0968d0?context=explore
=> Update pihole 2022.07.1

samourai-server/docker-compose.yml, samourai-server/umbrel-app.yml
- feat: add release notes
- feat: update samourai-server app to v1.16.1
=> feat: update samourai-server app to v1.16.1

oak-node/docker-compose.yml, oak-node/exports.sh, oak-node/umbrel-app.yml
Oak Node
https://oak-node.net/doc/tip/www/static/oak-logo.svg
---
Looking forward to your feedback. Thanks!
=> App submission: Oak Node

lndboss/.bosgui/config.json, lndboss/.bosgui/umbrel/credentials.json, lndboss/docker-compose.yml, lndboss/exports.sh, lndboss/umbrel-app.yml
LndBoss
https://svgshare.com/s/iwg
...
...
=> App Submission - lndboss

btcpay-server/docker-compose.yml, btcpay-server/umbrel-app.yml
- feat: update btcpay-server app to v1.6.3
- lint
- feat: bump version and add release notes
=> feat: update btcpay-server app to v1.6.3

squeakroad/docker-compose.yml, squeakroad/umbrel-app.yml
A few small bug fixes in Squeak Road app:
- https://github.com/yzernik/squeakroad/releases/tag/v0.1.10
- https://github.com/yzernik/squeakroad/releases/tag/v0.1.11
=> Update squeak road app to v0.1.14

bitcoin/docker-compose.yml, bitcoin/exports.sh, bitcoin/torrc.template, bitcoin/umbrel-app.yml
Release notes: https://github.com/bitcoin/bitcoin/blob/dd62721ba9c154685169588e356315d0787fdf7d/doc/release-notes/release-notes-23.0.md
This PR also includes a bugfix to send P2P traffic from Tor to bitcoind's specific Tor port
Credits to @kroese for submitting the original PR (https://github.com/getumbrel/umbrel-apps/pull/15) to address the Tor port bug
=> Update Bitcoin to v23

oak-node/docker-compose.yml, oak-node/umbrel-app.yml
Changes include:
- added a section for Nostr PoW Notes
- added schedule examples in the Scheduled Payments view
- added a Feedback via Lightning page
Tested in a VM with the latest Umbrel.
=> Bump Oak Node to v0.3.4

itchysats/docker-compose.yml, itchysats/umbrel-app.yml
Changelog for details: https://github.com/itchysats/itchysats/releases/tag/0.5.5
=> Upgrade ItchySats to `0.5.5`

thunderhub/docker-compose.yml, thunderhub/umbrel-app.yml
This PR replaces https://github.com/getumbrel/umbrel/pull/1213
=> Update Thunderhub to v0.13.15

lightning-terminal/docker-compose.yml, lightning-terminal/umbrel-app.yml
https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.7.1-alpha
Hey Y'all :) I come in peace with a new Litd release. There will be another release coming in the next week or so containing an LND bump (along with a loop bump too I think).
=> lightning-terminal: bump version to v0.7.1-alpha

itchysats/docker-compose.yml, itchysats/umbrel-app.yml
Changelog `0.6.0`: https://github.com/itchysats/itchysats/releases/tag/0.6.0
=> Upgrade ItchySats to `0.6.0`

itchysats/docker-compose.yml, itchysats/umbrel-app.yml
https://github.com/getumbrel/umbrel-apps/pull/132 merged super fast ❤️🚀
When testing on Umbrel we noticed a minor UI bug and fixed some log issues. 
Quick patch release `0.6.1`, for details see:
https://github.com/itchysats/itchysats/releases/tag/0.6.1
I kept the release notes for `0.6.0` in the release notes for `0.6.1` so users get informed about the new feature and dropping legacy support :)
=> Upgrade ItchySats to `0.6.1`

lndboss/docker-compose.yml, lndboss/umbrel-app.yml
Update LndBoss to v2.0.1
https://github.com/niteshbalusu11/lndboss/blob/master/CHANGELOG.md
=> Update LndBoss to v2.0.1

pi-hole/docker-compose.yml, pi-hole/umbrel-app.yml
getumbrel/umbrel-apps/issues/142  Docker Tag 2022.09.2
=> Upgrade Pi-Hole to 2022.09.2

tailscale/docker-compose.yml, tailscale/umbrel-app.yml
fixed a lot of bugs since the last update.
=> Update Tailscale to v1.30.1

krystal-bull/docker-compose.yml, krystal-bull/umbrel-app.yml
Upgrade Krystal Bull to the 1.9.4 release of bitcoin-s
https://github.com/bitcoin-s/bitcoin-s/releases/tag/1.9.4
=> 2022 09 14 krystalbull update

suredbits-wallet/docker-compose.yml, suredbits-wallet/umbrel-app.yml
Updates to the suredbits wallet to the 1.9.4 release:
https://github.com/bitcoin-s/bitcoin-s/releases/tag/1.9.4
=> 2022 09 10 suredbits wallet update

woofbot/docker-compose.yml, woofbot/umbrel-app.yml
Fixed a critical bug regarding watching addresses: https://github.com/woofbotapp/woofbotapp/issues/17
New feature - watching mempool becoming clear: https://github.com/woofbotapp/woofbotapp/issues/7
Minor UX changes.
Tested on my Raspberry Pi.
P.S.
The app is currently categorized as "Finance". It does allows watching price changes (via the CoinGecko api), but that's just one of its features - and all the others are unrelated to finance. I think "Automation" is a better category, because the app sends automatic telegram notifications for user-defined events.
=> Update WoofBot to v0.3.0

specter-desktop/docker-compose.yml, specter-desktop/umbrel-app.yml
Updated specter desktop docker image to v1.13.0
=> Update specter-desktop app to v1.13.0

robosats/docker-compose.yml, robosats/umbrel-app.yml
This is the first alpha available for robosats after the MVP version.
=> Update robosats to v0.2.0-alpha

file-browser/docker-compose.yml, file-browser/exports.sh, file-browser/umbrel-app.yml
This PR adds the File Browser app to help browse and manage the files you download on your Umbrel.
=> App Submission: File Browser

lnbits/docker-compose.yml, lnbits/umbrel-app.yml
- lnbits: update app to 0.9.4
- lnbits: update registry
=> lnbits: update app to 0.9.4

thunderhub/docker-compose.yml, thunderhub/umbrel-app.yml
=> Update Thunderhub to v0.13.16

pi-hole/docker-compose.yml, pi-hole/umbrel-app.yml
Release notes https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.09.4
@nevets963  hopefully this is good and i think you can edits it .
=> Update Pi-hole to 2022.09.4

woofbot/docker-compose.yml, woofbot/umbrel-app.yml
Some UX changes and a bug fix mentioned in the release notes.
Tested on a Raspberry Pi 4.
=> Update WoofBot to v0.4.0

core-lightning-rtl/docker-compose.yml, core-lightning-rtl/umbrel-app.yml, core-lightning/docker-compose.yml, core-lightning/umbrel-app.yml
=> RTL Update on CLN

suredbits-wallet/docker-compose.yml, suredbits-wallet/umbrel-app.yml
update suredbits-wallet to the 1.9.5 release:
- https://github.com/bitcoin-s/bitcoin-s/releases/1.9.5
- https://hub.docker.com/layers/bitcoinscala/bitcoin-s-server/1.9.5/images/sha256-21bc4c6352ce3bd47c6bf23e0cab04e6666530e6f265d682f3e9be9575deb839?context=explore
- https://hub.docker.com/layers/bitcoinscala/wallet-server-ui/1.9.5/images/sha256-e4252a1c1c54a76e55825711ebd4f7184af6a1475a659d1cfd3c1052ff61df78?context=explore
=> Updated Suredbits Wallet to 1.9.5

krystal-bull/docker-compose.yml, krystal-bull/umbrel-app.yml
Update Krystal Bull to 1.9.5
- https://github.com/bitcoin-s/bitcoin-s/releases/1.9.5
- https://hub.docker.com/layers/bitcoinscala/bitcoin-s-oracle-server/1.9.5/images/sha256-c363e13143050784dbf02ef08cd437817ec77b9806e77e15dcc1a31176a4249b?context=explore
- https://hub.docker.com/layers/bitcoinscala/oracle-server-ui/1.9.5/images/sha256-a9f9f8f8f9a4509ae2fad1c84d8f9e9da88b8b517ee0718a5a35a5753464abcf?context=explore
=> Update Krystal Bull to v1.9.5

lightning/docker-compose.yml, lightning/umbrel-app.yml
Fixes bug that causes lnd to crash on startup.
=> Update lnd to 0.15.2-beta

pi-hole/docker-compose.yml, pi-hole/umbrel-app.yml
Release notes https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.10
=> Update Pi-hole to 2022.10.10

calibre-web/docker-compose.yml, calibre-web/umbrel-app.yml
**GitHub Release:** https://github.com/linuxserver/docker-calibre-web/releases
**DockerHub Release:** https://hub.docker.com/layers/linuxserver/calibre-web/0.6.19/images/sha256-9a21e834059de2f0b730e6368e21119c6fc720f0d912a8522a96f6e041118444?context=explore
=> [App Update] Calibre Web

tallycoin-connect/docker-compose.yml, tallycoin-connect/umbrel-app.yml
Updated repo location and version bump.
Updated details for new website address, app description.
=> Tallycoin Connect update

suredbits-wallet/docker-compose.yml, suredbits-wallet/umbrel-app.yml
- https://hub.docker.com/layers/bitcoinscala/wallet-server-ui/1.9.6/images/sha256-d10423c3023b67210eb45a3a57c1c64de3c65ab018d7e4e4e59fdd837fa17f5c?context=explore
- https://hub.docker.com/layers/bitcoinscala/bitcoin-s-server/1.9.6/images/sha256-ed20159cafe2c2dfb7aaa3c4f664c2cd9d96aefcb02ba61810789c719bc7e7c9?context=explore
=> Update suredbits-wallet to v1.9.6

lndboss/docker-compose.yml, lndboss/umbrel-app.yml
Update LndBoss to v2.9.0, contains an important bug fix
=> Update LndBoss to v2.9.2

btcpay-server/docker-compose.yml, btcpay-server/umbrel-app.yml
This PR updates BTCPayServer to version 1.6.12.
=> Update BTCPayServer to 1.6.12

electrs/docker-compose.yml, electrs/umbrel-app.yml
=> Update Electrs to v0.9.9

tailscale/docker-compose.yml, tailscale/exports.sh, tailscale/umbrel-app.yml
This PR also adds makes the `exports.sh` quiet.
=> Update Tailscale to v1.33.158

rotki/docker-compose.yml, rotki/exports.sh, rotki/umbrel-app.yml
Rotki
https://svgshare.com/i/nrs.svg
=> App Submission: Rotki (Open-Source Crypto Portfolio Tracker)

libre-office/docker-compose.yml, libre-office/umbrel-app.yml, libreoffice/docker-compose.yml, libreoffice/umbrel-app.yml
...
https://svgshare.com/i/nav.svg
...
...
=> App Submission: LibreOffice

sphinx-relay/docker-compose.yml, sphinx-relay/umbrel-app.yml
Newest relay version update
https://github.com/stakwork/sphinx-relay/releases/tag/v2.2.12
=> Update sphinx-relay to v2.2.12

suredbits-wallet/docker-compose.yml, suredbits-wallet/umbrel-app.yml
Update to 1.9.7 of bitcoin-s: https://github.com/bitcoin-s/bitcoin-s/releases/tag/1.9.7
=> 2022 11 04 update suredbits wallet

krystal-bull/docker-compose.yml, krystal-bull/umbrel-app.yml
Update to 1.9.7 of bitcoin-s: https://github.com/bitcoin-s/bitcoin-s/releases/tag/1.9.7
=> Update krystal bull to 1.9.7

trilium-notes/docker-compose.yml, trilium-notes/umbrel-app.yml
=> Whitelist /api in App Proxy for Trilium Notes

pi-hole/docker-compose.yml, pi-hole/umbrel-app.yml
=> Pihole 2022.11.1 with FTL 5.19.2

torq/data/passwd, torq/docker-compose.yml, torq/exports.sh, torq/umbrel-app.yml
torq
Fixes #209 
https://svgshare.com/i/nyJ.svg
I've tried to use the dev environment but it asked me to install Pro or Business of Parallels so I stopped
=> App Submission: Torq (https://github.com/lncapital/torq)

core-lightning-rtl/docker-compose.yml, core-lightning-rtl/umbrel-app.yml
=> RTL on CLN v0.13.2

ride-the-lightning/docker-compose.yml, ride-the-lightning/umbrel-app.yml
=> RTL on LND v0.13.2

invidious/docker-compose.yml, invidious/umbrel-app.yml
Update Invidious to 2022.12.02-5160d8b
=> Update Invidious to 2022.11.22-5160d8b

lightning/docker-compose.yml, lightning/umbrel-app.yml
Tested on `arm64` and `amd64` using real sats.
=> Update LND to 0.15.5-beta

woofbot/docker-compose.yml, woofbot/umbrel-app.yml
See release notes.
Tested on a Raspberry Pi 4.
=> Update WoofBot to v0.4.6

torq/docker-compose.yml, torq/umbrel-app.yml
Tested upgrade on real raspberry pi.
Also cleaned up some empty line spaces.
=> Upgrade torq to v0.15.2

snowflake/docker-compose.yml, snowflake/umbrel-app.yml
=> Update Snowflake to v2.4.1

wikijs/docker-compose.yml, wikijs/umbrel-app.yml
...
https://github.com/IMPranshu/svg-logo/blob/main/wiki.svg
...
...
=> App Submission: WikiJS

snapdrop/docker-compose.yml, snapdrop/umbrel-app.yml
...
https://github.com/IMPranshu/svg-logo/blob/main/snapdrop.svg
...
...
=> App Submission: Snapdrop

remmina/docker-compose.yml, remmina/umbrel-app.yml
...
https://github.com/IMPranshu/svg-logo/blob/main/Remmina.svg
...
...
=> App Submission: Remmina

n8n/docker-compose.yml, n8n/exports.sh, n8n/umbrel-app.yml
...
https://github.com/IMPranshu/svg-logo/blob/main/n8n.svg
...
...
=> App Submission: N8N

firefox/docker-compose.yml, firefox/umbrel-app.yml
...
https://github.com/IMPranshu/svg-logo/blob/main/firefox-logo.svg
...
...
=> App Submission: Firefox Browser

pi-hole/docker-compose.yml, pi-hole/umbrel-app.yml
full changelog here https://github.com/pi-hole/docker-pi-hole/releases
=> Pihole to v5.18

urbit/docker-compose.yml, urbit/umbrel-app.yml
Update to use the official urbit bianries. This will allow users to autoupdate
=> Update Urbit to v1.15.0

core-lightning/docker-compose.yml, core-lightning/umbrel-app.yml
Tested using Ride The Lightning (Core Lightning).
=> Update Core Lightning to v22.11.1

woofbot/docker-compose.yml, woofbot/hooks/pre-start, woofbot/umbrel-app.yml
Tested on my raspberry pi.
This is a minor issue for those who update instead of uninstalling and reinstalling:
https://github.com/getumbrel/umbrel-apps/issues/346
(Minor issue, those logs are only needed for debugging purposes).
=> Update WoofBot to v0.5.2

tailscale/docker-compose.yml, tailscale/umbrel-app.yml
=> Update Tailscale to v1.34.2

lndg/docker-compose.yml, lndg/umbrel-app.yml
Updates LNDg to v1.5.0
https://github.com/cryptosharks131/lndg/releases/tag/v1.5.0
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/62295914?tag=v1.5.0
=> App Update: LNDg v1.5.0

itchysats/docker-compose.yml, itchysats/umbrel-app.yml
We renamed the itchysats organization to 10101.
=> Update itchsyats organisation to 10101

lndboss/docker-compose.yml, lndboss/umbrel-app.yml
Bumps lndboss version to v2.16.0.
Change log: https://github.com/niteshbalusu11/lndboss/blob/master/CHANGELOG.md
=> Update LndBoss to v2.16.0

lnmarkets/docker-compose.yml, lnmarkets/umbrel-app.yml
Patchnote: [v1.3.0](https://github.com/ln-markets/umbrel/releases/tag/v1.3.0)
Tested on arm64 !
=> Update LN Markets to v1.3.0

firefly-iii/docker-compose.yml, firefly-iii/exports.sh, firefly-iii/umbrel-app.yml
A free and open source personal finance manager
App icon and gallery assets merged here: https://github.com/getumbrel/umbrel-apps-gallery/pull/31
=> Firefly III

torq/docker-compose.yml, torq/umbrel-app.yml
More features and bug fixes!
Tested on a real raspberry pi.
Many thanks for your consideration
=> Bump Torq to v0.17.3

uptime-kuma/docker-compose.yml, uptime-kuma/umbrel-app.yml
This update fixes a knex.js security vulnerability along with differents fixes and new features. More information below.
https://github.com/louislam/uptime-kuma/releases
https://github.com/advisories/GHSA-4jv9-3563-23j3
=> Update UptimeKuma to v.1.19.6 (Critical Security Patch)

n8n/docker-compose.yml, n8n/umbrel-app.yml
Updates n8n docker image
https://docs.n8n.io/reference/release-notes/#n8n02120
=> Updates n8n to 0.212.0

circuitbreaker/docker-compose.yml, circuitbreaker/umbrel-app.yml
[![image](https://user-images.githubusercontent.com/433270/216438373-6cc82cc0-2a32-4c2e-9ba2-f9b92c6de123.png)](https://svgur.com/s/q0r)
[https://svgur.com/s/q0r](https://svgur.com/s/q0r)
=> App submission: Circuit Breaker

lnbits/docker-compose.yml, lnbits/umbrel-app.yml
suggesting update of lnbits to 0.9.5.3
=> Update LNbits to 0.9.7

sphinx-relay/docker-compose.yml, sphinx-relay/umbrel-app.yml
=> Update Sphinx Relay to v2.2.13

lndg/docker-compose.yml, lndg/umbrel-app.yml
Updates LNDg to v1.5.1
https://github.com/cryptosharks131/lndg/releases/tag/v1.5.1
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/67783129?tag=v1.5.1
=> Update LNDg to v1.5.1

rotki/docker-compose.yml, rotki/umbrel-app.yml
🫡
Edit: forgot to mention, tested on AMD VM 😉
=> Update rotki to 1.27.0

woofbot/docker-compose.yml, woofbot/umbrel-app.yml
Tested on my raspberry pi.
P.S.
It would be nice to update the dashboard screenshots (but not a big deal).
=> Update WoofBot to v0.6.0

pi-hole/docker-compose.yml, pi-hole/umbrel-app.yml
=> Update pihole v5.18.4

lndboss/docker-compose.yml, lndboss/umbrel-app.yml
Updated LndBoss to v2.17.1
https://github.com/niteshbalusu11/lndboss/blob/master/CHANGELOG.md
Signed-off-by: Nitesh Balusu <niteshbalusu@icloud.com>
=> Update LndBoss to 2.17.1

torq/docker-compose.yml, torq/umbrel-app.yml
Bug fix - enable data streams by default
Tested on real Rasberry PI
=> Update Torq to v0.18.19

jellyfin/docker-compose.yml, jellyfin/umbrel-app.yml
Tested on AMD VM
Should fix #424 (don't have the required setup to confirm)
=> Update Jellyfin to 10.8.9

btcpay-server/docker-compose.yml, btcpay-server/umbrel-app.yml
I believe I formatted everything correctly for umbrel-app.yml and hopefully there are no other issues :sweat_smile:
=> Update BTCPay Server to 1.7.12

lndboss/docker-compose.yml, lndboss/umbrel-app.yml
Signed-off-by: Nitesh Balusu <niteshbalusu@icloud.com>
- Fixed a bug where old config is being used for auto fees updates.
https://github.com/niteshbalusu11/lndboss/blob/master/CHANGELOG.md
=> Update LndBoss to 2.17.3

robosats/docker-compose.yml, robosats/umbrel-app.yml
Update RoboSats to latest v0.4.0-alpha
Tested only on `amd64`
=> Update RoboSats to v0.4.0-alpha

woofbot/docker-compose.yml, woofbot/umbrel-app.yml
Renamed app to "WoofBot without Lightning"
Here's the new logo:
=> Update WoofBot to v0.7.0 + App Rename

esphome/docker-compose.yml, esphome/umbrel-app.yml
update esphome version. fix platformio version error
=> Update esphome to 2023.2.4

woofbot-lnd/docker-compose.yml, woofbot-lnd/umbrel-app.yml, woofbot/docker-compose.yml, woofbot/umbrel-app.yml
update both woofbot and woofbot-lnd.
They use the same docker image, with different permissions (configured in the .yml files).
Tested on my Raspberry Pi.
=> Update WoofBot to v0.7.1

snort/docker-compose.yml, snort/umbrel-app.yml
Snort
https://void.cat/d/QzA8i39F3Tqr986ouuLDKL
https://void.cat/d/EL7xnxC4Fab123kUVB5w1e
https://void.cat/d/DenpDVYyWhvBKDQhzbMGTd
https://void.cat/d/RxUH2Ve3KKU6BspnCQF3xP
The same images but 2x size:
https://void.cat/d/WP56AV1Zz3qg3RKLbQ4tSd
https://void.cat/d/Ehq6hGmTSEs2RTJLBmv9M7
https://void.cat/d/4iS5jssVAL9sf1bsLxALUX
=> App Submission: Snort

invoice-ninja/config/nginx.conf, invoice-ninja/docker-compose.yml, invoice-ninja/hooks/pre-start, invoice-ninja/umbrel-app.yml
1 strange quirk is; the languages and currenies are not loaded immediately when Invoice Ninja is installed. It can take a few minutes for those to become ready. Issue reported here: https://github.com/invoiceninja/invoiceninja/issues/8075
=> App Submission: Invoice Ninja 5

plex/docker-compose.yml, plex/umbrel-app.yml
=> Update Plex to latest version

torq/docker-compose.yml, torq/umbrel-app.yml
Big upgrade to Torq!
Tested on a real Raspberry Pi.
Our pictures are now a bit old and not representative of the new features. May we please update them? New screenshots:
=> Update Torq to v0.19.1

torq/docker-compose.yml, torq/umbrel-app.yml
Small update to Torq
If LND goes down for any reason Torq wasn't reconnecting so we thought it was probably worth the release
Tested on real raspberry pi
=> Update Torq to v0.19.2

chatbot-ui/docker-compose.yml, chatbot-ui/umbrel-app.yml
ChatBot UI is an advanced chatbot kit for OpenAI's chat models aiming to mimic ChatGPT's interface and functionality.
https://github.com/mckaywrigley/chatbot-ui
Simply add your OpenAI API key and start chatting!
This version of ChatBot UI supports both GPT-3.5 and GPT-4 models. Conversations are stored locally within your browser. You can export and import conversations to safeguard against data loss.
=> App Submission: ChatBot UI

circuitbreaker/docker-compose.yml, circuitbreaker/umbrel-app.yml
=> Update circuitbreaker to v0.4.3

snort/docker-compose.yml, snort/umbrel-app.yml
=> Update Snort to v0.1.6

chatbot-ui/docker-compose.yml, chatbot-ui/umbrel-app.yml
Brings chatbot ui in line with this commit: https://github.com/mckaywrigley/chatbot-ui/commit/e8150e719548ce107f0cd45efbaae02746a9315f
=> Update Chatbot UI to 2023.04.05

woofbot-lnd/docker-compose.yml, woofbot-lnd/umbrel-app.yml, woofbot/docker-compose.yml, woofbot/umbrel-app.yml
update both woofbot and woofbot-lnd -
they use the same image, with different
permissions.
Tested on my Raspberry Pi.
=> update WoofBot to v0.8.2

ride-the-lightning/docker-compose.yml, ride-the-lightning/umbrel-app.yml
https://github.com/BoltzExchange/boltz-lnd/releases/tag/v1.2.7
=> Update boltz-lnd in RTL to v1.2.7

elements/docker-compose.yml, elements/umbrel-app.yml
This also picks a more recent block for assume valid.
=> Bump Elements to 22.1.1

woofbot-lnd/docker-compose.yml, woofbot-lnd/umbrel-app.yml, woofbot/docker-compose.yml, woofbot/umbrel-app.yml
=> update WoofBot to 0.9.0

snort/docker-compose.yml, snort/umbrel-app.yml
=> Update: Snort

gitea/docker-compose.yml, gitea/umbrel-app.yml
Tested on Ubuntu VM with simple Gitea setup.
Closes https://github.com/getumbrel/umbrel-apps/issues/503
=> Update Gitea to 1.19.1

lightning/docker-compose.yml, lightning/umbrel-app.yml
=> Update LND to v0.16.2-beta

uptime-kuma/docker-compose.yml, uptime-kuma/umbrel-app.yml
Not able to currently test it, so opening it as "Draft" for now.
=> Update Uptime Kuma to 1.21.1

pi-hole/docker-compose.yml, pi-hole/umbrel-app.yml
Everything is in the title. I also linked the changelog rather than copy/pasting it because it has a lot of links, it's easier this way I think
=> Update Pi-Hole to latest

woofbot-lnd/docker-compose.yml, woofbot-lnd/umbrel-app.yml, woofbot/docker-compose.yml, woofbot/umbrel-app.yml
Tested on my Raspberry Pi.
Updated the [lightning package](https://www.npmjs.com/package/lightning) dependency to fix a bug with the `/about` command. Also fixed a few typos.
=> update WoofBot to 0.9.1

firefly-iii/docker-compose.yml, firefly-iii/umbrel-app.yml
=> Update Firefly iii to version 6.0.9

transmission/docker-compose.yml, transmission/umbrel-app.yml
Dunno why it's v3, I just bumped to v4 and everything works just fine.
=> Update transmission to 4.0.3

sphinx-relay/docker-compose.yml, sphinx-relay/umbrel-app.yml
the current sphinx-relay looks like it's broken, user reported and also mine can't currently connect - seems to do with newest LND version 0.16.2-beta
=> Update Sphinx Relay to v2.3.2

overseerr/docker-compose.yml, overseerr/umbrel-app.yml
https://overseerr.dev/
https://github.com/sct/overseerr
Overseerr is a request management and media discovery tool built to work with your existing Plex ecosystem.
=> App Submission - Overseerr

librespeed/docker-compose.yml, librespeed/umbrel-app.yml
https://librespeed.org/
https://github.com/librespeed/speedtest
Free and open source speedtest. Measure internet speeds between your devices and your Umbrel.
=> App Submission - LibreSpeed

bazarr/docker-compose.yml, bazarr/umbrel-app.yml
https://www.bazarr.media/
https://github.com/morpheus65535/bazarr
Bazarr is a companion application to Sonarr and Radarr that manages and downloads subtitles based on your requirements. You define your preferences by TV show or movie and Bazarr takes care of everything for you.
=> App Submission - Bazarr

torq/docker-compose.yml, torq/umbrel-app.yml
Torq can now we used with CLN! It is still an experimental version
Bug fixes and improvements
Tested on real Rasberry PI
=> Update Torq to v0.22.4

bitcoin/docker-compose.yml, bitcoin/umbrel-app.yml
This PR updates the bitcoind image to the most recent 25.0 version
=> Update Bitcoin Node to Core v25.0

lightning/docker-compose.yml, lightning/umbrel-app.yml
=> Update LND to v0.16.3-beta

woofbot-lnd/docker-compose.yml, woofbot-lnd/umbrel-app.yml, woofbot/docker-compose.yml, woofbot/umbrel-app.yml
Just updating dependencies which broke a little with LND v0.16.3-beta.
Tested on my Raspberry-Pi.
=> Update WoofBot to 0.9.7

immich/docker-compose.yml, immich/umbrel-app.yml
https://github.com/immich-app/immich/releases/tag/v1.61.0
=> Update Immich to v1.61.0

lndboss/docker-compose.yml, lndboss/umbrel-app.yml
Signed-off-by: Nitesh Balusu <84944042+niteshbalusu11@users.noreply.github.com>
Bumping LndBoss to v.2.19.1
=> Bump lndboss to v2.19.1

mempool/umbrel-app.yml
Add mining dashboard, add gallery image, add language note, and remove TV view.
This PR adds a reference to a fourth image, which is added in https://github.com/getumbrel/umbrel-apps-gallery/pull/40, so that needs to be merged first.
=> Update mempool app description

oak-node/docker-compose.yml, oak-node/umbrel-app.yml
Tested on:
- amd64 (VM)
- arm64 (raspi)
=> Bump Oak Node to v0.3.7

chatbot-ui/docker-compose.yml, chatbot-ui/umbrel-app.yml
Tested on x86 and arm64. Up-to-date with https://github.com/mckaywrigley/chatbot-ui/commit/fa3f6e93bbe0d1ff9f208ddefae6fc7dfb738dc7.
=> Update chatbot-ui to 2023.04.20

calibre-web/docker-compose.yml, calibre-web/umbrel-app.yml
Tested on ARM64 (Ubuntu Multipass VM)
=> Update Calibre-Web to 0.6.20

lnmarkets/docker-compose.yml, lnmarkets/umbrel-app.yml
Hey,
We updated our app with removing some feature to allow us to break thing in production :)
A full revamp may come at a later time.
Here is a screenshot 
Best.
=> Update lnmarkets to v2.0.0

lndg/docker-compose.yml, lndg/umbrel-app.yml
Updates LNDg to v1.7.0
https://github.com/cryptosharks131/lndg/releases/tag/v1.7.0
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/106291333?tag=v1.7.0
=> Update LNDg to v1.7.0

photoprism/docker-compose.yml, photoprism/umbrel-app.yml
Tested on ARM65 (Ubuntu Multipass VM)
Closes https://github.com/getumbrel/umbrel-apps/issues/559
=> Update Photoprism to 230615

lightning/docker-compose.yml, lightning/umbrel-app.yml
This release is a minor release to fix a memory leak inadvertently introduced by optimizations to the mempool scanning logic.
=> Update LND to 0.16.4-beta

mempool/umbrel-app.yml
Simplify, simplify, simplify.
Tagline on main repo also updated with https://github.com/getumbrel/umbrel/pull/1665.
=> Update mempool description+tagline (v2.5, mid-2023)

ghostfolio/docker-compose.yml, ghostfolio/umbrel-app.yml
Update ghostfolio to its latest release
=> chore: update ghostfolio to 1.286.0

rotki/docker-compose.yml, rotki/umbrel-app.yml
Tested on ARM64 VM (Ubuntu Multipass) ✅
=> Update rotki to v1.29.0

btc-rpc-explorer/docker-compose.yml, btc-rpc-explorer/umbrel-app.yml
There's been a new release of this app by the author:
https://github.com/janoside/btc-rpc-explorer/releases/tag/v3.4.0
=> Update btc-rpc-explorer app to 3.4.0

nostr-relay/docker-compose.yml, nostr-relay/hooks/pre-start, nostr-relay/umbrel-app.yml
https://github.com/getumbrel/umbrel-nostr-relay/releases/tag/v1.1.0
=> Update Nostr Realy to v1.1.0

lnbits/docker-compose.yml, lnbits/umbrel-app.yml
Lnbits extension is few versions behind now.
This is to update lnbits to the latest version (0.10.9)
=> Update lnbits to 0.10.9

pi-hole/docker-compose.yml, pi-hole/umbrel-app.yml
https://github.com/pi-hole/docker-pi-hole/releases/tag/2023.05.2
Not tested
=> update pi hole v2023.05.2

llama-gpt/docker-compose.yml, llama-gpt/hooks/pre-install, llama-gpt/hooks/pre-start, llama-gpt/umbrel-app.yml
https://github.com/getumbrel/llama-gpt
=> Add LlamaGPT

octoprint/docker-compose.yml, octoprint/umbrel-app.yml
OctoPrint
https://octoprint.org/assets/img/logo.png
=> App Submission: OctoPrint

homebox/docker-compose.yml, homebox/umbrel-app.yml
https://hay-kot.github.io/homebox/assets/img/lilbox.svg
=> App Submission : Homebox

freshrss/docker-compose.yml, freshrss/umbrel-app.yml
...
https://github.com/IMPranshu/svg-logo/blob/main/logo.svg
...
...
=> App Submission: Freshrss

tautulli/docker-compose.yml, tautulli/umbrel-app.yml
...
https://svgshare.com/i/vVE.svg
...
...
=> App Submission: Tautulli

plex/docker-compose.yml, plex/umbrel-app.yml
Updates Plex to version 1.32.5.7349.
=> Update Plex to v1.32.5.7349

immich/docker-compose.yml, immich/umbrel-app.yml
v1.73.0
Please make sure the mobile app and the server are on the same version to see the album displayed on the mobile app.
Welcome to release v1.73.0 of Immich. There are many improvements in this version that you will like. Some of the key highlights include:
- Optimized viewing experience for the Album page.
- Added option to configure the generated thumbnail resolution.
- Added option to toggle visibility of the memory reel.
- Better quality for thumbnails and generated videos.
Change logs - https://github.com/immich-app/immich/releases/tag/v1.73.0
=> immich update v1.73.0

rotki/docker-compose.yml, rotki/umbrel-app.yml
✅  Tested on Ubuntu Multipass on MacOS
=> Update rotki 1.30.0

immich/docker-compose.yml, immich/umbrel-app.yml
Updated image to v1.74.0 for
`immich-server` (the same `immich-server` tag is used under `server` and `microservices`)
`immich-machine-learning`
`immich-web`
`immich-proxy`
=> Update Immich to v1.74.0

heimdall/docker-compose.yml, heimdall/umbrel-app.yml
Updated Heimdall image from v2.5.5 to v2.5.6
=> Update Heimdall to v2.5.6

thunderhub/docker-compose.yml, thunderhub/umbrel-app.yml
Update ThunderHub image from v0.13.19 to v0.13.21
=> Update ThunderHub to v0.13.21

syncthing/docker-compose.yml, syncthing/umbrel-app.yml
Update the `Syncthing` image from `v1.23.2` to `v1.23.7`
=> Update Syncthing to  v1.23.7

uptime-kuma/docker-compose.yml, uptime-kuma/umbrel-app.yml
Updated image of Uptime Kuma from v1.21.2 to v1.23.0
=> Update Uptime Kuma to v1.23.0

rotki/docker-compose.yml, rotki/umbrel-app.yml
✅ Tested on Ubuntu Multipass on ARM
=> Update rotki 1.30.1

btcpay-server/docker-compose.yml, btcpay-server/umbrel-app.yml
Update btcpayserver to 1.11.4 and nbxplorer 2.3.66.
=> Update BTCPay Server to v1.11.4

immich/docker-compose.yml, immich/umbrel-app.yml
Updated image to v1.76.1 for
- `immich-server` (the same `immich-server` tag is used under `server` and `microservices)`
- `immich-machine-learning`
- `immich-web`
- `immich-proxy`
=> Update Immich to v1.77

thunderhub/docker-compose.yml, thunderhub/umbrel-app.yml
Update ThunderHub image from v0.13.21 to v0.13.23
=> Update Thunderhub to v0.13.23

woofbot-lnd/docker-compose.yml, woofbot-lnd/umbrel-app.yml, woofbot/docker-compose.yml, woofbot/umbrel-app.yml
=> Update WoofBot to v0.9.8

robosats/docker-compose.yml, robosats/umbrel-app.yml
https://github.com/RoboSats/robosats/releases/tag/v0.5.2-alpha
Updates robosats to v0.5.2. 
Not tested!
=> Update Robosats to v0.5.2

oak-node/docker-compose.yml, oak-node/umbrel-app.yml
Tested on:
- amd64 (VM)
- arm64 (raspi)
=> Bump Oak Node to v0.3.8

jellyfin/docker-compose.yml, jellyfin/umbrel-app.yml
Small update by Jellyfin providing bug fixes and minor improvements.
=> update Jellyfin to 10.8.11

torq/docker-compose.yml, torq/umbrel-app.yml
* Package upgrades
* Bugfixes:
* Fixed Incorrect ordering of locked columns in table views
* CLN payment status was stuck or not showing correct status
=> Update Torq to v1.1.5

n8n/docker-compose.yml, n8n/umbrel-app.yml
=> update n8n to v1.9.3

chatpad-ai/docker-compose.yml, chatpad-ai/umbrel-app.yml
=> update chatpad-ai to e8240a

radarr/docker-compose.yml, radarr/umbrel-app.yml
=> update Radarr to 5.0.3

plex/docker-compose.yml, plex/umbrel-app.yml
=> update plex to 1.32.6

file-browser/docker-compose.yml, file-browser/umbrel-app.yml
=> update file browser to v2.25.0

ghostfolio/docker-compose.yml, ghostfolio/umbrel-app.yml
Update ghostfolio to its latest release
=> Update ghostfolio to 2.11.0

sabnzbd/docker-compose.yml, sabnzbd/umbrel-app.yml
=> App submission: Sabnzbd

lnbits/docker-compose.yml, lnbits/umbrel-app.yml
This update goes from 0.10.9 to 0.11.1 which includes:
-[0.11.0 Leo](https://github.com/lnbits/lnbits/releases/tag/0.11.0)
-[0.11.1 Leo](https://github.com/lnbits/lnbits/releases/tag/0.11.1)
Tested on:
=> Update lnbits to 0.11.1

audiobookshelf/docker-compose.yml, audiobookshelf/umbrel-app.yml
=> Update audiobookshelf to v2.5.0

btcpay-server/docker-compose.yml, btcpay-server/umbrel-app.yml
Tested on arm64 and x86(amd64)
=> Update btcpayserver to 1.11.7

calibre-web/docker-compose.yml, calibre-web/umbrel-app.yml
Tested on arm64 and x86(amd64)
=> Update calibre-web to v0.6.21

code-server/docker-compose.yml, code-server/umbrel-app.yml
=> Update code-server to v4.18.0

ride-the-lightning/docker-compose.yml, ride-the-lightning/umbrel-app.yml
=> Update RTL (LND) to v0.14.1-beta

file-browser/docker-compose.yml, file-browser/umbrel-app.yml
=> Update File Browser to v2.26.0

core-lightning-rtl/docker-compose.yml, core-lightning-rtl/umbrel-app.yml
=> Update RTL (Core Lightning) to v0.14.1-beta

firefly-iii/docker-compose.yml, firefly-iii/umbrel-app.yml
Tested on arm64 and x86(amd64)
=> Update firefly-iii to v6.0.30

firefox/docker-compose.yml, firefox/umbrel-app.yml
=> Update Firefox to 116.0.3

freshrss/docker-compose.yml, freshrss/umbrel-app.yml
=> Update FreshRSS to v1.22.1

snowflake/docker-compose.yml, snowflake/umbrel-app.yml
Release notes: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/releases
=> Update snowflake to v2.7.0

tautulli/docker-compose.yml, tautulli/umbrel-app.yml
Release notes: https://github.com/Tautulli/Tautulli/releases
=> Update tautulli to v2.13.2

lightning/docker-compose.yml, lightning/umbrel-app.yml
Hotfix release: https://github.com/lightningnetwork/lnd/releases/tag/v0.17.2-beta
=> Update Lightning Node to v0.17.2-beta

code-server/docker-compose.yml, code-server/umbrel-app.yml
Release notes: https://github.com/coder/code-server/releases
=> Update code-server to 4.19.1

ghostfolio/docker-compose.yml, ghostfolio/umbrel-app.yml
Release notes: https://github.com/ghostfolio/ghostfolio/releases
=> Update ghostfolio to 2.27.1

uptime-kuma/docker-compose.yml, uptime-kuma/umbrel-app.yml
Release notes: https://github.com/louislam/uptime-kuma/releases/tag/1.23.7
=> Update uptime-kuma to 1.23.7

transmission/docker-compose.yml, transmission/umbrel-app.yml
Release notes: https://github.com/transmission/transmission/releases/tag/4.0.4
=> Update transmission to 4.0.4

plex/docker-compose.yml, plex/umbrel-app.yml
Release notes: https://forums.plex.tv/t/plex-web/20528/430
=> Update plex to 1.32.8 (4.119.1)

lightning/docker-compose.yml, lightning/umbrel-app.yml
=> Update LND to 0.17.3-beta

immich/docker-compose.yml, immich/hooks/pre-start, immich/umbrel-app.yml
Need to replace sha256 to universal ones
=> Update immich to 1.91.3

autobrr/docker-compose.yml, autobrr/umbrel-app.yml
Release notes: https://github.com/autobrr/autobrr/releases
=> Update autobrr to 1.34.1

thunderhub/docker-compose.yml, thunderhub/umbrel-app.yml
Update performed manually locally. Data persisted after update.
=> Update Thunderhub  v0.13.23 --> v0.13.29

tailscale/docker-compose.yml, tailscale/umbrel-app.yml
Release notes: https://github.com/tailscale/tailscale/releases
=> Update tailscale to v1.56.1

bitcoin/docker-compose.yml, bitcoin/umbrel-app.yml
Release notes: https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-26.0.md
=> Update Bitcoin to 26.0

audiobookshelf/docker-compose.yml, audiobookshelf/umbrel-app.yml
Release notes: https://github.com/advplyr/audiobookshelf/releases
=> Update audiobookshelf to 2.7.1

nextcloud/docker-compose.yml, nextcloud/hooks/pre-start, nextcloud/umbrel-app.yml
Release notes: https://nextcloud.com/changelog/
Just a small patch update due to requests.
=> Update nextcloud to 28.0.1

vikunja/data/proxy/nginx.conf, vikunja/docker-compose.yml, vikunja/umbrel-app.yml
...
https://github.com/IMPranshu/svg-logo/blob/main/vikunja-logo.svg
...
...
=> App Submission: Vikunja

firefly-iii/docker-compose.yml, firefly-iii/umbrel-app.yml
=> Update firefly-iii to v6.1.6

autobrr/docker-compose.yml, autobrr/umbrel-app.yml
https://github.com/autobrr/autobrr/releases
Tested on:
=> Update autobrr to 1.36.0

nextcloud/docker-compose.yml, nextcloud/umbrel-app.yml
Release notes: https://nextcloud.com/changelog/
=> Update nextcloud to 28.0.2

lightning/docker-compose.yml, lightning/umbrel-app.yml
https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.17.4.md
=> Update lightning to 0.17.4-beta

home-assistant/docker-compose.yml, home-assistant/umbrel-app.yml
https://www.home-assistant.io/blog/2024/02/07/release-20242/
=> Update home-assistant to 2024.2.1

immich/docker-compose.yml, immich/umbrel-app.yml
https://github.com/immich-app/immich/releases
=> Update immich to v1.94.1

plex/docker-compose.yml, plex/umbrel-app.yml
https://www.videohelp.com/software/Plex
=> Update plex to 1.40.0

ghostfolio/docker-compose.yml, ghostfolio/umbrel-app.yml
https://github.com/ghostfolio/ghostfolio/releases
=> Update ghostfolio to 2.51.0

lnbits/docker-compose.yml, lnbits/umbrel-app.yml
Release notes: https://github.com/lnbits/lnbits/releases
=> Update LNBits to 0.12.1

readarr/docker-compose.yml, readarr/hooks/post-install, readarr/umbrel-app.yml
...
https://svgshare.com/i/vsy.svg
...
...
=> App Submission: Readarr

nostrudel/docker-compose.yml, nostrudel/umbrel-app.yml
https://raw.githubusercontent.com/hzrd149/umbrel-community-app-store/master/hzrd149-nostrudel/icon.svg
=> App Submission: noStrudel

watch-your-lan/docker-compose.yml, watch-your-lan/umbrel-app.yml
WatchYourLan
...
https://svgur.com/i/120w.svg
...
...
=> App Submission: WatchYourLan

seafile/docker-compose.yml, seafile/umbrel-app.yml
...
https://svgshare.com/i/vV3.svg
...
...
=> App Submission: Seafile

code-server/docker-compose.yml, code-server/umbrel-app.yml
https://github.com/coder/code-server/releases
=> Update code-server to 4.21.1

homebox/docker-compose.yml, homebox/umbrel-app.yml
https://github.com/hay-kot/homebox/releases
=> Update homebox to 0.10.3

public-pool/docker-compose.yml, public-pool/umbrel-app.yml
=> Update public pool

heimdall/docker-compose.yml, heimdall/umbrel-app.yml
Release notes: https://github.com/linuxserver/Heimdall/releases
=> Update heimdall to 2.6.1

ghostfolio/docker-compose.yml, ghostfolio/umbrel-app.yml
Release notes: https://github.com/ghostfolio/ghostfolio/releases
=> Update ghostfolio to 2.61.0

nextcloud/docker-compose.yml, nextcloud/umbrel-app.yml
Release notes: https://nextcloud.com/changelog/
=> Update nextcloud to 28.0.3

tailscale/docker-compose.yml, tailscale/umbrel-app.yml
Release notes: https://github.com/tailscale/tailscale/releases
=> Update tailscale to 1.62.0

databag/docker-compose.yml, databag/umbrel-app.yml
new databag version changelog:
- a smaller container size
- support of dark mode
- support of additional languages
- some guidance text on login screen for account creation
=> updated databag version

rotki/docker-compose.yml, rotki/umbrel-app.yml
Updating Rotki as it's a few versions behind and there's also a bug which is fixed in the latest version (reported via [rotki discord](https://discord.com/channels/657906918408585217/745172610240872508/1228798019030487140)).
=> Update rotki to v.1.32.2

plex/docker-compose.yml, plex/umbrel-app.yml
Fix: #1053 
1.40.0 -> 1.40.1
Haven't tested the update, sorry. It almost certainly works though
=> Updated Plex

databag/docker-compose.yml, databag/umbrel-app.yml
Normally my releases include more features, but this version of Go has resolved several security vulnerabilities.
=> updating databag container

affine/docker-compose.yml, affine/umbrel-app.yml
...
https://svgur.com/i/13qq.svg
...
...
=> App Submission: Affine

morphos/docker-compose.yml, morphos/umbrel-app.yml
Morphos Server
[Morphos icon](https://svgshare.com/s/14x5)
=> add morphos server

vikunja/docker-compose.yml, vikunja/umbrel-app.yml
Updates Vikunja to v0.22.1 and adds specific db host name.
=> Update Vikunja to v0.22.1

audiobookshelf/docker-compose.yml, audiobookshelf/umbrel-app.yml
Tested on Raspberry Pi 4 with UmbrelOS
=> Update ABS to 2.9.0

metube/docker-compose.yml, metube/umbrel-app.yml
Tested on x86 and arm64. Release notes and comparison from git commits.
=> Update Metube to 2024-05-02

memos/docker-compose.yml, memos/umbrel-app.yml
These apps are going to a a PITA to maintain... I should probably automate this.
Memos
Unfortunately this can't be made into an svg
https://www.usememos.com/logo.png
_We will help finalize these images before the app goes live in the Umbrel App Store._
=> Added memos

pocketbase/docker-compose.yml, pocketbase/umbrel-app.yml
PocketBase
Screenshots from the [official demo](https://pocketbase.io/demo/)
=> Add PocketBase

wireguard/docker-compose.yml, wireguard/umbrel-app.yml
=> Add WireGuard

databag/docker-compose.yml, databag/umbrel-app.yml
- Added support for Multi-Factor Authentication for admin and users
-- integration tested with freeOTP(+) and [online test site](https://www.token2.com/site/page/token2-totp-toolset-sha256-version)
=> Updated to databag version supporting MFA

n8n/docker-compose.yml, n8n/umbrel-app.yml
Tested in Umbrel OS 1.1.2 on Beelink EQ12 N100
=> update n8n from 1.18.1 to 1.44.1

home-assistant/docker-compose.yml, home-assistant/umbrel-app.yml
https://www.home-assistant.io/blog/2024/06/05/release-20246/
=> Update Home Assistant to  v2024.6

lightning-terminal/docker-compose.yml, lightning-terminal/umbrel-app.yml
Hi there, 
New release: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.13.0-alpha
=> lightning-terminal: update to LiT v0.13.0-alpha

immich/docker-compose.yml, immich/umbrel-app.yml
1.103.0 --> 1.105.1
https://github.com/immich-app/immich/releases
Tested on x86 and arm64
=> Update Immich to v1.105.1

myspeed/docker-compose.yml, myspeed/umbrel-app.yml
=> Add MySpeed

stirling-pdf/docker-compose.yml, stirling-pdf/umbrel-app.yml
=> Add Stirling PDF

autobrr/docker-compose.yml, autobrr/umbrel-app.yml
=> Update autobrr to 1.42.0

lightning/docker-compose.yml, lightning/umbrel-app.yml
Couldn't find any reference to anyone testing or merging this on the umbrel team. Is this update already in progress somewhere?
=> update lnd image to v0.18.0-beta

plex/docker-compose.yml, plex/umbrel-app.yml
=> Update Plex to v1.40.3

node-red/docker-compose.yml, node-red/umbrel-app.yml
Major milestone release: https://github.com/node-red/node-red/releases
Tested fresh install and update
=> Update Node-RED (Bitcoin) to v4.0.0

peerswap/docker-compose.yml, peerswap/umbrel-app.yml
Adds channel Auto Fee functionality plus various enhancements.
=> Update PeerSwap Web UI to v1.5.7

maybe/.env, maybe/docker-compose.yml, maybe/hooks/pre-install, maybe/umbrel-app.yml
Closes https://github.com/getumbrel/umbrel-apps/issues/1104
_We will help finalize these images before the app goes live in the Umbrel App Store._
=> App Submission: Maybe

maybe/docker-compose.yml, maybe/umbrel-app.yml
Left description as-is / didn't add release notes, as they still apply.
=> Update maybe to 0.1.0-alpha.9

immich/docker-compose.yml, immich/umbrel-app.yml
Notes:
- Ensure that your mobile app is compatible with this release of Immich.
- This release includes a security update for Node.js. It is strongly recommended to update.
- Watch out for changes related to Redis for Websocket state tracking and the new queue system for CLI processing.
=> Update Immich to v1.108.0

lightning-terminal/docker-compose.yml, lightning-terminal/umbrel-app.yml
Hey yall! here  with the v0.13.3-alpha release https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.13.3-alpha
=> lightning-terminal: update to v0.13.3-alpha

yucca/docker-compose.yml, yucca/hooks/pre-start, yucca/umbrel-app.yml
=> App submission: Yucca

ordinals/docker-compose.yml, ordinals/hooks/pre-start, ordinals/umbrel-app.yml
This is a major version update, which requires a full re-index of ord (handled by our pre-start script).
=> Update ordinals to version v0.20.0

peerswap/docker-compose.yml, peerswap/umbrel-app.yml
Bug fixes and improvements. See full changelog here: https://github.com/Impa10r/peerswap-web/blob/main/CHANGELOG.md
=> Update PeerSwap to v1.6.9

morphos/docker-compose.yml, morphos/umbrel-app.yml
Update morphos to v0.6.0 https://github.com/danvergara/morphos/releases/tag/v0.6.0
=> Update morphos to v0.6.0

homebridge/docker-compose.yml, homebridge/umbrel-app.yml
This is a pull request to update homebridge to version 2024-09-03. PR must be reviewed and tested before merging.
=> Update homebridge to 2024-09-03

lndg/docker-compose.yml, lndg/hooks/pre-start, lndg/umbrel-app.yml
Updates LNDg to v1.9.0
https://github.com/cryptosharks131/lndg/releases/tag/v1.9.0
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/278874650?tag=v1.9.0
=> Update LNDg to v1.9.0

lnbits/docker-compose.yml, lnbits/umbrel-app.yml
=> Update lnbits to v0.12.11

nginx-proxy-manager/docker-compose.yml, nginx-proxy-manager/umbrel-app.yml
Update Nginx Proxy Manager to v2.12.1
=> Update Nginx Proxy Manager to v2.12.1

robosats/docker-compose.yml, robosats/umbrel-app.yml
Simple version bump. Untested.
=> Bump RoboSats to v0.7.1-alpha

homebox/docker-compose.yml, homebox/umbrel-app.yml
Update HomeBox to an actively maintained fork and version v0.15.2
=> Update homebox to v0.15.2

grafana/docker-compose.yml, grafana/umbrel-app.yml
...
https://svgur.com/s/1BeX
- https://grafana.com/static/img/grafana/showcase_visualize.jpg
- https://grafana.com/media/products/cloud/grafana/grafana-dashboard-english.png
- https://grafana.com/media/products/cloud/grafana/grafana-kubernetes.jpg
- https://grafana.com/static/img/grafana/time_series_light_theme_sized.png
- https://grafana.com/static/img/grafana/stat_light_theme_sized.png
- https://grafana.com/static/img/grafana/gauge_light_theme_sized.png
=> App Submission: Grafana

mattermost/docker-compose.yml, mattermost/umbrel-app.yml
Mattermost
https://mattermost.com/wp-content/uploads/2024/06/mattermost-logomark.svg
https://mattermost.com/wp-content/uploads/2024/06/mattermost-home-hero.webp
https://mattermost.com/wp-content/uploads/2021/10/mattermost-platform-channels.webp
https://mattermost.com/wp-content/uploads/2021/10/mattermost-platform-playbooks.webp
https://mattermost.com/wp-content/uploads/2023/01/mattermost-platform-calls.webp
=> App Submission: Mattermost

libre-relay/docker-compose.yml, libre-relay/exports.sh, libre-relay/hooks/pre-start, libre-relay/scripts/rpcauth.py, libre-relay/torrc.template, libre-relay/umbrel-app.yml
App submission for Peter Todd.
https://github.com/petertodd/bitcoin/tree/libre-relay-v28.0
=> App Submission: Libre Relay

firefox/docker-compose.yml, firefox/umbrel-app.yml
Update Firefox to the latest version.
Not tested yet.
=> Update Firefox to 132.0.2

gitlab/docker-compose.yml, gitlab/hooks/pre-start, gitlab/umbrel-app.yml
Updating GitLab to the latest version. Could not test it yet, not enough free memory on my Pi 5.
=> Update GitLab to version 17.6.1

vikunja/docker-compose.yml, vikunja/umbrel-app.yml
=> Update vikunja to version 0.24.5

zabbix/docker-compose.yml, zabbix/umbrel-app.yml
=> Update Zabbix to version 7.0.6

core-lightning-rtl/docker-compose.yml, core-lightning-rtl/umbrel-app.yml
Tested x86 and arm64 (fresh install and app update)
=> Update RTL (CLN) to 0.15.4-beta

wireguard/umbrel-app.yml
Just a small note to make the use of wireguard easier for users.
Fixes #1642
=> Wireguard: Add note about using nginx for external access

mattermost/docker-compose.yml, mattermost/umbrel-app.yml
=> Update Mattermost to v10.2.1

nostrudel/docker-compose.yml, nostrudel/umbrel-app.yml
Updates noStrudel to the latest release
=> update noStrudel to v0.42.0

helipad/docker-compose.yml, helipad/umbrel-app.yml
Updates Helipad from v0.2.0 to v0.2.1
=> Update Helipad to v0.2.1

zabbix/docker-compose.yml, zabbix/umbrel-app.yml
Tested fresh install and update on Umbrel Home.
=> Update zabbix to version 7.2.2

duplicati/docker-compose.yml, duplicati/umbrel-app.yml
=> Update duplicati to v2.1.0.2_beta_2024-11-29

matter-server/docker-compose.yml, matter-server/umbrel-app.yml
Matter Server
https://seeklogo.com/vector-logo/477960/matter-icon
There is not a lot of UI to show here as it is mainly used as a backend for home assistant and others.
=> App Submission: Matter Server

datum/docker-compose.yml, datum/umbrel-app.yml
update datum to [v2.2](https://github.com/OCEAN-xyz/datum_gateway/releases/tag/v0.2.2beta)
=> update datum to v2.2

matter-server/docker-compose.yml, matter-server/umbrel-app.yml
Tested update on Raspberry Pi 5 and install on Umbrel Home.
=> Update matter-server to version 7.0.1

peerswap/docker-compose.yml, peerswap/umbrel-app.yml
Bug fixes and improvements. Full changelog: https://github.com/Impa10r/peerswap-web/blob/main/CHANGELOG.md
=> Update PeerSwap to v1.7.6

firefox/docker-compose.yml, firefox/umbrel-app.yml
Tested update on Raspberry Pi 5 and fresh install on Umbrel Home.
=> Update Firefox to version 134.0.1

core-lightning/docker-compose.yml, core-lightning/umbrel-app.yml
- Updates cln-application to v0.0.6
- Updates code lightning to v24.11.1
=> Update cln-application and cln

firefox/docker-compose.yml, firefox/umbrel-app.yml
Tested update on Umbrel Home and fresh install on Raspberry Pi 5.
=> Update firefox to version 134.0.2

albyhub/umbrel-app.yml
Fixed the description to be more informative, added few links, according to Alby's guidelines
=> Update Alby Hub description

lobe-chat/docker-compose.yml, lobe-chat/umbrel-app.yml
Tested update on Umbrel Home and fresh install on Raspberry Pi 5.
=> Update Lobe Chat to version 1.49.6

budibase/docker-compose.yml, budibase/umbrel-app.yml
🤖 This is an automated summary of installation tests for budibase:
=> Update budibase to 3.4.0

ghostfolio/docker-compose.yml, ghostfolio/umbrel-app.yml
🤖 This is an automated summary of installation tests for ghostfolio:
=> Update ghostfolio to 2.137.1

audiobookshelf/docker-compose.yml, audiobookshelf/umbrel-app.yml
🤖 This is an automated summary of installation tests for audiobookshelf:
=> Update audiobookshelf to v2.19.0

file-browser/docker-compose.yml, file-browser/umbrel-app.yml
🤖 This is an automated summary of installation tests for file-browser:
=> Update file-browser to v2.32.0

autobrr/docker-compose.yml, autobrr/umbrel-app.yml
🤖 This is an automated summary of installation tests for autobrr:
=> Update autobrr to v1.58.0

plausible/docker-compose.yml, plausible/umbrel-app.yml
🤖 This is an automated summary of installation tests for plausible:
=> Update plausible to v2.1.5

vaultwarden/docker-compose.yml, vaultwarden/umbrel-app.yml
🤖 This is an automated summary of installation tests for vaultwarden:
=> Update vaultwarden to 1.33.1

lidarr/docker-compose.yml, lidarr/umbrel-app.yml
🤖 This is an automated summary of installation tests for lidarr:
=> Update lidarr to v2.9.6.4552

budibase/docker-compose.yml, budibase/umbrel-app.yml
🤖 This is an automated summary of installation tests for budibase:
=> Update budibase 3.4.3

mealie/docker-compose.yml, mealie/umbrel-app.yml
🤖 This is an automated summary of installation tests for mealie:
Tested fresh installation on Umbrel Home.
=> Update mealie to v2.6.0

home-assistant/docker-compose.yml, home-assistant/umbrel-app.yml
🤖 This is an automated summary of installation tests for home-assistant:
Tested fresh install on Umbrel Home and update on Raspberry Pi 5.
=> Update home assistant 2025.2.1

pingvin-share/docker-compose.yml, pingvin-share/hooks/pre-start, pingvin-share/umbrel-app.yml
🤖 This is an automated summary of installation tests for pingvin-share:
Tested update on Umbrel Home.
=> Update pingvin share v1.8.2

audiobookshelf/docker-compose.yml, audiobookshelf/umbrel-app.yml
🤖 This is an automated summary of installation tests for audiobookshelf:
Tested fresh install on Umbrel Home.
=> Update audiobookshelf to v2.19.1

home-assistant/docker-compose.yml, home-assistant/umbrel-app.yml
🤖 This is an automated summary of installation tests for home-assistant:
Tested update on Raspberry Pi 5.
=> Update home-assistant to 2025.2.2

synapse/docker-compose.yml, synapse/umbrel-app.yml
This is a pretty big update to synapse. 
Solved the issue of the error when updating to newer versions by adding a setting to the config in the start command.
Tested on my Raspberry Pi 5 and Umbrel Home. But as it is such a big update, some more testing would be great @nmfretz.
Fixes #763
=> Update synapse to version 1.123.0

synapse/docker-compose.yml, synapse/umbrel-app.yml
🤖 This is an automated summary of installation tests for synapse:
=> Update synapse to version v1.124.0

audiobookshelf/docker-compose.yml, audiobookshelf/umbrel-app.yml
🤖 This is an automated summary of installation tests for audiobookshelf:
=> Update audiobookshelf to version v2.19.4

budibase/docker-compose.yml, budibase/umbrel-app.yml
🤖 This is an automated summary of installation tests for budibase:
=> Update budibase to 3.4.16

firefly-iii/docker-compose.yml, firefly-iii/umbrel-app.yml
🤖 This is an automated summary of installation tests for firefly-iii:
=> Update firefly iii v6.2.7

firefly-iii-importer/docker-compose.yml, firefly-iii-importer/umbrel-app.yml
🤖 This is an automated summary of installation tests for firefly-iii-importer:
=> Update firefly iii importer v1.6.1

grafana/docker-compose.yml, grafana/umbrel-app.yml
🤖 This is an automated summary of installation tests for grafana:
=> Update grafana to v11.5.2

mainsail/docker-compose.yml, mainsail/umbrel-app.yml
🤖 This is an automated summary of installation tests for mainsail:
=> Update mainsail to v2.13.2

invoice-ninja/docker-compose.yml, invoice-ninja/umbrel-app.yml
🤖 This is an automated summary of installation tests for invoice-ninja:
=> Update invoice ninja to v5.11.41

pocketbase/docker-compose.yml, pocketbase/umbrel-app.yml
🤖 This is an automated summary of installation tests for pocketbase:
=> Update pocketbase to v0.25.7

navidrome/docker-compose.yml, navidrome/umbrel-app.yml
🤖 This is an automated summary of installation tests for navidrome:
=> Update navidrome to v0.54.5

wordpress/docker-compose.yml, wordpress/umbrel-app.yml
Tested the update on Umbrel Home and an Umbrel Dev instance.
=> Update wordpress to version 6.7.2

ghost/docker-compose.yml, ghost/umbrel-app.yml
🤖 This is an automated summary of installation tests for ghost:
=> Update ghost to version v5.110.1

mattermost/docker-compose.yml, mattermost/umbrel-app.yml
Tested update on Raspberry Pi 5 and fresh install on Umbrel Dev instance.
=> Update mattermost to v10.5.1

synapse/docker-compose.yml, synapse/umbrel-app.yml
Tested on Umbrel Dev instance.
=> Update synapse to v1.125.0

audiobookshelf/docker-compose.yml, audiobookshelf/umbrel-app.yml
🤖 This is an automated summary of installation tests for audiobookshelf:
=> Update audiobookshelf to version v2.19.5

pocketbase/docker-compose.yml, pocketbase/umbrel-app.yml
🤖 This is an automated summary of installation tests for pocketbase:
=> Update pocketbase to version v0.25.8

ollama/docker-compose.yml, ollama/umbrel-app.yml
🤖 This is an automated summary of installation tests for ollama:
=> Update ollama v0.5.12

umami/docker-compose.yml, umami/umbrel-app.yml
🤖 This is an automated summary of installation tests for umami:
=> Update umami to version v2.16.1

ghostfolio/docker-compose.yml, ghostfolio/umbrel-app.yml, maybe/docker-compose.yml, maybe/umbrel-app.yml
🤖 This is an automated summary of installation tests for ghostfolio:
=> Update ghostfolio to version 2.141.0

affine/docker-compose.yml, affine/umbrel-app.yml
Tested fresh install on Umbrel Dev instance and update on Umbrel Home.
=> Update affine to version 0.20.2

lobe-chat/docker-compose.yml, lobe-chat/umbrel-app.yml
Tested fresh install on Umbrel Dev instance and update on Umbrel Home.
=> Update Lobe Chat to version 1.65.1

firefox/docker-compose.yml, firefox/umbrel-app.yml
Tested fresh install on Umbrel dev instance and update on Umbrel Home.
=> Update firefox to version 135.0.1

immich/docker-compose.yml, immich/umbrel-app.yml
Tested fresh install on dev instance and update on Umbrel Home.
=> Update immich to version 1.127.0

home-assistant/docker-compose.yml, home-assistant/umbrel-app.yml
🤖 This is an automated summary of installation tests for home-assistant:
Tested fresh install on dev instance and update on Umbrel Home.
=> Update home-assistant to version 2025.2.5

pi-hole/umbrel-app.yml
Making sure that users don't break their internet connection if they have setup pi-hole as their DNS server.
Please review @nmfretz.
=> Add upgrading warning to pi-hole release notes

open-webui/docker-compose.yml, open-webui/umbrel-app.yml
Tested by updating files on Umbrel OS 1.4, and causing update to trigger:
- `open-webui/docker-compose.yml`
- `open-webui/umbrel-app.yml`
Update was successful without issues and existing data persists.
=> Update Open-webUI to v0.5.18

mempool/umbrel-app.yml
Hey there, want to update the tagline that shows for Mempool in the app store from "Explore the full bitcoin ecosystem" to "Be your own explorer".
=> Update mempool tagline to byoe

influxdb/umbrel-app.yml
Changes influxdb UI port to unused port
=> Change influxdb port

kimai/docker-compose.yml, kimai/umbrel-app.yml
Kimai
https://github.com/kimai/images/blob/main/kimai_logo_transparent.svg
https://www.kimai.org/images/screenshots/screenshot-dashboard.webp
https://www.kimai.org/images/screenshots/screenshot-reporting.webp
=> App Submission: Kimai

sqlitebrowser/umbrel-app.yml
Adds missing `dependencies: []`
=> Modify sqlitebrowser manifest

sqlitebrowser/umbrel-app.yml
=> Add missing manifest keys for sqlitebrowser

maybe/docker-compose.yml, maybe/umbrel-app.yml
Tested the update on a dev instance and on Umbrel Home.
=> Update maybe to version v0.4.3

bitcoin-knots/umbrel-app.yml
Small fixes to recent Knots release notes.
Context: https://github.com/getumbrel/umbrel-apps/pull/2292#issuecomment-2709352733
=> Fix Bitcoin Knots release notes

ghost/docker-compose.yml, ghost/umbrel-app.yml
🤖 This is an automated summary of installation tests for ghost:
=> Update ghost to version v5.110.3

rotki/docker-compose.yml, rotki/umbrel-app.yml
🤖 This is an automated summary of installation tests for rotki:
Tested on dev instance and Umbrel Home.
=> Update rotki v1.38.0

element/docker-compose.yml, element/umbrel-app.yml
🤖 This is an automated summary of installation tests for element:
=> Update element to v1.11.94

zoraxy/docker-compose.yml, zoraxy/umbrel-app.yml
🤖 This is an automated summary of installation tests for zoraxy:
=> Update zoraxy to version v3.1.9

homebox/docker-compose.yml, homebox/umbrel-app.yml
🤖 This is an automated summary of installation tests for homebox:
Tested on dev instance and Umbrel Home.
=> Update homebox v0.18.0

cobalt/umbrel-app.yml
Adds gallery image with processing server URL instructions
=> Cobalt - Add gallery image

downtify/docker-compose.yml, downtify/umbrel-app.yml
Update Downtify to version 0.3.1.
=> Update downtify to 0.3.1

umami/docker-compose.yml, umami/umbrel-app.yml
🤖 This is an automated summary of installation tests for umami:
=> Update umami to v2.17.0

home-assistant/docker-compose.yml, home-assistant/umbrel-app.yml
Tested fresh install on Umbrel Dev instance and update on Umbrel Home. All seemed fine after the update.
=> Update home assistant 2025.3.1

gitlab/docker-compose.yml, gitlab/hooks/pre-start, gitlab/umbrel-app.yml
Tested fresh install on Umbrel dev instance and update on Umbrel Home.
=> Update GitLab to version 17.9.1

firefox/docker-compose.yml, firefox/umbrel-app.yml
=> Update Firefox to version 136.0.1

photoprism/docker-compose.yml, photoprism/umbrel-app.yml
=> Update photoprism to version 250228-43447fa38

firefox/docker-compose.yml, firefox/umbrel-app.yml
=> Update firefox to version 136.0.2

affine/docker-compose.yml, affine/umbrel-app.yml
=> Update affine to version 0.20.5

technitium-dns/docker-compose.yml, technitium-dns/umbrel-app.yml
=> Update technitium-dns to version 13.4.3

obsidian/docker-compose.yml, obsidian/umbrel-app.yml
=> Update obsidian to version 1.8.9

readarr/docker-compose.yml, readarr/umbrel-app.yml
=> Update readarr to version 0.4.12.2753

snapdrop/docker-compose.yml, snapdrop/umbrel-app.yml
=> Update snapdrop to version b8b78cc2

downtify/docker-compose.yml, downtify/umbrel-app.yml
Update Downtify to version 0.3.2.
=> Update downtify to 0.3.2

robosats/docker-compose.yml, robosats/umbrel-app.yml
Update RoboSats to latest v0.7.5-alpha
=> Update RoboSats to v0.7.5-alpha

gitlab/docker-compose.yml, gitlab/hooks/pre-start, gitlab/umbrel-app.yml
=> Update GitLab to version 17.10.1

plex/docker-compose.yml, plex/umbrel-app.yml
=> Update plex to version 1.41.5.9522

qbittorrent/docker-compose.yml, qbittorrent/umbrel-app.yml
=> Update qbittorrent to version 5.0.4

metube/docker-compose.yml, metube/umbrel-app.yml
=> Update metube to version 2025-04-01

seafile/docker-compose.yml, seafile/umbrel-app.yml
This update adds the missing seadoc component to seafile.
Fixes #2471
=> Update seafile to include seadoc

datum/data/settings/datum_gateway_config.json, datum/docker-compose.yml, datum/hooks/pre-start, datum/umbrel-app.yml
I'm hitting a problem with this release its no longer possible to use `"pool_address": "enter your bitcoin address"` we need to put a valid bitcoin address, this can be now done in the UI but there is a permission error (I will fix that).
The second thing is the the autoconfig isn't working when upgrading from v0.2.2
=> update to datum `v0.3.1beta`

fulcrum/docker-compose.yml, fulcrum/umbrel-app.yml
Update works, but could not test a lot so far as it still seems to be syncing up.
Maybe @nmfretz or @sharknoon can test as well.
=> Update fulcrum to version 1.12.0

pingvin-share/docker-compose.yml, pingvin-share/umbrel-app.yml
Tested on Umbrel Home and dev instance.
=> Update pingvin-share to v1.11.1

robosats/docker-compose.yml, robosats/umbrel-app.yml
Update RoboSats to latest v0.7.6-alpha
=> Update RoboSats to v0.7.6-alpha

umami/docker-compose.yml, umami/umbrel-app.yml
Remove the app-proxy of umami due to the issues described in #2390
Also closes #2390.
Please take a look if it is ok like this @nmfretz
=> Remove app-proxy from umami

lobe-chat/umbrel-app.yml
Added full release notes for lobe-chat 1.79.10
=> Update release notes for lobe-chat 1.79.10

bitcoin-knots/umbrel-app.yml
Looking at https://apps.umbrel.com/app/bitcoin-knots it looks like double spacing is needed for correct paragraph spacing.
=> Update bitcoin-knots description spacing

file-drop/docker-compose.yml, file-drop/umbrel-app.yml
A decentralized, open-source solution for sharing images and videos using P2P technology.
=> App Submission: File Drop

.github/workflows/lint-apps.yml
pinned to commit 0f80d0bd783b67f21370c35b58b800e0613cfb91
=> Update linter action to 1.6.0

bitcoin-knots/umbrel-app.yml
Added a link to leo Haf's new open source site with a full step by step guide on how to migrate to knots - https://github.com/Retropex/bc-guide
=> Update bitcoin-knots description

lndg/docker-compose.yml, lndg/umbrel-app.yml
Updates LNDg to v1.10.0
https://github.com/cryptosharks131/lndg/releases/tag/v1.10.0
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/403254695?tag=v1.10.0
=> Update LNDg to v1.10.0

activepieces/docker-compose.yml, activepieces/exports.sh, activepieces/umbrel-app.yml
Activepieces
https://cdn.jsdelivr.net/gh/selfhst/icons/svg/activepieces.svg
=> App Submission: Activepieces

firefox/docker-compose.yml, firefox/umbrel-app.yml
=> Update Firefox to version 136.0.4

zabbix/docker-compose.yml, zabbix/umbrel-app.yml
=> Update zabbix to version 7.2.6

readarr/docker-compose.yml, readarr/umbrel-app.yml
=> Update readarr to version 0.4.15.2787

affine/docker-compose.yml, affine/umbrel-app.yml
=> Update affine to version 0.21.5

metube/docker-compose.yml, metube/umbrel-app.yml
=> Update metube to version 2025-04-16

qbittorrent/docker-compose.yml, qbittorrent/umbrel-app.yml
=> Update qbittorrent to version 5.1.0

btcpay-server/docker-compose.yml, btcpay-server/umbrel-app.yml
=> Update btcpay-server to version 2.1.1

bitcoin/docker-compose.yml, bitcoin/exports.sh, bitcoin/umbrel-app.yml
Tested fresh install and app update on both x86 and arm64 with major dependent apps in the ecosystem.
Please ping me if you run into any compatibility issues with dependent apps in the ecosystem.
=> Update Bitcoin Node to v29.0

bitcoin-knots/docker-compose.yml, bitcoin-knots/umbrel-app.yml
See here for changes: https://github.com/Retropex/umbrel-bitcoin/commit/baa498ffb0eddea663b0b053f4a10719ec1766e4
=> fix knots units

bitcoin-knots/docker-compose.yml, bitcoin-knots/umbrel-app.yml
See this two commits:
https://github.com/Retropex/umbrel-bitcoin/commit/bd0b345bfb233233e46bd834d882da4ece391dbb
https://github.com/Retropex/umbrel-bitcoin/commit/adef924cefa017e01d6ec3751e59e0f6b5d22917
=> Update bitcoin-knots to 28.1-3

affine/docker-compose.yml, affine/umbrel-app.yml
Tested on Umbrel dev instance and Umbrel Home.
=> Update affine to version 0.21.6

invidious/docker-compose.yml, invidious/umbrel-app.yml
=> Update invidious to version 2.20250517.0

zabbix/docker-compose.yml, zabbix/umbrel-app.yml
=> Update zabbix to version 7.2.7

metube/docker-compose.yml, metube/umbrel-app.yml
=> Update metube to version 2025-05-01

plex/docker-compose.yml, plex/umbrel-app.yml
=> Update plex to version 1.41.7.9799

invoice-ninja/docker-compose.yml, invoice-ninja/umbrel-app.yml
Tested on Umbrel Home and dev instance.
=> Update invoice-ninja to v5.11.80

invoice-ninja/docker-compose.yml, invoice-ninja/umbrel-app.yml
Needed so the nginx can access company logos and other data.
Also added the port to the APP_URL.
=> Update invoice-ninja nginx with storage mount and fix APP_URL

plex/docker-compose.yml, plex/umbrel-app.yml
=> Update plex to 1.41.7.9823

datum/docker-compose.yml, datum/umbrel-app.yml
https://github.com/OCEAN-xyz/datum_gateway/pull/118/commits/1be9b3637b8f6ef49adb2703e2ae101dd514b0a2
https://github.com/OCEAN-xyz/datum_gateway/pull/118/commits/47a65d0091a27bbb82b4c955ab1844ea1b2382fb
=> add dynamic units for the datum widget

plex/docker-compose.yml, plex/umbrel-app.yml
=> Update plex to version 1.41.8.9834

lndg/docker-compose.yml, lndg/umbrel-app.yml
Updates LNDg to v1.10.1
https://github.com/cryptosharks131/lndg/releases/tag/v1.10.1
https://github.com/cryptosharks131/lndg/pkgs/container/lndg/438277999?tag=v1.10.1
=> Update LNDg to v1.10.1

chromium/docker-compose.yml, chromium/umbrel-app.yml
Tested update on Umbrel dev instance.
=> Update chromium to version 8d3cb5f1

core-lightning-rtl/docker-compose.yml, core-lightning-rtl/umbrel-app.yml, ride-the-lightning/docker-compose.yml, ride-the-lightning/umbrel-app.yml
* Updates boltz-client to 2.7.1
=> Update Boltz Client (used by RTL)

endurain/docker-compose.yml, endurain/hooks/pre-start, endurain/settings.env, endurain/umbrel-app.yml
Endurain
https://cdn.jsdelivr.net/gh/selfhst/icons/svg/endurain.svg
https://docs.endurain.com/assets/gallery/screenshot_home.png
https://docs.endurain.com/assets/gallery/screenshot_activity_page_1.png
https://docs.endurain.com/assets/gallery/screenshot_gears_page.png
https://docs.endurain.com/assets/gallery/screenshot_health_weight.png
https://docs.endurain.com/assets/gallery/screenshot_profile.png
=> App Submission: Endurain

librechat/.env, librechat/data/api/librechat.yaml, librechat/docker-compose.yml, librechat/hooks/pre-start, librechat/umbrel-app.yml
LibreChat
https://cdn.jsdelivr.net/gh/selfhst/icons/svg/librechat.svg
=> App Submission: LibreChat

lnbits/docker-compose.yml, lnbits/umbrel-app.yml
Version `1.2.1` had the wrong sha256sum. Corrected it to fix issues with the update.
=> Update lnbits sha256sum of version 1.2.1

datum/docker-compose.yml, datum/umbrel-app.yml
=> update datum to v0.4.0beta

lightning-terminal/docker-compose.yml, lightning-terminal/umbrel-app.yml
hey yall, 
here with the v0.15.1-alpha release https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.15.1-alpha
=> lightning-terminal: v0.15.1-alpha

affine/docker-compose.yml, affine/umbrel-app.yml
=> Update affine to version 0.23.2

librechat/docker-compose.yml, librechat/umbrel-app.yml
=> Update librechat to version 0.7.9

gitlab/docker-compose.yml, gitlab/hooks/pre-start, gitlab/umbrel-app.yml
=> Update gitlab to version 18.2.1

.github/workflows/lint-apps.yml
https://github.com/sharknoon/umbrel-app-linter-action/releases/tag/v1.7.0
cc @sharknoon
=> Bump linter action to v1.7.0

audiobookshelf/docker-compose.yml, audiobookshelf/umbrel-app.yml
Tested update on Umbrel dev instance.
=> Update audiobookshelf to v2.29.0

open-webui/docker-compose.yml, open-webui/umbrel-app.yml
=> Update open-webui to version v0.6.26

public-pool-web/docker-compose.yml, public-pool-web/umbrel-app.yml
Hi,
more fixes.
Thanks in advance
=> Update public-pool-web to version 0.1.0

bitcoin-knots/docker-compose.yml, bitcoin-knots/exports.sh, bitcoin-knots/umbrel-app.yml
=> Update Knots for latest ecosystem compatibility

twenty/docker-compose.yml, twenty/umbrel-app.yml
Tested on Umbrel dev instance.
=> Update twenty to v1.5.3

invidious/docker-compose.yml, invidious/umbrel-app.yml
Tested on Umbrel dev instance.
=> Update invidious to version 2.20250913.0

twenty/docker-compose.yml, twenty/umbrel-app.yml
Tested on Umbrel dev instance.
=> Update twenty to v1.6.7

matter-server/docker-compose.yml, matter-server/umbrel-app.yml
=> Update matter-server to version 8.1.1
